//
// File generated by /afs/cern.ch/ams/Offline/root/linux/root-v5-34-9-icc64-slc6/bin/rootcint at Sun Oct 23 21:57:03 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME rootdict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "rootdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void SimpleHitState_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_SimpleHitState(void *p = 0);
   static void *newArray_SimpleHitState(Long_t size, void *p);
   static void delete_SimpleHitState(void *p);
   static void deleteArray_SimpleHitState(void *p);
   static void destruct_SimpleHitState(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SimpleHitState*)
   {
      ::SimpleHitState *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SimpleHitState >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SimpleHitState", ::SimpleHitState::Class_Version(), "./SimpleHitState.h", 6,
                  typeid(::SimpleHitState), DefineBehavior(ptr, ptr),
                  &::SimpleHitState::Dictionary, isa_proxy, 4,
                  sizeof(::SimpleHitState) );
      instance.SetNew(&new_SimpleHitState);
      instance.SetNewArray(&newArray_SimpleHitState);
      instance.SetDelete(&delete_SimpleHitState);
      instance.SetDeleteArray(&deleteArray_SimpleHitState);
      instance.SetDestructor(&destruct_SimpleHitState);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SimpleHitState*)
   {
      return GenerateInitInstanceLocal((::SimpleHitState*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SimpleHitState*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *SimpleHitState::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *SimpleHitState::Class_Name()
{
   return "SimpleHitState";
}

//______________________________________________________________________________
const char *SimpleHitState::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::SimpleHitState*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SimpleHitState::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::SimpleHitState*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SimpleHitState::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::SimpleHitState*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SimpleHitState::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::SimpleHitState*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void SimpleHitState::Streamer(TBuffer &R__b)
{
   // Stream an object of class SimpleHitState.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(SimpleHitState::Class(),this);
   } else {
      R__b.WriteClassBuffer(SimpleHitState::Class(),this);
   }
}

//______________________________________________________________________________
void SimpleHitState::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SimpleHitState.
      TClass *R__cl = ::SimpleHitState::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", &x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", &y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "z", &z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "layer", &layer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hittype", &hittype);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "YOnly", &YOnly);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "XOnly", &XOnly);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Amp", &Amp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "AmpY", &AmpY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pathlength", &pathlength);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_SimpleHitState(void *p) {
      return  p ? new(p) ::SimpleHitState : new ::SimpleHitState;
   }
   static void *newArray_SimpleHitState(Long_t nElements, void *p) {
      return p ? new(p) ::SimpleHitState[nElements] : new ::SimpleHitState[nElements];
   }
   // Wrapper around operator delete
   static void delete_SimpleHitState(void *p) {
      delete ((::SimpleHitState*)p);
   }
   static void deleteArray_SimpleHitState(void *p) {
      delete [] ((::SimpleHitState*)p);
   }
   static void destruct_SimpleHitState(void *p) {
      typedef ::SimpleHitState current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::SimpleHitState

/********************************************************
* rootdict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__INTEL_COMPILER) && (__INTEL_COMPILER >= 1100)
# pragma warning (disable 21)
# pragma warning (disable 191)
#endif

extern "C" void G__cpp_reset_tagtablerootdict();

extern "C" void G__set_cpp_environmentrootdict() {
  G__cpp_reset_tagtablerootdict();
}
#include <new>
extern "C" int G__cpp_dllrevrootdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SimpleHitState */
static int G__rootdict_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SimpleHitState* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SimpleHitState[n];
     } else {
       p = new((void*) gvp) SimpleHitState[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SimpleHitState;
     } else {
       p = new((void*) gvp) SimpleHitState;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictLN_SimpleHitState));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SimpleHitState* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 10:
     //m: 10
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SimpleHitState(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (float) G__double(libp->para[7])
, (float) G__double(libp->para[8]), (float) G__double(libp->para[9]));
     } else {
       p = new((void*) gvp) SimpleHitState(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (float) G__double(libp->para[7])
, (float) G__double(libp->para[8]), (float) G__double(libp->para[9]));
     }
     break;
   case 9:
     //m: 9
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SimpleHitState(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (float) G__double(libp->para[7])
, (float) G__double(libp->para[8]));
     } else {
       p = new((void*) gvp) SimpleHitState(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (float) G__double(libp->para[7])
, (float) G__double(libp->para[8]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictLN_SimpleHitState));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SimpleHitState*) G__getstructoffset())->operator()(*((SimpleHitState*) G__int(libp->para[0])), *((SimpleHitState*) G__int(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SimpleHitState::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SimpleHitState::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SimpleHitState::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SimpleHitState::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SimpleHitState*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SimpleHitState::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SimpleHitState::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SimpleHitState::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SimpleHitState::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__rootdict_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SimpleHitState* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SimpleHitState(*(SimpleHitState*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictLN_SimpleHitState));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SimpleHitState G__TSimpleHitState;
static int G__rootdict_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SimpleHitState*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SimpleHitState*) (soff+(sizeof(SimpleHitState)*i)))->~G__TSimpleHitState();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SimpleHitState*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SimpleHitState*) (soff))->~G__TSimpleHitState();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__rootdict_168_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SimpleHitState* dest = (SimpleHitState*) G__getstructoffset();
   *dest = *(SimpleHitState*) libp->para[0].ref;
   const SimpleHitState& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SimpleHitState */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrootdict {
 public:
  G__Sizep2memfuncrootdict(): p(&G__Sizep2memfuncrootdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrootdict::*p)();
};

size_t G__get_sizep2memfuncrootdict()
{
  G__Sizep2memfuncrootdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerootdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__rootdictLN_SimpleHitState))) {
     SimpleHitState *G__Lderived;
     G__Lderived=(SimpleHitState*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_SimpleHitState),G__get_linked_tagnum(&G__rootdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerootdict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SimpleHitState */
static void G__setup_memvarSimpleHitState(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rootdictLN_SimpleHitState));
   { SimpleHitState *p; p=(SimpleHitState*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),100,0,0,-1,-1,-1,1,"x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y)-(long)(p)),100,0,0,-1,-1,-1,1,"y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->z)-(long)(p)),100,0,0,-1,-1,-1,1,"z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->layer)-(long)(p)),105,0,0,-1,-1,-1,1,"layer=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hittype)-(long)(p)),105,0,0,-1,-1,-1,1,"hittype=",0,"TrTrack:1 , ECALShower:2, TRDKHit:3");
   G__memvar_setup((void*)((long)(&p->YOnly)-(long)(p)),105,0,0,-1,-1,-1,1,"YOnly=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->XOnly)-(long)(p)),105,0,0,-1,-1,-1,1,"XOnly=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Amp)-(long)(p)),102,0,0,-1,-1,-1,1,"Amp=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->AmpY)-(long)(p)),102,0,0,-1,-1,-1,1,"AmpY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pathlength)-(long)(p)),102,0,0,-1,-1,-1,1,"pathlength=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrootdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSimpleHitState(void) {
   /* SimpleHitState */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rootdictLN_SimpleHitState));
   G__memfunc_setup("SimpleHitState",1424,G__rootdict_168_0_1, 105, G__get_linked_tagnum(&G__rootdictLN_SimpleHitState), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SimpleHitState",1424,G__rootdict_168_0_2, 105, G__get_linked_tagnum(&G__rootdictLN_SimpleHitState), -1, 0, 10, 1, 1, 0, 
"f - - 0 - _x f - - 0 - _y "
"f - - 0 - _z i - - 0 - _layer "
"i - - 0 - _hittype i - - 0 - _YOnly "
"i - - 0 - _XOnly f - - 0 - _Amp "
"f - - 0 - _AmpY f - - 0 '0' _path", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator()",957,G__rootdict_168_0_3, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'SimpleHitState' - 0 - i u 'SimpleHitState' - 0 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__rootdict_168_0_4, 85, G__get_linked_tagnum(&G__rootdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SimpleHitState::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__rootdict_168_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SimpleHitState::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__rootdict_168_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SimpleHitState::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__rootdict_168_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SimpleHitState::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__rootdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__rootdict_168_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__rootdict_168_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SimpleHitState::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__rootdict_168_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SimpleHitState::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__rootdict_168_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SimpleHitState::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__rootdict_168_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SimpleHitState::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("SimpleHitState", 1424, G__rootdict_168_0_16, (int) ('i'), G__get_linked_tagnum(&G__rootdictLN_SimpleHitState), -1, 0, 1, 1, 1, 0, "u 'SimpleHitState' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SimpleHitState", 1550, G__rootdict_168_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__rootdict_168_0_18, (int) ('u'), G__get_linked_tagnum(&G__rootdictLN_SimpleHitState), -1, 1, 1, 1, 1, 0, "u 'SimpleHitState' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrootdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrootdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrootdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__rootdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_SimpleHitState = { "SimpleHitState" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerootdict() {
  G__rootdictLN_TClass.tagnum = -1 ;
  G__rootdictLN_TBuffer.tagnum = -1 ;
  G__rootdictLN_TMemberInspector.tagnum = -1 ;
  G__rootdictLN_TObject.tagnum = -1 ;
  G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_SimpleHitState.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerootdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__rootdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rootdictLN_SimpleHitState),sizeof(SimpleHitState),-1,324864,(char*)NULL,G__setup_memvarSimpleHitState,G__setup_memfuncSimpleHitState);
}
extern "C" void G__cpp_setuprootdict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprootdict()");
  G__set_cpp_environmentrootdict();
  G__cpp_setup_tagtablerootdict();

  G__cpp_setup_inheritancerootdict();

  G__cpp_setup_typetablerootdict();

  G__cpp_setup_memvarrootdict();

  G__cpp_setup_memfuncrootdict();
  G__cpp_setup_globalrootdict();
  G__cpp_setup_funcrootdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrootdict();
  return;
}
class G__cpp_setup_initrootdict {
  public:
    G__cpp_setup_initrootdict() { G__add_setup_func("rootdict",(G__incsetup)(&G__cpp_setuprootdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrootdict() { G__remove_setup_func("rootdict"); }
};
G__cpp_setup_initrootdict G__cpp_setup_initializerrootdict;

