// Class: ReadBDTD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTD
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : hchou
Date           : Sat Mar 14 10:50:12 2020
Host           : Linux lcgapp-centos7-x86-64-25.cern.ch 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/h/hchou/AMSProject/apflux
Training events: 250000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
lxin                          lxin                          lxin                          lxin                          units                             'F'    [-13.6213407516,3.62821340561]
lyin                          lyin                          lyin                          lyin                          units                             'F'    [-12.6075334549,5.60300254822]
lxex                          lxex                          lxex                          lxex                          units                             'F'    [-5.39945793152,3.47817993164]
lyex                          lyex                          lyex                          lyex                          units                             'F'    [-5.38689899445,5.96375608444]
nlxin                         nlxin                         nlxin                         nlxin                         units                             'F'    [0.000393887341488,6.48450136185]
nlyin                         nlyin                         nlyin                         nlyin                         units                             'F'    [0.00157873239368,19.9187240601]
nlxex                         nlxex                         nlxex                         nlxex                         units                             'F'    [0.0568397901952,7.20413017273]
nlyex                         nlyex                         nlyex                         nlyex                         units                             'F'    [0.0753777995706,33.1219215393]
lxinC                         lxinC                         lxinC                         lxinC                         units                             'F'    [-11.7956790924,5.34278678894]
lyinC                         lyinC                         lyinC                         lyinC                         units                             'F'    [-13.0330018997,8.29169178009]
lxexC                         lxexC                         lxexC                         lxexC                         units                             'F'    [-5.98990488052,4.65408277512]
lyexC                         lyexC                         lyexC                         lyexC                         units                             'F'    [-6.09984731674,9.26662731171]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTDNode

#ifndef BDTDNode__def
#define BDTDNode__def

class BDTDNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTDNode ( BDTDNode* left,BDTDNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTDNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTDNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTDNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTDNode*   fLeft;     // pointer to the left daughter node
   BDTDNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTDNode::~BDTDNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTDNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTDNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTD : public IClassifierReader {

 public:

   // constructor
   ReadBDTD( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDTD" ),
        fNvars( 12 )
   {
      // the training input variables
      const char* inputVars[] = { "lxin", "lyin", "lxex", "lyex", "nlxin", "nlyin", "nlxex", "nlyex", "lxinC", "lyinC", "lxexC", "lyexC" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -36.9916152954102;
      fVmax[0] = 16.0991554260254;
      fVmin[1] = -23.3115634918213;
      fVmax[1] = 11.990514755249;
      fVmin[2] = -7.82190799713135;
      fVmax[2] = 25.4478912353516;
      fVmin[3] = -11.9930953979492;
      fVmax[3] = 18.7951183319092;
      fVmin[4] = -7.6027569770813;
      fVmax[4] = 17.9718780517578;
      fVmin[5] = -27.6613731384277;
      fVmax[5] = 27.2652435302734;
      fVmin[6] = -0.597503900527954;
      fVmax[6] = 15.8361597061157;
      fVmin[7] = -3.3253653049469;
      fVmax[7] = 73.8278503417969;
      fVmin[8] = -30.4487037658691;
      fVmax[8] = 34.2172966003418;
      fVmin[9] = -18.9261150360107;
      fVmax[9] = 28.1801795959473;
      fVmin[10] = -28.1813106536865;
      fVmax[10] = 9.20821571350098;
      fVmin[11] = -43.1375617980957;
      fVmax[11] = 18.1437511444092;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadBDTD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][12][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTDNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTD::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTDNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTDNode*)current->GetRight();
         else current=(BDTDNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDTD::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.599410557425202);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.97398, 1, 1, 0.849996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.312107,-99) , 
3, 2.36519, 1, 0, 0.742088,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43797,-99) , 
7, 2.41043, 1, 0, 0.473722,-99) , 
NN(
0, 
0, 
-1, -1.67612, 1, -1, 0.218895,-99) , 
7, 3.01427, 1, 0, 0.280143,-99) , 
11, -2.28335, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.453954);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.42193, 1, 1, 0.929726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465475,-99) , 
3, 2.02989, 1, 0, 0.609383,-99) , 
3, 1.19162, 1, 0, 0.690081,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.276626,-99) , 
11, -1.31063, 1, 0, 0.452924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.175418,-99) , 
3, 2.34068, 1, 0, 0.378465,-99) , 
11, -2.28335, 1, 0, 0.521745,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.392005);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.14458, 0, 1, 0.893646,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.735803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481533,-99) , 
10, -2.40963, 1, 0, 0.614154,-99) , 
3, 1.19162, 1, 0, 0.677107,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409816,-99) , 
9, -4.04275, 1, 0, 0.57496,-99) , 
NN(
0, 
0, 
-1, -3.81083, 1, -1, 0.305024,-99) , 
3, 1.23808, 1, 0, 0.395691,-99) , 
11, -2.28335, 1, 0, 0.52491,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.335677);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.96735, 1, 1, 0.706085,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4116,-99) , 
3, 1.23808, 1, 0, 0.485464,-99) , 
11, -2.14507, 1, 0, 0.601333,-99) , 
NN(
0, 
0, 
-1, 3.39375, 1, -1, 0.305321,-99) , 
2, 1.68375, 1, 0, 0.550655,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.334963);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.721711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471139,-99) , 
10, -1.81857, 1, 0, 0.664737,-99) , 
NN(
0, 
0, 
-1, -4.7195, 0, -1, 0.399663,-99) , 
7, 4.02256, 1, 0, 0.58783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308983,-99) , 
9, -3.22402, 1, 0, 0.539979,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.267754);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.71381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463602,-99) , 
1, 2.3473, 1, 0, 0.61207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41344,-99) , 
3, 2.66796, 1, 0, 0.584127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384636,-99) , 
9, -3.22402, 1, 0, 0.550248,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.228959);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.20185, 1, 1, 0.615557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405709,-99) , 
10, -0.899673, 1, 0, 0.592241,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311529,-99) , 
6, 4.00542, 1, 0, 0.414311,-99) , 
2, 1.68375, 1, 0, 0.562634,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.177755);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.57387, 1, 1, 0.751747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494892,-99) , 
11, -1.40373, 1, 0, 0.632914,-99) , 
NN(
NN(
0, 
0, 
-1, 0.543251, 1, 1, 0.644866,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336938,-99) , 
9, -3.81083, 1, 0, 0.449513,-99) , 
11, -2.9153, 1, 0, 0.488523,-99) , 
3, 1.20185, 1, 0, 0.526688,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.226051);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.43121, 1, 1, 0.750352,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429349,-99) , 
11, -2.04021, 1, 0, 0.541829,-99) , 
3, 0.57351, 1, 0, 0.632844,-99) , 
NN(
NN(
0, 
0, 
-1, 0.543251, 1, 1, 0.603194,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38727,-99) , 
7, 3.2097, 1, 0, 0.43228,-99) , 
11, -2.9153, 1, 0, 0.465951,-99) , 
3, 1.20185, 1, 0, 0.50967,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.162676);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.40373, 1, 1, 0.6172,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40241,-99) , 
8, -4.39513, 0, 0, 0.494586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343194,-99) , 
2, 1.68375, 1, 0, 0.469719,-99) , 
3, 1.20185, 1, 0, 0.507757,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.160052);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.57387, 1, 1, 0.657091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493099,-99) , 
11, -1.40373, 1, 0, 0.578107,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434541,-99) , 
3, 1.72048, 1, 0, 0.513748,-99) , 
NN(
0, 
0, 
-1, 1.22807, 1, -1, 0.414573,-99) , 
3, 2.03963, 1, 0, 0.461457,-99) , 
3, 1.20185, 1, 0, 0.491362,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.137995);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.57351, 1, 1, 0.600073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394444,-99) , 
11, -1.76914, 1, 0, 0.488996,-99) , 
3, 1.20185, 1, 0, 0.517151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340625,-99) , 
6, 5.66294, 1, 0, 0.50443,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.158994);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637039,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473863,-99) , 
3, 1.65255, 1, 0, 0.499184,-99) , 
0, 1.01887, 1, 0, 0.558494,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427688,-99) , 
3, 1.7778, 1, 0, 0.491285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319308,-99) , 
5, 4.92319, 1, 0, 0.467652,-99) , 
2, 0.0994728, 1, 0, 0.488271,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.13283);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460172,-99) , 
2, 0.778438, 1, 0, 0.535623,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439024,-99) , 
3, 0.84365, 1, 0, 0.45989,-99) , 
0, 1.89022, 1, 0, 0.504518,-99) , 
NN(
0, 
0, 
-1, 3.39375, 1, -1, 0.410045,-99) , 
2, 1.68375, 1, 0, 0.488929,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.117557);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614095,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392554,-99) , 
11, -1.2074, 1, 0, 0.511712,-99) , 
NN(
0, 
0, 
-1, -4.51598, 0, -1, 0.43147,-99) , 
7, 4.02256, 1, 0, 0.485998,-99) , 
1, 0.223155, 1, 0, 0.496157,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.142849);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.08176, 1, 1, 0.587693,-99) , 
NN(
0, 
0, 
-1, 1.7371, 0, -1, 0.388745,-99) , 
5, 4.58242, 1, 0, 0.526155,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410155,-99) , 
2, 1.53055, 1, 0, 0.490982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343177,-99) , 
1, 2.86481, 1, 0, 0.462255,-99) , 
1, 1.90421, 1, 0, 0.490042,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.114861);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.08176, 1, 1, 0.552701,-99) , 
NN(
0, 
0, 
-1, 1.7371, 0, -1, 0.423178,-99) , 
5, 4.58242, 1, 0, 0.512731,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422397,-99) , 
7, 3.75737, 1, 0, 0.46961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376057,-99) , 
1, 2.86481, 1, 0, 0.4517,-99) , 
1, 1.90421, 1, 0, 0.478148,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.110817);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493306,-99) , 
9, -4.918, 1, 0, 0.515945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356305,-99) , 
7, 4.40082, 1, 0, 0.487937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407119,-99) , 
3, 2.66796, 1, 0, 0.474872,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.125407);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38929,-99) , 
7, 4.40082, 1, 0, 0.519251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432221,-99) , 
3, 2.66796, 1, 0, 0.505224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393591,-99) , 
6, 5.66294, 1, 0, 0.49739,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.105948);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.890855, 1, 1, 0.556631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451281,-99) , 
9, -3.31542, 1, 0, 0.52353,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466719,-99) , 
0, 1.31023, 1, 0, 0.504386,-99) , 
NN(
0, 
0, 
-1, 4.50852, 1, -1, 0.442506,-99) , 
2, 0.358102, 1, 0, 0.461278,-99) , 
1, 1.90421, 1, 0, 0.488176,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0799598);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582645,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486638,-99) , 
3, 0.571155, 1, 0, 0.504769,-99) , 
NN(
0, 
0, 
-1, 4.88038, 1, -1, 0.445817,-99) , 
4, 3.69629, 0, 0, 0.487098,-99) , 
1, 0.223155, 1, 0, 0.494481,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.08775);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.53498, 1, 1, 0.539561,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43273,-99) , 
7, 3.34801, 0, 0, 0.491165,-99) , 
9, -3.96708, 1, 0, 0.520305,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402145,-99) , 
2, 0.424049, 1, 0, 0.457005,-99) , 
10, -1.47451, 1, 0, 0.508668,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0714388);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.525905, 1, 1, 0.521705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36874,-99) , 
5, 5.08333, 1, 0, 0.506574,-99) , 
NN(
0, 
0, 
-1, 4.88038, 1, -1, 0.450824,-99) , 
4, 3.3578, 0, 0, 0.496129,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0993291);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.43121, 1, 1, 0.611695,-99) , 
NN(
0, 
0, 
-1, 4.41787, 1, -1, 0.45905,-99) , 
3, 0.57351, 1, 0, 0.522719,-99) , 
NN(
NN(
0, 
0, 
-1, 1.85459, 0, 1, 0.534441,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445203,-99) , 
0, 0.799896, 1, 0, 0.457554,-99) , 
8, -3.58425, 0, 0, 0.476378,-99) , 
3, 1.20185, 1, 0, 0.487805,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0837383);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.43121, 1, 1, 0.587857,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416044,-99) , 
5, 4.41787, 1, 0, 0.483796,-99) , 
3, 0.57351, 1, 0, 0.527022,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494529,-99) , 
3, 2.03965, 0, 0, 0.537695,-99) , 
NN(
0, 
0, 
-1, -1.6384, 1, -1, 0.467203,-99) , 
11, -2.9153, 1, 0, 0.481493,-99) , 
3, 1.20185, 1, 0, 0.492696,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0540161);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.53498, 1, 1, 0.52638,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457308,-99) , 
1, 1.66633, 0, 0, 0.488853,-99) , 
9, -3.96708, 1, 0, 0.51145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430554,-99) , 
2, 0.424049, 1, 0, 0.463416,-99) , 
10, -1.47451, 1, 0, 0.502681,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0472164);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556447,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493759,-99) , 
7, 2.81019, 1, 0, 0.501885,-99) , 
NN(
0, 
0, 
-1, 1.44895, 1, -1, 0.450634,-99) , 
8, -4.57996, 0, 0, 0.490076,-99) , 
1, 0.223155, 1, 0, 0.49514,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0747912);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.96718, 1, 1, 0.547197,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472327,-99) , 
11, -2.63555, 1, 0, 0.505148,-99) , 
10, -2.5455, 1, 0, 0.523211,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465864,-99) , 
11, -1.63161, 1, 0, 0.504438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424877,-99) , 
6, 4.88038, 1, 0, 0.490488,-99) , 
4, 4.57564, 0, 0, 0.502431,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0678063);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.0329, 0, 1, 0.523487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418466,-99) , 
7, 4.40082, 1, 0, 0.50549,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463975,-99) , 
3, 2.66796, 1, 0, 0.498812,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0530647);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551021,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486454,-99) , 
9, -4.04967, 1, 0, 0.525989,-99) , 
NN(
0, 
0, 
-1, 1.99401, 1, -1, 0.479028,-99) , 
1, 1.34389, 1, 0, 0.4873,-99) , 
1, 0.223155, 1, 0, 0.492174,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0639916);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486945,-99) , 
6, 4.50668, 0, 0, 0.543058,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484692,-99) , 
9, -4.10857, 1, 0, 0.504014,-99) , 
2, 0.767018, 1, 0, 0.521331,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491202,-99) , 
3, 1.4362, 1, 0, 0.507866,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424995,-99) , 
2, 0.709765, 1, 0, 0.460378,-99) , 
6, 4.09783, 1, 0, 0.490051,-99) , 
4, 4.57564, 0, 0, 0.501466,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0593617);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.00942, 0, 1, 0.530019,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493059,-99) , 
7, 3.98619, 0, 0, 0.548296,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47288,-99) , 
7, 3.13205, 1, 0, 0.484887,-99) , 
3, 0.980524, 1, 0, 0.496226,-99) , 
6, 3.31527, 1, 0, 0.503399,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0507218);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.50668, 0, 1, 0.543066,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488594,-99) , 
1, 1.90421, 1, 0, 0.503364,-99) , 
2, 0.767018, 1, 0, 0.520965,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4725,-99) , 
6, 4.29343, 1, 0, 0.503165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438545,-99) , 
8, -4.9563, 0, 0, 0.494949,-99) , 
4, 4.57564, 0, 0, 0.504444,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0590771);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464249,-99) , 
11, -1.49698, 1, 0, 0.525943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480761,-99) , 
8, -4.65142, 0, 0, 0.516412,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481339,-99) , 
11, -2.16382, 0, 0, 0.515159,-99) , 
NN(
0, 
0, 
-1, -1.63161, 1, -1, 0.480529,-99) , 
1, 1.63289, 1, 0, 0.491519,-99) , 
4, 4.57564, 0, 0, 0.500602,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0840809);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54486,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658544,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40585,-99) , 
11, -1.57904, 1, 0, 0.493103,-99) , 
3, 0.250772, 1, 0, 0.50255,-99) , 
9, -5.46717, 1, 0, 0.505939,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0767457);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.98865, 1, 1, 0.534447,-99) , 
NN(
0, 
0, 
-1, 3.65163, 0, -1, 0.457035,-99) , 
5, 4.40397, 1, 0, 0.508306,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527584,-99) , 
NN(
0, 
0, 
-1, -2.57887, 1, -1, 0.456266,-99) , 
3, 2.36519, 0, 0, 0.475344,-99) , 
11, -2.28335, 0, 0, 0.49294,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0625629);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.947124, 1, 1, 0.517635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408567,-99) , 
11, -0.879679, 1, 0, 0.500795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457308,-99) , 
3, 2.66796, 1, 0, 0.493755,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0926668);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447312,-99) , 
1, 2.67832, 1, 0, 0.516895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448565,-99) , 
3, 2.34068, 1, 0, 0.499222,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48167,-99) , 
0, 0.784952, 1, 0, 0.502647,-99) , 
NN(
0, 
0, 
-1, 3.6006, 0, -1, 0.444093,-99) , 
10, -2.40963, 0, 0, 0.4735,-99) , 
11, -2.28335, 0, 0, 0.487203,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0357466);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533713,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474761,-99) , 
0, 0.94837, 0, 0, 0.499148,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443628,-99) , 
7, 3.3604, 1, 0, 0.466761,-99) , 
8, -4.57996, 0, 0, 0.491705,-99) , 
1, 0.223155, 1, 0, 0.494915,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0328931);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530181,-99) , 
NN(
0, 
0, 
-1, 2.91822, 1, -1, 0.485249,-99) , 
1, 0.783542, 1, 0, 0.488156,-99) , 
1, 0.223155, 1, 0, 0.490955,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0318475);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499642,-99) , 
9, -5.16835, 1, 0, 0.506672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454409,-99) , 
5, 2.8637, 0, 0, 0.501043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458847,-99) , 
11, -2.662, 1, 0, 0.478412,-99) , 
10, -1.47451, 1, 0, 0.496937,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0358705);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.02256, 0, 1, 0.513012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462315,-99) , 
5, 2.8637, 0, 0, 0.507558,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453607,-99) , 
9, -4.12775, 1, 0, 0.481596,-99) , 
10, -1.47451, 1, 0, 0.502851,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.073734);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437743,-99) , 
3, 0.902641, 1, 0, 0.473904,-99) , 
3, 0.57351, 1, 0, 0.510531,-99) , 
NN(
NN(
0, 
0, 
-1, 2.03965, 0, 1, 0.538506,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465067,-99) , 
3, 1.79421, 1, 0, 0.481011,-99) , 
11, -2.9153, 1, 0, 0.492765,-99) , 
3, 1.20185, 1, 0, 0.497092,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0322836);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525583,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492866,-99) , 
9, -4.51598, 1, 0, 0.500472,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440376,-99) , 
0, 1.44895, 1, 0, 0.476305,-99) , 
8, -4.57996, 0, 0, 0.494927,-99) , 
1, 0.223155, 1, 0, 0.497267,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0229582);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -5.16835, 1, 1, 0.506204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474172,-99) , 
5, 2.8637, 0, 0, 0.502754,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467974,-99) , 
11, -2.662, 1, 0, 0.480896,-99) , 
10, -1.47451, 1, 0, 0.498795,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0376009);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494455,-99) , 
7, 2.81019, 1, 0, 0.504147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440939,-99) , 
9, -2.59424, 1, 0, 0.498044,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446666,-99) , 
0, 0.930364, 0, 0, 0.474532,-99) , 
10, -3.25496, 0, 0, 0.495524,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0340676);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498829,-99) , 
1, 1.53498, 1, 0, 0.510565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450228,-99) , 
9, -2.59424, 1, 0, 0.504749,-99) , 
NN(
0, 
0, 
-1, 0.930364, 0, -1, 0.47425,-99) , 
10, -3.25496, 0, 0, 0.50148,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0353826);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.68045, 0, 1, 0.515218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458674,-99) , 
9, -2.59424, 1, 0, 0.509773,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46444,-99) , 
0, 0.930364, 0, 0, 0.482751,-99) , 
10, -3.25496, 0, 0, 0.506878,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0573358);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.68124, 0, 1, 0.539027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468763,-99) , 
6, 3.66604, 0, 0, 0.513979,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460251,-99) , 
11, -1.23586, 1, 0, 0.509902,-99) , 
NN(
0, 
0, 
-1, 4.50852, 1, -1, 0.470977,-99) , 
2, 1.30655, 1, 0, 0.496522,-99) , 
2, 0.0994728, 1, 0, 0.500475,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0561605);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499227,-99) , 
7, 4.05409, 0, 0, 0.523039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456467,-99) , 
7, 4.42308, 1, 0, 0.507005,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531181,-99) , 
NN(
0, 
0, 
-1, -2.57887, 1, -1, 0.47443,-99) , 
3, 2.36519, 0, 0, 0.489626,-99) , 
11, -2.28335, 0, 0, 0.498847,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0652589);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490198,-99) , 
9, -4.43426, 1, 0, 0.531551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470431,-99) , 
7, 4.42308, 1, 0, 0.516842,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49945,-99) , 
8, -3.70599, 0, 0, 0.520836,-99) , 
NN(
0, 
0, 
-1, -3.96708, 0, -1, 0.47121,-99) , 
10, -2.40963, 0, 0, 0.496139,-99) , 
11, -2.28335, 0, 0, 0.507124,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.072002);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574667,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469149,-99) , 
1, 2.02494, 0, 0, 0.500655,-99) , 
3, 0.57351, 1, 0, 0.531489,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466508,-99) , 
11, -1.47336, 1, 0, 0.518052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46111,-99) , 
3, 2.87741, 1, 0, 0.509506,-99) , 
3, 1.20185, 1, 0, 0.514843,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0829531);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573475,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445851,-99) , 
3, 1.89793, 1, 0, 0.507414,-99) , 
1, 0.75327, 1, 0, 0.518733,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468193,-99) , 
7, 3.96735, 1, 0, 0.514824,-99) , 
NN(
0, 
0, 
-1, -3.96708, 0, -1, 0.475793,-99) , 
10, -2.40963, 0, 0, 0.495372,-99) , 
11, -2.28335, 0, 0, 0.507752,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0421159);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.96708, 1, 1, 0.524143,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482879,-99) , 
8, -3.82181, 0, 0, 0.501435,-99) , 
10, -2.74626, 1, 0, 0.510699,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474132,-99) , 
2, 0.424049, 1, 0, 0.487106,-99) , 
10, -1.47451, 1, 0, 0.506419,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0503742);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478801,-99) , 
7, 4.19255, 1, 0, 0.514812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445114,-99) , 
1, 2.87397, 1, 0, 0.480471,-99) , 
1, 2.49002, 1, 0, 0.505795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475847,-99) , 
4, 5.79348, 1, 0, 0.503805,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0732708);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594415,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470933,-99) , 
10, -2.33239, 1, 0, 0.492963,-99) , 
3, 0.822595, 1, 0, 0.516362,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491079,-99) , 
7, 2.97265, 1, 0, 0.570174,-99) , 
NN(
0, 
0, 
-1, -1.79504, 1, -1, 0.47337,-99) , 
9, -4.73392, 1, 0, 0.491748,-99) , 
7, 4.02256, 0, 0, 0.499748,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0458249);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.83326, 0, 1, 0.551192,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458314,-99) , 
7, 4.40082, 1, 0, 0.504971,-99) , 
0, 0.542902, 1, 0, 0.511352,-99) , 
NN(
0, 
0, 
-1, 0.930364, 0, -1, 0.482536,-99) , 
10, -3.25496, 0, 0, 0.508268,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0495858);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545449,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482116,-99) , 
2, 0.709765, 1, 0, 0.499569,-99) , 
10, -1.60839, 0, 0, 0.515194,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489305,-99) , 
10, -2.59105, 1, 0, 0.507095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447361,-99) , 
5, 4.8698, 1, 0, 0.498209,-99) , 
0, 0.930364, 1, 0, 0.50226,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0483327);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491524,-99) , 
2, 1.00942, 0, 0, 0.520101,-99) , 
NN(
NN(
0, 
0, 
-1, 4.45257, 0, 1, 0.513365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462436,-99) , 
7, 3.39207, 1, 0, 0.485968,-99) , 
2, 0.709765, 1, 0, 0.499222,-99) , 
6, 3.31527, 1, 0, 0.503662,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0483332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553175,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494353,-99) , 
6, 3.04911, 1, 0, 0.507763,-99) , 
6, 2.75629, 1, 0, 0.521721,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480948,-99) , 
7, 3.98619, 0, 0, 0.523642,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48021,-99) , 
11, -2.9153, 1, 0, 0.488498,-99) , 
3, 0.980524, 1, 0, 0.49467,-99) , 
6, 3.31527, 1, 0, 0.500421,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0537231);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.00942, 0, 1, 0.519313,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421404,-99) , 
11, -1.02574, 1, 0, 0.505681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469787,-99) , 
10, -1.31098, 1, 0, 0.500318,-99) , 
6, 3.31527, 1, 0, 0.504356,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0430394);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529235,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614703,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434072,-99) , 
11, -1.57904, 1, 0, 0.486782,-99) , 
3, 0.250772, 1, 0, 0.493911,-99) , 
9, -5.46717, 1, 0, 0.496709,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0635646);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486313,-99) , 
7, 3.55388, 1, 0, 0.518348,-99) , 
NN(
0, 
0, 
-1, 1.23808, 1, -1, 0.469508,-99) , 
5, 4.40397, 1, 0, 0.502015,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463184,-99) , 
10, -1.22431, 1, 0, 0.495585,-99) , 
NN(
0, 
0, 
-1, -3.96708, 0, -1, 0.457623,-99) , 
10, -2.40963, 0, 0, 0.476593,-99) , 
11, -2.28335, 0, 0, 0.489988,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0702657);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479719,-99) , 
11, -0.83769, 1, 0, 0.533414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422958,-99) , 
3, 1.93878, 1, 0, 0.489661,-99) , 
1, 2.00185, 1, 0, 0.511117,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512582,-99) , 
NN(
0, 
0, 
-1, -2.57887, 1, -1, 0.469029,-99) , 
3, 2.36519, 0, 0, 0.480614,-99) , 
11, -2.28335, 0, 0, 0.496683,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0634596);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578667,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477124,-99) , 
3, 1.67843, 1, 0, 0.489927,-99) , 
3, 0.822595, 1, 0, 0.510213,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496084,-99) , 
7, 2.97265, 1, 0, 0.559108,-99) , 
NN(
0, 
0, 
-1, -1.79504, 1, -1, 0.475054,-99) , 
9, -4.73392, 1, 0, 0.490887,-99) , 
7, 4.02256, 0, 0, 0.497171,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0338854);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528677,-99) , 
NN(
NN(
0, 
0, 
-1, 0.483234, 1, 1, 0.511358,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439654,-99) , 
1, 2.91821, 1, 0, 0.485952,-99) , 
1, 2.46459, 1, 0, 0.50381,-99) , 
1, 0.223155, 1, 0, 0.505681,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0261777);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520226,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496096,-99) , 
3, 0.483234, 1, 0, 0.502889,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448018,-99) , 
1, 2.91821, 1, 0, 0.483216,-99) , 
1, 2.46459, 1, 0, 0.497047,-99) , 
1, 0.223155, 1, 0, 0.49879,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0409706);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606009,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41505,-99) , 
7, 4.42851, 1, 0, 0.493337,-99) , 
3, 0.250772, 1, 0, 0.499578,-99) , 
9, -5.46717, 1, 0, 0.501201,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0684124);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488111,-99) , 
9, -4.41222, 1, 0, 0.519665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460251,-99) , 
7, 4.67717, 1, 0, 0.503193,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470333,-99) , 
3, 1.7778, 1, 0, 0.499413,-99) , 
NN(
0, 
0, 
-1, 3.39207, 1, -1, 0.453045,-99) , 
5, 4.84622, 1, 0, 0.488438,-99) , 
5, 3.72527, 1, 0, 0.493278,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0503903);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -4.41222, 1, 1, 0.525182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477285,-99) , 
7, 4.67717, 1, 0, 0.511906,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485934,-99) , 
9, -3.31828, 0, 0, 0.499157,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425738,-99) , 
7, 3.39207, 1, 0, 0.470045,-99) , 
5, 4.84622, 1, 0, 0.492273,-99) , 
5, 3.72527, 1, 0, 0.498712,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0441995);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524817,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592754,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442209,-99) , 
11, -1.57904, 1, 0, 0.492927,-99) , 
3, 0.250772, 1, 0, 0.498418,-99) , 
9, -5.46717, 1, 0, 0.500504,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0582619);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554962,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468144,-99) , 
5, 3.72527, 1, 0, 0.488735,-99) , 
3, 0.822595, 1, 0, 0.503575,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495297,-99) , 
7, 2.97265, 1, 0, 0.546777,-99) , 
NN(
0, 
0, 
-1, -1.79504, 1, -1, 0.475523,-99) , 
9, -4.73392, 1, 0, 0.488807,-99) , 
7, 4.02256, 0, 0, 0.493576,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0308876);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543851,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472045,-99) , 
3, 1.65255, 0, 0, 0.494665,-99) , 
6, 4.37663, 0, 0, 0.511282,-99) , 
NN(
NN(
0, 
0, 
-1, 1.6153, 0, 1, 0.51554,-99) , 
NN(
0, 
0, 
-1, 1.30655, 1, -1, 0.489544,-99) , 
6, 3.58309, 1, 0, 0.497827,-99) , 
2, 0.0994728, 1, 0, 0.500856,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0260945);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.96718, 1, 1, 0.523641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487048,-99) , 
11, -2.63555, 1, 0, 0.499477,-99) , 
10, -2.5455, 1, 0, 0.509875,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497286,-99) , 
1, 0.576645, 1, 0, 0.501687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468988,-99) , 
10, -3.25496, 0, 0, 0.497918,-99) , 
4, 4.57564, 0, 0, 0.502267,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0266903);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541072,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491148,-99) , 
6, 3.78843, 0, 0, 0.499182,-99) , 
10, -1.60839, 0, 0, 0.513433,-99) , 
NN(
NN(
0, 
0, 
-1, -3.32127, 0, 1, 0.508116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461768,-99) , 
8, -4.76039, 0, 0, 0.50242,-99) , 
0, 0.930364, 1, 0, 0.505045,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0346554);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534438,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491167,-99) , 
10, -2.8738, 0, 0, 0.497969,-99) , 
10, -1.60839, 0, 0, 0.510368,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478838,-99) , 
2, 1.2481, 1, 0, 0.503458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462318,-99) , 
5, 4.8698, 1, 0, 0.497387,-99) , 
0, 0.930364, 1, 0, 0.500481,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0465056);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477884,-99) , 
7, 3.39375, 1, 0, 0.511118,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433463,-99) , 
11, -0.859058, 1, 0, 0.500107,-99) , 
NN(
0, 
0, 
-1, 4.14346, 1, -1, 0.469464,-99) , 
2, 1.23109, 1, 0, 0.495395,-99) , 
2, 1.68375, 0, 0, 0.497965,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0443861);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489497,-99) , 
7, 3.39375, 1, 0, 0.513222,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47466,-99) , 
11, -1.17892, 1, 0, 0.500493,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471494,-99) , 
9, -3.76081, 0, 0, 0.480884,-99) , 
11, -2.14507, 0, 0, 0.490083,-99) , 
2, 1.68375, 0, 0, 0.493864,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0268219);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.39375, 1, 1, 0.515236,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489697,-99) , 
9, -4.12775, 1, 0, 0.510085,-99) , 
NN(
0, 
0, 
-1, 4.40082, 1, -1, 0.488315,-99) , 
0, 0.706141, 1, 0, 0.491677,-99) , 
2, 1.68375, 0, 0, 0.495526,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0314895);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516708,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495513,-99) , 
2, 1.69028, 0, 0, 0.503212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431229,-99) , 
2, 2.16591, 1, 0, 0.497885,-99) , 
6, 5.66294, 0, 0, 0.499186,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0627069);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520349,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421293,-99) , 
11, -0.8335, 1, 0, 0.511443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433193,-99) , 
3, 2.8844, 1, 0, 0.503491,-99) , 
9, -5.46717, 1, 0, 0.504819,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0313823);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510065,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490538,-99) , 
1, 0.836334, 1, 0, 0.496365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452579,-99) , 
5, 4.98022, 1, 0, 0.491755,-99) , 
9, -3.22402, 0, 0, 0.494856,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0307785);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48218,-99) , 
7, 4.19255, 1, 0, 0.505761,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46129,-99) , 
6, 4.09783, 1, 0, 0.482966,-99) , 
1, 2.49002, 1, 0, 0.499776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484726,-99) , 
4, 5.79348, 1, 0, 0.498776,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0260741);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495733,-99) , 
3, 1.96718, 1, 0, 0.511449,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486187,-99) , 
7, 3.91654, 0, 0, 0.496209,-99) , 
10, -2.5455, 1, 0, 0.502756,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490827,-99) , 
9, -4.92737, 1, 0, 0.495514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472067,-99) , 
10, -3.25496, 0, 0, 0.49283,-99) , 
4, 4.57564, 0, 0, 0.49644,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0216449);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531831,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474238,-99) , 
10, -2.86233, 1, 0, 0.494061,-99) , 
6, 4.37663, 0, 0, 0.506811,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52913,-99) , 
NN(
0, 
0, 
-1, 4.67712, 1, -1, 0.494537,-99) , 
6, 2.81728, 1, 0, 0.497332,-99) , 
2, 0.0994728, 1, 0, 0.499466,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0374742);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485854,-99) , 
10, -2.12459, 1, 0, 0.513468,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478306,-99) , 
0, 1.44895, 1, 0, 0.494884,-99) , 
8, -4.05451, 0, 0, 0.503462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489174,-99) , 
8, -2.7347, 1, 0, 0.502514,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0206028);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526964,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48958,-99) , 
5, 3.77816, 0, 0, 0.505832,-99) , 
8, -2.9316, 0, 0, 0.509087,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497616,-99) , 
1, 0.576645, 1, 0, 0.500353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470916,-99) , 
10, -3.25496, 0, 0, 0.496988,-99) , 
4, 4.57564, 0, 0, 0.501388,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0210306);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492908,-99) , 
10, -1.83326, 0, 0, 0.524041,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496774,-99) , 
3, 0.525905, 1, 0, 0.501712,-99) , 
0, 0.542902, 1, 0, 0.504781,-99) , 
NN(
0, 
0, 
-1, 0.930364, 0, -1, 0.490905,-99) , 
10, -3.25496, 0, 0, 0.503318,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.020538);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.37202, 0, 1, 0.510573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487758,-99) , 
9, -2.59424, 1, 0, 0.508408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489586,-99) , 
0, 0.930364, 0, 0, 0.496162,-99) , 
10, -3.25496, 0, 0, 0.507117,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.032149);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511932,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491391,-99) , 
7, 3.66983, 1, 0, 0.505957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464698,-99) , 
5, 4.98022, 1, 0, 0.50164,-99) , 
9, -3.22402, 0, 0, 0.503384,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0498843);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565588,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481615,-99) , 
0, 1.75793, 0, 0, 0.496228,-99) , 
3, 0.822595, 1, 0, 0.511742,-99) , 
NN(
NN(
0, 
0, 
-1, -2.46142, 1, 1, 0.542241,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423587,-99) , 
11, -1.79504, 1, 0, 0.488663,-99) , 
9, -4.73392, 1, 0, 0.498615,-99) , 
7, 4.02256, 0, 0, 0.502859,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0407582);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483805,-99) , 
6, 3.66604, 0, 0, 0.497381,-99) , 
3, 0.822595, 1, 0, 0.509863,-99) , 
NN(
NN(
0, 
0, 
-1, -2.46142, 1, 1, 0.529836,-99) , 
NN(
0, 
0, 
-1, -1.79504, 1, -1, 0.481217,-99) , 
9, -4.73392, 1, 0, 0.490239,-99) , 
7, 4.02256, 0, 0, 0.496583,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0390047);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479051,-99) , 
4, 4.61909, 1, 0, 0.494908,-99) , 
3, 0.822595, 1, 0, 0.505674,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493191,-99) , 
9, -5.05179, 1, 0, 0.505809,-99) , 
NN(
0, 
0, 
-1, -2.41748, 1, -1, 0.472607,-99) , 
7, 3.67266, 1, 0, 0.496643,-99) , 
7, 4.02256, 0, 0, 0.499563,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0474402);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495255,-99) , 
11, -2.64264, 1, 0, 0.511704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473364,-99) , 
3, 2.87741, 1, 0, 0.505919,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449366,-99) , 
5, 3.82384, 0, 0, 0.511692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477484,-99) , 
9, -4.21577, 0, 0, 0.496594,-99) , 
3, 1.20185, 0, 0, 0.503708,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0698153);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486813,-99) , 
10, -2.04217, 1, 0, 0.521579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483637,-99) , 
7, 4.42308, 1, 0, 0.512186,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480511,-99) , 
1, 2.58408, 1, 0, 0.5292,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464191,-99) , 
5, 4.58242, 0, 0, 0.493667,-99) , 
1, 2.38017, 0, 0, 0.503493,-99) , 
11, -2.28335, 0, 0, 0.508029,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0426441);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487088,-99) , 
11, -2.31591, 0, 0, 0.526806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488502,-99) , 
9, -3.67083, 1, 0, 0.518572,-99) , 
NN(
NN(
0, 
0, 
-1, -3.31828, 0, 1, 0.511806,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449676,-99) , 
7, 3.39207, 1, 0, 0.48607,-99) , 
5, 4.84622, 1, 0, 0.505753,-99) , 
5, 3.72527, 1, 0, 0.509986,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0416514);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.09601, 1, 1, 0.527554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494691,-99) , 
7, 4.67717, 1, 0, 0.518421,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487648,-99) , 
6, 4.42347, 1, 0, 0.504444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462354,-99) , 
11, -2.54817, 1, 0, 0.486933,-99) , 
4, 3.95342, 0, 0, 0.49741,-99) , 
5, 3.72527, 1, 0, 0.504346,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0360129);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477556,-99) , 
8, -4.19406, 0, 0, 0.503544,-99) , 
6, 4.44247, 0, 0, 0.513809,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479695,-99) , 
8, -3.77639, 1, 0, 0.503265,-99) , 
NN(
0, 
0, 
-1, 2.49002, 1, -1, 0.487976,-99) , 
0, 1.75972, 1, 0, 0.496416,-99) , 
5, 3.72527, 1, 0, 0.502157,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0178426);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535737,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498929,-99) , 
2, 0.424049, 1, 0, 0.504855,-99) , 
8, -2.9316, 0, 0, 0.509602,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49759,-99) , 
4, 2.91099, 1, 0, 0.501205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473371,-99) , 
10, -3.25496, 0, 0, 0.498036,-99) , 
4, 4.57564, 0, 0, 0.502241,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0325833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481115,-99) , 
5, 3.3454, 1, 0, 0.517843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488628,-99) , 
9, -3.67083, 1, 0, 0.511552,-99) , 
NN(
NN(
0, 
0, 
-1, -2.28335, 1, 1, 0.515589,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490501,-99) , 
4, 4.1918, 0, 0, 0.496777,-99) , 
4, 4.95474, 0, 0, 0.501504,-99) , 
5, 3.72527, 1, 0, 0.50482,-99)    );
   return;
};

// Clean up
inline void ReadBDTD::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDTD::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadBDTD::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 9.54682438481;
   fDecTF_1[0][0][1] = -0.132838199374;
   fDecTF_1[0][0][2] = -4.87373468024;
   fDecTF_1[0][0][3] = 0.0348922032029;
   fDecTF_1[0][0][4] = 1.08900429569;
   fDecTF_1[0][0][5] = -0.0267825562252;
   fDecTF_1[0][0][6] = -0.429567174243;
   fDecTF_1[0][0][7] = -0.0255874473482;
   fDecTF_1[0][0][8] = -8.47459455016;
   fDecTF_1[0][0][9] = 0.137236349897;
   fDecTF_1[0][0][10] = 4.43292612732;
   fDecTF_1[0][0][11] = -0.0265835202215;
   fDecTF_1[0][1][0] = -0.132838199374;
   fDecTF_1[0][1][1] = 7.117682064;
   fDecTF_1[0][1][2] = 0.00880730464017;
   fDecTF_1[0][1][3] = -3.9996541007;
   fDecTF_1[0][1][4] = -0.0104287275435;
   fDecTF_1[0][1][5] = 1.04147560116;
   fDecTF_1[0][1][6] = -0.0144707689857;
   fDecTF_1[0][1][7] = -0.321557184528;
   fDecTF_1[0][1][8] = 0.10548552038;
   fDecTF_1[0][1][9] = -5.46615293704;
   fDecTF_1[0][1][10] = 0.0204126229467;
   fDecTF_1[0][1][11] = 2.94925358887;
   fDecTF_1[0][2][0] = -4.87373468024;
   fDecTF_1[0][2][1] = 0.00880730464018;
   fDecTF_1[0][2][2] = 9.02730816686;
   fDecTF_1[0][2][3] = -0.151811755385;
   fDecTF_1[0][2][4] = 0.087024265957;
   fDecTF_1[0][2][5] = -0.0354975836888;
   fDecTF_1[0][2][6] = 0.6775243144;
   fDecTF_1[0][2][7] = -0.0322993331689;
   fDecTF_1[0][2][8] = 4.23198936098;
   fDecTF_1[0][2][9] = 0.0229644611721;
   fDecTF_1[0][2][10] = -7.54315826834;
   fDecTF_1[0][2][11] = 0.141066386718;
   fDecTF_1[0][3][0] = 0.0348922032029;
   fDecTF_1[0][3][1] = -3.9996541007;
   fDecTF_1[0][3][2] = -0.151811755385;
   fDecTF_1[0][3][3] = 7.24708430851;
   fDecTF_1[0][3][4] = -0.0309373746472;
   fDecTF_1[0][3][5] = -0.224843860989;
   fDecTF_1[0][3][6] = -0.0175993514601;
   fDecTF_1[0][3][7] = 0.414936826169;
   fDecTF_1[0][3][8] = 0.0020332693685;
   fDecTF_1[0][3][9] = 2.69009940949;
   fDecTF_1[0][3][10] = 0.12914740673;
   fDecTF_1[0][3][11] = -4.68343700689;
   fDecTF_1[0][4][0] = 1.08900429569;
   fDecTF_1[0][4][1] = -0.0104287275435;
   fDecTF_1[0][4][2] = 0.087024265957;
   fDecTF_1[0][4][3] = -0.0309373746472;
   fDecTF_1[0][4][4] = 4.15573927069;
   fDecTF_1[0][4][5] = -0.132772560136;
   fDecTF_1[0][4][6] = -1.43286796363;
   fDecTF_1[0][4][7] = 0.0149954965592;
   fDecTF_1[0][4][8] = -2.72873951471;
   fDecTF_1[0][4][9] = 0.0293768298911;
   fDecTF_1[0][4][10] = 0.144824050951;
   fDecTF_1[0][4][11] = 0.0585484622963;
   fDecTF_1[0][5][0] = -0.0267825562252;
   fDecTF_1[0][5][1] = 1.04147560116;
   fDecTF_1[0][5][2] = -0.0354975836888;
   fDecTF_1[0][5][3] = -0.224843860989;
   fDecTF_1[0][5][4] = -0.132772560136;
   fDecTF_1[0][5][5] = 4.51748674176;
   fDecTF_1[0][5][6] = 0.0307634963299;
   fDecTF_1[0][5][7] = -1.5240649188;
   fDecTF_1[0][5][8] = 0.0592983092236;
   fDecTF_1[0][5][9] = -2.81473195655;
   fDecTF_1[0][5][10] = 0.054546238219;
   fDecTF_1[0][5][11] = 0.420940074972;
   fDecTF_1[0][6][0] = -0.429567174243;
   fDecTF_1[0][6][1] = -0.0144707689857;
   fDecTF_1[0][6][2] = 0.6775243144;
   fDecTF_1[0][6][3] = -0.0175993514601;
   fDecTF_1[0][6][4] = -1.43286796363;
   fDecTF_1[0][6][5] = 0.0307634963299;
   fDecTF_1[0][6][6] = 4.04929341626;
   fDecTF_1[0][6][7] = -0.142212870512;
   fDecTF_1[0][6][8] = 0.437151389703;
   fDecTF_1[0][6][9] = 0.0300183565849;
   fDecTF_1[0][6][10] = -2.32958862958;
   fDecTF_1[0][6][11] = 0.0572045236624;
   fDecTF_1[0][7][0] = -0.0255874473482;
   fDecTF_1[0][7][1] = -0.321557184528;
   fDecTF_1[0][7][2] = -0.0322993331689;
   fDecTF_1[0][7][3] = 0.414936826169;
   fDecTF_1[0][7][4] = 0.0149954965592;
   fDecTF_1[0][7][5] = -1.5240649188;
   fDecTF_1[0][7][6] = -0.142212870512;
   fDecTF_1[0][7][7] = 4.13526782672;
   fDecTF_1[0][7][8] = 0.023583596923;
   fDecTF_1[0][7][9] = 0.211819460221;
   fDecTF_1[0][7][10] = 0.0864198364572;
   fDecTF_1[0][7][11] = -1.86196396135;
   fDecTF_1[0][8][0] = -8.47459455016;
   fDecTF_1[0][8][1] = 0.10548552038;
   fDecTF_1[0][8][2] = 4.23198936098;
   fDecTF_1[0][8][3] = 0.00203326936849;
   fDecTF_1[0][8][4] = -2.72873951471;
   fDecTF_1[0][8][5] = 0.0592983092236;
   fDecTF_1[0][8][6] = 0.437151389703;
   fDecTF_1[0][8][7] = 0.023583596923;
   fDecTF_1[0][8][8] = 10.5335678754;
   fDecTF_1[0][8][9] = -0.185570038076;
   fDecTF_1[0][8][10] = -5.00627659857;
   fDecTF_1[0][8][11] = 0.0398139258823;
   fDecTF_1[0][9][0] = 0.137236349897;
   fDecTF_1[0][9][1] = -5.46615293704;
   fDecTF_1[0][9][2] = 0.0229644611721;
   fDecTF_1[0][9][3] = 2.69009940949;
   fDecTF_1[0][9][4] = 0.0293768298911;
   fDecTF_1[0][9][5] = -2.81473195655;
   fDecTF_1[0][9][6] = 0.0300183565849;
   fDecTF_1[0][9][7] = 0.211819460221;
   fDecTF_1[0][9][8] = -0.185570038076;
   fDecTF_1[0][9][9] = 7.0219876017;
   fDecTF_1[0][9][10] = -0.0213189540824;
   fDecTF_1[0][9][11] = -2.86387684924;
   fDecTF_1[0][10][0] = 4.43292612732;
   fDecTF_1[0][10][1] = 0.0204126229467;
   fDecTF_1[0][10][2] = -7.54315826834;
   fDecTF_1[0][10][3] = 0.12914740673;
   fDecTF_1[0][10][4] = 0.144824050951;
   fDecTF_1[0][10][5] = 0.054546238219;
   fDecTF_1[0][10][6] = -2.32958862958;
   fDecTF_1[0][10][7] = 0.0864198364572;
   fDecTF_1[0][10][8] = -5.00627659857;
   fDecTF_1[0][10][9] = -0.0213189540824;
   fDecTF_1[0][10][10] = 9.72583162927;
   fDecTF_1[0][10][11] = -0.272822807742;
   fDecTF_1[0][11][0] = -0.0265835202215;
   fDecTF_1[0][11][1] = 2.94925358887;
   fDecTF_1[0][11][2] = 0.141066386718;
   fDecTF_1[0][11][3] = -4.68343700689;
   fDecTF_1[0][11][4] = 0.0585484622964;
   fDecTF_1[0][11][5] = 0.420940074972;
   fDecTF_1[0][11][6] = 0.0572045236624;
   fDecTF_1[0][11][7] = -1.86196396135;
   fDecTF_1[0][11][8] = 0.0398139258823;
   fDecTF_1[0][11][9] = -2.86387684924;
   fDecTF_1[0][11][10] = -0.272822807742;
   fDecTF_1[0][11][11] = 5.69355104428;
   fDecTF_1[1][0][0] = 5.59855553973;
   fDecTF_1[1][0][1] = -0.194556683213;
   fDecTF_1[1][0][2] = -1.35919802075;
   fDecTF_1[1][0][3] = 0.0370811684779;
   fDecTF_1[1][0][4] = 0.511780367948;
   fDecTF_1[1][0][5] = -0.120828349574;
   fDecTF_1[1][0][6] = 0.0680332529469;
   fDecTF_1[1][0][7] = 0.102534791002;
   fDecTF_1[1][0][8] = -4.49359856721;
   fDecTF_1[1][0][9] = 0.179750497391;
   fDecTF_1[1][0][10] = 1.0152193191;
   fDecTF_1[1][0][11] = -0.00981623413032;
   fDecTF_1[1][1][0] = -0.194556683213;
   fDecTF_1[1][1][1] = 4.265091342;
   fDecTF_1[1][1][2] = 0.0223592691814;
   fDecTF_1[1][1][3] = -1.65249838804;
   fDecTF_1[1][1][4] = 0.0266989752835;
   fDecTF_1[1][1][5] = 0.354531676641;
   fDecTF_1[1][1][6] = -0.0949151074119;
   fDecTF_1[1][1][7] = -0.369662212887;
   fDecTF_1[1][1][8] = 0.136566645263;
   fDecTF_1[1][1][9] = -2.8071554409;
   fDecTF_1[1][1][10] = -0.0134775200271;
   fDecTF_1[1][1][11] = 1.73576706824;
   fDecTF_1[1][2][0] = -1.35919802075;
   fDecTF_1[1][2][1] = 0.0223592691814;
   fDecTF_1[1][2][2] = 4.45664910942;
   fDecTF_1[1][2][3] = -0.0994258200266;
   fDecTF_1[1][2][4] = 0.360220518007;
   fDecTF_1[1][2][5] = -0.0646545305466;
   fDecTF_1[1][2][6] = -0.314034998162;
   fDecTF_1[1][2][7] = -0.134085923707;
   fDecTF_1[1][2][8] = 1.01453897724;
   fDecTF_1[1][2][9] = 0.0362206807965;
   fDecTF_1[1][2][10] = -2.89909494547;
   fDecTF_1[1][2][11] = 0.105341825639;
   fDecTF_1[1][3][0] = 0.0370811684779;
   fDecTF_1[1][3][1] = -1.65249838804;
   fDecTF_1[1][3][2] = -0.0994258200266;
   fDecTF_1[1][3][3] = 6.32001767537;
   fDecTF_1[1][3][4] = -0.0154986713453;
   fDecTF_1[1][3][5] = -0.351557297023;
   fDecTF_1[1][3][6] = 0.157750314773;
   fDecTF_1[1][3][7] = 0.345364364818;
   fDecTF_1[1][3][8] = 0.038595729402;
   fDecTF_1[1][3][9] = 1.36232461331;
   fDecTF_1[1][3][10] = -0.119772060344;
   fDecTF_1[1][3][11] = -3.24480036924;
   fDecTF_1[1][4][0] = 0.511780367948;
   fDecTF_1[1][4][1] = 0.0266989752835;
   fDecTF_1[1][4][2] = 0.360220518007;
   fDecTF_1[1][4][3] = -0.0154986713453;
   fDecTF_1[1][4][4] = 3.26577545289;
   fDecTF_1[1][4][5] = -0.126517978478;
   fDecTF_1[1][4][6] = -0.577465483496;
   fDecTF_1[1][4][7] = 0.0469512095675;
   fDecTF_1[1][4][8] = -2.12730814801;
   fDecTF_1[1][4][9] = 0.0166317775095;
   fDecTF_1[1][4][10] = -0.21336264522;
   fDecTF_1[1][4][11] = 0.0355346720008;
   fDecTF_1[1][5][0] = -0.120828349574;
   fDecTF_1[1][5][1] = 0.354531676641;
   fDecTF_1[1][5][2] = -0.0646545305466;
   fDecTF_1[1][5][3] = -0.351557297023;
   fDecTF_1[1][5][4] = -0.126517978478;
   fDecTF_1[1][5][5] = 2.40379183467;
   fDecTF_1[1][5][6] = 0.0509506071857;
   fDecTF_1[1][5][7] = -1.13648964786;
   fDecTF_1[1][5][8] = 0.171870467213;
   fDecTF_1[1][5][9] = -1.55820098598;
   fDecTF_1[1][5][10] = 0.0624681366005;
   fDecTF_1[1][5][11] = 0.46235310288;
   fDecTF_1[1][6][0] = 0.0680332529469;
   fDecTF_1[1][6][1] = -0.0949151074119;
   fDecTF_1[1][6][2] = -0.314034998162;
   fDecTF_1[1][6][3] = 0.157750314773;
   fDecTF_1[1][6][4] = -0.577465483496;
   fDecTF_1[1][6][5] = 0.0509506071857;
   fDecTF_1[1][6][6] = 2.72052005545;
   fDecTF_1[1][6][7] = -0.171177301448;
   fDecTF_1[1][6][8] = -0.138538720199;
   fDecTF_1[1][6][9] = 0.0404593941275;
   fDecTF_1[1][6][10] = -1.12978001279;
   fDecTF_1[1][6][11] = -0.0287314066535;
   fDecTF_1[1][7][0] = 0.102534791002;
   fDecTF_1[1][7][1] = -0.369662212887;
   fDecTF_1[1][7][2] = -0.134085923707;
   fDecTF_1[1][7][3] = 0.345364364818;
   fDecTF_1[1][7][4] = 0.0469512095675;
   fDecTF_1[1][7][5] = -1.13648964786;
   fDecTF_1[1][7][6] = -0.171177301448;
   fDecTF_1[1][7][7] = 2.29307541166;
   fDecTF_1[1][7][8] = -0.108540100029;
   fDecTF_1[1][7][9] = 0.779096444766;
   fDecTF_1[1][7][10] = 0.272078900094;
   fDecTF_1[1][7][11] = -1.37321961089;
   fDecTF_1[1][8][0] = -4.49359856721;
   fDecTF_1[1][8][1] = 0.136566645263;
   fDecTF_1[1][8][2] = 1.01453897724;
   fDecTF_1[1][8][3] = 0.038595729402;
   fDecTF_1[1][8][4] = -2.12730814801;
   fDecTF_1[1][8][5] = 0.171870467213;
   fDecTF_1[1][8][6] = -0.138538720199;
   fDecTF_1[1][8][7] = -0.108540100029;
   fDecTF_1[1][8][8] = 6.17433889193;
   fDecTF_1[1][8][9] = -0.292989992811;
   fDecTF_1[1][8][10] = -1.29077424593;
   fDecTF_1[1][8][11] = 0.015440229705;
   fDecTF_1[1][9][0] = 0.179750497391;
   fDecTF_1[1][9][1] = -2.8071554409;
   fDecTF_1[1][9][2] = 0.0362206807965;
   fDecTF_1[1][9][3] = 1.36232461331;
   fDecTF_1[1][9][4] = 0.0166317775095;
   fDecTF_1[1][9][5] = -1.55820098598;
   fDecTF_1[1][9][6] = 0.0404593941275;
   fDecTF_1[1][9][7] = 0.779096444766;
   fDecTF_1[1][9][8] = -0.292989992811;
   fDecTF_1[1][9][9] = 3.74968540878;
   fDecTF_1[1][9][10] = 0.00955018338899;
   fDecTF_1[1][9][11] = -2.19409817685;
   fDecTF_1[1][10][0] = 1.0152193191;
   fDecTF_1[1][10][1] = -0.0134775200271;
   fDecTF_1[1][10][2] = -2.89909494547;
   fDecTF_1[1][10][3] = -0.119772060344;
   fDecTF_1[1][10][4] = -0.21336264522;
   fDecTF_1[1][10][5] = 0.0624681366005;
   fDecTF_1[1][10][6] = -1.12978001279;
   fDecTF_1[1][10][7] = 0.272078900094;
   fDecTF_1[1][10][8] = -1.29077424593;
   fDecTF_1[1][10][9] = 0.00955018338899;
   fDecTF_1[1][10][10] = 4.30175848778;
   fDecTF_1[1][10][11] = -0.129757659361;
   fDecTF_1[1][11][0] = -0.00981623413032;
   fDecTF_1[1][11][1] = 1.73576706824;
   fDecTF_1[1][11][2] = 0.105341825639;
   fDecTF_1[1][11][3] = -3.24480036924;
   fDecTF_1[1][11][4] = 0.0355346720008;
   fDecTF_1[1][11][5] = 0.46235310288;
   fDecTF_1[1][11][6] = -0.0287314066535;
   fDecTF_1[1][11][7] = -1.37321961089;
   fDecTF_1[1][11][8] = 0.015440229705;
   fDecTF_1[1][11][9] = -2.19409817685;
   fDecTF_1[1][11][10] = -0.129757659361;
   fDecTF_1[1][11][11] = 4.30991060656;
   fDecTF_1[2][0][0] = 7.60299063374;
   fDecTF_1[2][0][1] = -0.179193237028;
   fDecTF_1[2][0][2] = -2.95626177299;
   fDecTF_1[2][0][3] = -0.0334155546492;
   fDecTF_1[2][0][4] = 0.806237706787;
   fDecTF_1[2][0][5] = -0.0307202409155;
   fDecTF_1[2][0][6] = -0.0678150166427;
   fDecTF_1[2][0][7] = 0.0545304545437;
   fDecTF_1[2][0][8] = -6.49484602471;
   fDecTF_1[2][0][9] = 0.155723854415;
   fDecTF_1[2][0][10] = 2.45312480766;
   fDecTF_1[2][0][11] = 0.00954543583733;
   fDecTF_1[2][1][0] = -0.179193237028;
   fDecTF_1[2][1][1] = 5.70494561753;
   fDecTF_1[2][1][2] = 0.0620872946188;
   fDecTF_1[2][1][3] = -3.28686146894;
   fDecTF_1[2][1][4] = -0.00362360352611;
   fDecTF_1[2][1][5] = 0.814888962593;
   fDecTF_1[2][1][6] = -0.0409828894391;
   fDecTF_1[2][1][7] = -0.470419327341;
   fDecTF_1[2][1][8] = 0.140537612196;
   fDecTF_1[2][1][9] = -4.1498677333;
   fDecTF_1[2][1][10] = -0.018009543831;
   fDecTF_1[2][1][11] = 2.55897386782;
   fDecTF_1[2][2][0] = -2.95626177299;
   fDecTF_1[2][2][1] = 0.0620872946188;
   fDecTF_1[2][2][2] = 6.64490757323;
   fDecTF_1[2][2][3] = -0.0904282552458;
   fDecTF_1[2][2][4] = 0.337210231258;
   fDecTF_1[2][2][5] = -0.11168548645;
   fDecTF_1[2][2][6] = 0.116593267598;
   fDecTF_1[2][2][7] = -0.144951759589;
   fDecTF_1[2][2][8] = 2.3686964383;
   fDecTF_1[2][2][9] = 0.0512866653866;
   fDecTF_1[2][2][10] = -5.08117099033;
   fDecTF_1[2][2][11] = 0.0657664071916;
   fDecTF_1[2][3][0] = -0.0334155546492;
   fDecTF_1[2][3][1] = -3.28686146894;
   fDecTF_1[2][3][2] = -0.0904282552458;
   fDecTF_1[2][3][3] = 6.39230430551;
   fDecTF_1[2][3][4] = -0.044810274236;
   fDecTF_1[2][3][5] = -0.0707128468605;
   fDecTF_1[2][3][6] = 0.056082276701;
   fDecTF_1[2][3][7] = 0.300823307047;
   fDecTF_1[2][3][8] = 0.137638998204;
   fDecTF_1[2][3][9] = 2.22694250118;
   fDecTF_1[2][3][10] = -0.0745137679256;
   fDecTF_1[2][3][11] = -4.12263629813;
   fDecTF_1[2][4][0] = 0.806237706787;
   fDecTF_1[2][4][1] = -0.00362360352611;
   fDecTF_1[2][4][2] = 0.337210231258;
   fDecTF_1[2][4][3] = -0.044810274236;
   fDecTF_1[2][4][4] = 3.83558803042;
   fDecTF_1[2][4][5] = -0.127022739956;
   fDecTF_1[2][4][6] = -1.09086658699;
   fDecTF_1[2][4][7] = 0.0399545689907;
   fDecTF_1[2][4][8] = -2.45670273401;
   fDecTF_1[2][4][9] = 0.01532920749;
   fDecTF_1[2][4][10] = -0.107138383065;
   fDecTF_1[2][4][11] = 0.0832570581953;
   fDecTF_1[2][5][0] = -0.0307202409155;
   fDecTF_1[2][5][1] = 0.814888962593;
   fDecTF_1[2][5][2] = -0.11168548645;
   fDecTF_1[2][5][3] = -0.0707128468605;
   fDecTF_1[2][5][4] = -0.127022739956;
   fDecTF_1[2][5][5] = 3.47159195766;
   fDecTF_1[2][5][6] = 0.0204981783375;
   fDecTF_1[2][5][7] = -1.38032763018;
   fDecTF_1[2][5][8] = 0.0421010188998;
   fDecTF_1[2][5][9] = -2.27265828519;
   fDecTF_1[2][5][10] = 0.161348994213;
   fDecTF_1[2][5][11] = 0.404436650117;
   fDecTF_1[2][6][0] = -0.0678150166427;
   fDecTF_1[2][6][1] = -0.0409828894391;
   fDecTF_1[2][6][2] = 0.116593267598;
   fDecTF_1[2][6][3] = 0.056082276701;
   fDecTF_1[2][6][4] = -1.09086658699;
   fDecTF_1[2][6][5] = 0.0204981783375;
   fDecTF_1[2][6][6] = 3.52698605359;
   fDecTF_1[2][6][7] = -0.172808542985;
   fDecTF_1[2][6][8] = 0.0762752485938;
   fDecTF_1[2][6][9] = 0.0486287130912;
   fDecTF_1[2][6][10] = -1.71618856166;
   fDecTF_1[2][6][11] = -0.00695423949048;
   fDecTF_1[2][7][0] = 0.0545304545437;
   fDecTF_1[2][7][1] = -0.470419327341;
   fDecTF_1[2][7][2] = -0.144951759589;
   fDecTF_1[2][7][3] = 0.300823307047;
   fDecTF_1[2][7][4] = 0.0399545689907;
   fDecTF_1[2][7][5] = -1.38032763018;
   fDecTF_1[2][7][6] = -0.172808542985;
   fDecTF_1[2][7][7] = 3.25121654369;
   fDecTF_1[2][7][8] = -0.0394571501911;
   fDecTF_1[2][7][9] = 0.611058382642;
   fDecTF_1[2][7][10] = 0.195954259148;
   fDecTF_1[2][7][11] = -1.6425996067;
   fDecTF_1[2][8][0] = -6.49484602471;
   fDecTF_1[2][8][1] = 0.140537612196;
   fDecTF_1[2][8][2] = 2.3686964383;
   fDecTF_1[2][8][3] = 0.137638998204;
   fDecTF_1[2][8][4] = -2.45670273401;
   fDecTF_1[2][8][5] = 0.0421010188998;
   fDecTF_1[2][8][6] = 0.0762752485938;
   fDecTF_1[2][8][7] = -0.0394571501911;
   fDecTF_1[2][8][8] = 8.39091838576;
   fDecTF_1[2][8][9] = -0.228700407466;
   fDecTF_1[2][8][10] = -2.88237213108;
   fDecTF_1[2][8][11] = 0.0174498048654;
   fDecTF_1[2][9][0] = 0.155723854415;
   fDecTF_1[2][9][1] = -4.1498677333;
   fDecTF_1[2][9][2] = 0.0512866653866;
   fDecTF_1[2][9][3] = 2.22694250118;
   fDecTF_1[2][9][4] = 0.01532920749;
   fDecTF_1[2][9][5] = -2.27265828519;
   fDecTF_1[2][9][6] = 0.0486287130912;
   fDecTF_1[2][9][7] = 0.611058382642;
   fDecTF_1[2][9][8] = -0.228700407466;
   fDecTF_1[2][9][9] = 5.4186571768;
   fDecTF_1[2][9][10] = -0.0378172615548;
   fDecTF_1[2][9][11] = -2.66041474522;
   fDecTF_1[2][10][0] = 2.45312480766;
   fDecTF_1[2][10][1] = -0.018009543831;
   fDecTF_1[2][10][2] = -5.08117099033;
   fDecTF_1[2][10][3] = -0.0745137679256;
   fDecTF_1[2][10][4] = -0.107138383065;
   fDecTF_1[2][10][5] = 0.161348994213;
   fDecTF_1[2][10][6] = -1.71618856166;
   fDecTF_1[2][10][7] = 0.195954259148;
   fDecTF_1[2][10][8] = -2.88237213108;
   fDecTF_1[2][10][9] = -0.0378172615548;
   fDecTF_1[2][10][10] = 6.90331543843;
   fDecTF_1[2][10][11] = -0.218106457742;
   fDecTF_1[2][11][0] = 0.00954543583733;
   fDecTF_1[2][11][1] = 2.55897386782;
   fDecTF_1[2][11][2] = 0.0657664071916;
   fDecTF_1[2][11][3] = -4.12263629813;
   fDecTF_1[2][11][4] = 0.0832570581953;
   fDecTF_1[2][11][5] = 0.404436650117;
   fDecTF_1[2][11][6] = -0.00695423949048;
   fDecTF_1[2][11][7] = -1.6425996067;
   fDecTF_1[2][11][8] = 0.0174498048654;
   fDecTF_1[2][11][9] = -2.66041474522;
   fDecTF_1[2][11][10] = -0.218106457742;
   fDecTF_1[2][11][11] = 5.06450337529;
}

//_______________________________________________________________________
inline void ReadBDTD::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   }

   std::vector<double> tv;
   for (int i=0; i<12;i++) {
      double v = 0;
      for (int j=0; j<12; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<12;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadBDTD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadBDTD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
