[PROJECT]
PROJPATH     =  mdst
PROJVERSION  =  19Nov03
PROJTITLE    =  ISS_PART06
PROJBIN      =  mdst
PROJFLIST    =  flist.cern.iss.B1130.pass7
EVENTTYPE    =  ISS
FILEPEREXE   =  1
JOBREGION    =  PART
EXESATID     =  160000
EXEENDID     =  165774

[QUEUE]
QUEUE      =  tomorrow
STORAGE    =  EOS
EXEPERJOB  =  8
CONFIRM    =  NONE
