[PROJECT]
PROJPATH     =  mdst
PROJVERSION  =  20Jul08
PROJTITLE    =  ISS_PART04
PROJBIN      =  mdst
PROJFLIST    =  flist.cern.iss.B1130.pass7
EVENTTYPE    =  ISS
FILEPEREXE   =  2
JOBREGION    =  PART
EXESATID     =  30000
EXEENDID     =  39999

[QUEUE]
QUEUE      =  tomorrow
STORAGE    =  EOS
EXEPERJOB  =  5
CONFIRM    =  NONE
