[PROJECT]
PROJPATH     =  mdst
PROJVERSION  =  20Jan15
PROJTITLE    =  ISS_PART06
PROJBIN      =  mdst
PROJFLIST    =  flist.cern.iss.B1130.pass7
EVENTTYPE    =  ISS
FILEPEREXE   =  1
JOBREGION    =  PART
EXESATID     =  125000
EXEENDID     =  149999

[QUEUE]
QUEUE      =  tomorrow
STORAGE    =  EOS
EXEPERJOB  =  6
CONFIRM    =  NONE
