// Class: ReadBDTD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTD
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : hchou
Date           : Wed Apr  8 12:18:13 2020
Host           : Linux lcgapp-centos7-x86-64-25.cern.ch 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/h/hchou/AMSProject/apflux
Training events: 250000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
lxin                          lxin                          lxin                          lxin                          units                             'F'    [-16.24376297,3.09532809258]
lyin                          lyin                          lyin                          lyin                          units                             'F'    [-12.2133512497,5.53393983841]
lxex                          lxex                          lxex                          lxex                          units                             'F'    [-7.09427499771,3.06820940971]
lyex                          lyex                          lyex                          lyex                          units                             'F'    [-6.9883980751,5.2984919548]
nlxin                         nlxin                         nlxin                         nlxin                         units                             'F'    [0.000241763569647,6.57443094254]
nlyin                         nlyin                         nlyin                         nlyin                         units                             'F'    [0.0017457959475,20.5189094543]
nlxex                         nlxex                         nlxex                         nlxex                         units                             'F'    [0.0362178459764,7.73935699463]
nlyex                         nlyex                         nlyex                         nlyex                         units                             'F'    [0.035787127912,26.1129932404]
lxinC                         lxinC                         lxinC                         lxinC                         units                             'F'    [-16.5309410095,5.01919078827]
lyinC                         lyinC                         lyinC                         lyinC                         units                             'F'    [-12.4249925613,8.87220668793]
lxexC                         lxexC                         lxexC                         lxexC                         units                             'F'    [-7.12931919098,4.61731719971]
lyexC                         lyexC                         lyexC                         lyexC                         units                             'F'    [-7.76819849014,8.1995344162]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTDNode

#ifndef BDTDNode__def
#define BDTDNode__def

class BDTDNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTDNode ( BDTDNode* left,BDTDNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTDNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTDNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTDNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTDNode*   fLeft;     // pointer to the left daughter node
   BDTDNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTDNode::~BDTDNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTDNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTDNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTD : public IClassifierReader {

 public:

   // constructor
   ReadBDTD( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDTD" ),
        fNvars( 12 )
   {
      // the training input variables
      const char* inputVars[] = { "lxin", "lyin", "lxex", "lyex", "nlxin", "nlyin", "nlxex", "nlyex", "lxinC", "lyinC", "lxexC", "lyexC" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -43.9137916564941;
      fVmax[0] = 15.8578300476074;
      fVmin[1] = -28.7515335083008;
      fVmax[1] = 11.0306301116943;
      fVmin[2] = -11.9315128326416;
      fVmax[2] = 37.6144409179688;
      fVmin[3] = -16.4127407073975;
      fVmax[3] = 19.4781188964844;
      fVmin[4] = -7.74320459365845;
      fVmax[4] = 24.4239711761475;
      fVmin[5] = -19.7945957183838;
      fVmax[5] = 29.2108726501465;
      fVmin[6] = 0.199435025453568;
      fVmax[6] = 18.1161289215088;
      fVmin[7] = -1.93302512168884;
      fVmax[7] = 58.7880973815918;
      fVmin[8] = -42.8429679870605;
      fVmax[8] = 32.3115997314453;
      fVmin[9] = -21.1144905090332;
      fVmax[9] = 20.640022277832;
      fVmin[10] = -38.3761291503906;
      fVmax[10] = 12.7234802246094;
      fVmin[11] = -39.2615966796875;
      fVmax[11] = 13.2843294143677;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadBDTD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][12][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTDNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTD::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTDNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTDNode*)current->GetRight();
         else current=(BDTDNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDTD::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.58645331264491);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.38243, 1, 1, 0.847417,-99) , 
NN(
0, 
0, 
-1, -2.00622, 1, -1, 0.292487,-99) , 
11, -2.77076, 1, 0, 0.634777,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.158543,-99) , 
11, -2.91422, 1, 0, 0.38611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.152445,-99) , 
3, 3.20109, 1, 0, 0.311815,-99) , 
3, 2.38723, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.412674);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.4844, 1, 1, 0.699621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27964,-99) , 
11, -1.70042, 1, 0, 0.621893,-99) , 
NN(
0, 
0, 
-1, 0.781076, 1, -1, 0.315391,-99) , 
3, 2.38723, 1, 0, 0.490373,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.348674);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.50385, 1, 1, 0.651481,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340843,-99) , 
3, 1.42309, 1, 0, 0.406529,-99) , 
11, -3.10612, 1, 0, 0.534032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197818,-99) , 
2, 2.22447, 1, 0, 0.497225,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.252911);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -4.18749, 1, 1, 0.668475,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2939,-99) , 
11, -2.29351, 1, 0, 0.476648,-99) , 
7, 3.84994, 1, 0, 0.530927,-99) , 
NN(
0, 
0, 
-1, 0.876072, 1, -1, 0.282235,-99) , 
10, -1.87641, 1, 0, 0.485488,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.240079);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.771113,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37579,-99) , 
2, 1.24004, 1, 0, 0.479272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.23298,-99) , 
9, -3.2197, 1, 0, 0.440279,-99) , 
3, 0.678145, 1, 0, 0.462336,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.286425);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.747801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474141,-99) , 
9, -3.87504, 1, 0, 0.668032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404799,-99) , 
3, 2.79508, 1, 0, 0.583538,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665385,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298522,-99) , 
11, -3.48329, 1, 0, 0.378859,-99) , 
3, 1.01386, 1, 0, 0.409358,-99) , 
7, 3.84994, 1, 0, 0.455819,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.234516);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.24113, 1, 1, 0.662633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475937,-99) , 
5, 4.6821, 1, 0, 0.590202,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273712,-99) , 
7, 5.3101, 1, 0, 0.480924,-99) , 
NN(
0, 
0, 
-1, -3.47629, 0, -1, 0.334115,-99) , 
3, 2.33273, 1, 0, 0.414196,-99) , 
7, 3.84994, 1, 0, 0.460929,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.197151);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.95321, 1, 1, 0.652207,-99) , 
NN(
0, 
0, 
-1, 3.80697, 0, -1, 0.475434,-99) , 
9, -4.07506, 1, 0, 0.579136,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397841,-99) , 
3, 1.99694, 1, 0, 0.446877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306806,-99) , 
10, -1.87641, 1, 0, 0.420224,-99) , 
7, 3.84994, 1, 0, 0.462482,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.148535);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.4602, 1, 1, 0.633341,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435238,-99) , 
8, -3.79467, 0, 0, 0.498256,-99) , 
10, -2.86118, 1, 0, 0.572031,-99) , 
NN(
0, 
0, 
-1, 2.8096, 1, -1, 0.438054,-99) , 
7, 3.84994, 1, 0, 0.473666,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.205409);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401639,-99) , 
11, -2.07803, 1, 0, 0.563504,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409785,-99) , 
8, -3.13898, 0, 0, 0.44035,-99) , 
10, -2.69499, 1, 0, 0.515379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322352,-99) , 
2, 2.22447, 1, 0, 0.496193,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.18361);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672868,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376778,-99) , 
7, 4.87118, 1, 0, 0.505179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321402,-99) , 
1, 2.74403, 1, 0, 0.48159,-99) , 
3, 0.678145, 1, 0, 0.493723,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.139695);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.87001, 0, 1, 0.649511,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461846,-99) , 
1, 0.759115, 1, 0, 0.476707,-99) , 
3, 1.29989, 1, 0, 0.499119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372352,-99) , 
9, -3.2197, 1, 0, 0.478706,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.118725);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.91716, 1, 1, 0.551929,-99) , 
NN(
0, 
0, 
-1, 0.781076, 1, -1, 0.449069,-99) , 
3, 2.63967, 1, 0, 0.51838,-99) , 
NN(
0, 
0, 
-1, 5.02533, 1, -1, 0.398615,-99) , 
4, 2.97919, 0, 0, 0.500381,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.120153);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480649,-99) , 
1, 1.95321, 1, 0, 0.524069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404369,-99) , 
9, -2.96311, 1, 0, 0.509684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369934,-99) , 
2, 2.22447, 1, 0, 0.496051,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.134424);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.3341, 1, 1, 0.659109,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455165,-99) , 
7, 4.25703, 1, 0, 0.497418,-99) , 
3, 1.50385, 1, 0, 0.520284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411206,-99) , 
11, -1.72879, 1, 0, 0.505768,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.105751);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44332,-99) , 
2, 1.74297, 1, 0, 0.532574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430509,-99) , 
6, 5.55327, 1, 0, 0.520967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399033,-99) , 
2, 2.22447, 1, 0, 0.509224,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.109682);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634725,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414235,-99) , 
1, 2.56394, 1, 0, 0.504217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390992,-99) , 
7, 5.41932, 1, 0, 0.489442,-99) , 
11, -4.23098, 1, 0, 0.497847,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.096114);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492298,-99) , 
11, -3.8411, 1, 0, 0.520268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432576,-99) , 
3, 2.91013, 1, 0, 0.501738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407899,-99) , 
9, -3.2197, 1, 0, 0.486682,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.08117);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.40398, 1, 1, 0.532848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456303,-99) , 
3, 2.91013, 1, 0, 0.516716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431301,-99) , 
9, -3.2197, 1, 0, 0.503071,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.065874);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606463,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48883,-99) , 
7, 3.2623, 1, 0, 0.500213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425758,-99) , 
9, -3.2197, 1, 0, 0.489286,-99) , 
3, 0.678145, 1, 0, 0.496441,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0718204);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.70944, 1, 1, 0.530144,-99) , 
NN(
0, 
0, 
-1, -3.1156, 1, -1, 0.456659,-99) , 
5, 4.94449, 1, 0, 0.515842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43426,-99) , 
2, 2.22447, 1, 0, 0.508096,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0883312);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457768,-99) , 
9, -2.96311, 1, 0, 0.518125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437833,-99) , 
8, -4.81026, 0, 0, 0.510517,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376906,-99) , 
4, 4.51096, 0, 0, 0.449218,-99) , 
6, 5.31849, 1, 0, 0.499879,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0651891);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.57119, 0, 1, 0.55148,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467919,-99) , 
8, -3.91059, 0, 0, 0.491694,-99) , 
NN(
0, 
0, 
-1, -3.40367, 1, -1, 0.426551,-99) , 
6, 5.31849, 1, 0, 0.480981,-99) , 
2, -0.134857, 1, 0, 0.489893,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0522863);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579878,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410964,-99) , 
5, 5.14151, 1, 0, 0.491928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42328,-99) , 
1, 2.74403, 1, 0, 0.483324,-99) , 
3, 0.678145, 1, 0, 0.489204,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0836854);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571428,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479962,-99) , 
3, 1.42309, 1, 0, 0.490343,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393376,-99) , 
6, 3.78843, 1, 0, 0.436524,-99) , 
2, 1.53091, 1, 0, 0.476596,-99) , 
11, -4.23098, 1, 0, 0.481954,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0797449);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.90454, 1, 1, 0.542412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474639,-99) , 
9, -3.65029, 1, 0, 0.523651,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476754,-99) , 
11, -3.10612, 0, 0, 0.510246,-99) , 
NN(
0, 
0, 
-1, 5.02533, 1, -1, 0.453142,-99) , 
2, 0.825772, 1, 0, 0.47931,-99) , 
4, 4.51096, 0, 0, 0.492809,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0664195);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.8767, 0, 1, 0.57646,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476354,-99) , 
2, 0.781076, 1, 0, 0.494225,-99) , 
3, 1.50385, 1, 0, 0.505501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445715,-99) , 
11, -1.72879, 1, 0, 0.497586,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0650115);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560923,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443889,-99) , 
11, -2.28521, 1, 0, 0.503347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434615,-99) , 
3, 3.36386, 1, 0, 0.496356,-99) , 
3, 0.678145, 1, 0, 0.500266,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0839463);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540683,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49398,-99) , 
5, 3.88227, 0, 0, 0.550408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453138,-99) , 
3, 1.80383, 1, 0, 0.469833,-99) , 
11, -3.86876, 1, 0, 0.486288,-99) , 
9, -5.20801, 1, 0, 0.492812,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0930825);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547961,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463034,-99) , 
3, 2.86399, 1, 0, 0.502905,-99) , 
8, -3.47629, 0, 0, 0.514392,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423569,-99) , 
1, 2.44197, 1, 0, 0.494763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382935,-99) , 
5, 5.03384, 1, 0, 0.480503,-99) , 
3, 2.38723, 0, 0, 0.495975,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.07631);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459179,-99) , 
10, -2.58649, 1, 0, 0.499427,-99) , 
1, 1.08637, 1, 0, 0.508597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442854,-99) , 
3, 1.83426, 1, 0, 0.485289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405156,-99) , 
5, 5.03384, 1, 0, 0.475135,-99) , 
3, 2.38723, 0, 0, 0.490418,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0442155);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.781076, 1, 1, 0.517109,-99) , 
NN(
0, 
0, 
-1, 4.95495, 1, -1, 0.482336,-99) , 
4, 4.51096, 0, 0, 0.492692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447755,-99) , 
11, -1.72879, 1, 0, 0.486749,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0375439);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.0885, 1, 1, 0.513795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455843,-99) , 
10, -2.58649, 1, 0, 0.484082,-99) , 
7, 4.25703, 1, 0, 0.497159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458712,-99) , 
11, -1.72879, 1, 0, 0.492081,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0515992);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523146,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465413,-99) , 
7, 4.58895, 1, 0, 0.492865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424787,-99) , 
11, -2.08831, 1, 0, 0.483805,-99) , 
9, -5.20801, 1, 0, 0.48852,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0531715);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495876,-99) , 
6, 4.57119, 0, 0, 0.519889,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475731,-99) , 
11, -3.10612, 0, 0, 0.49152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394899,-99) , 
6, 4.32637, 1, 0, 0.448995,-99) , 
2, 1.66274, 1, 0, 0.481051,-99) , 
2, -0.134857, 1, 0, 0.485948,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0470957);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -4.25942, 1, 1, 0.522592,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485115,-99) , 
2, 1.23474, 0, 0, 0.492334,-99) , 
NN(
0, 
0, 
-1, 4.32637, 1, -1, 0.44908,-99) , 
2, 1.66274, 1, 0, 0.481702,-99) , 
2, -0.134857, 1, 0, 0.486858,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0538949);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445596,-99) , 
7, 4.81963, 1, 0, 0.51116,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450961,-99) , 
11, -3.09068, 0, 0, 0.485387,-99) , 
11, -3.51624, 1, 0, 0.495597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46709,-99) , 
11, -1.72879, 1, 0, 0.491837,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0427121);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527567,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535728,-99) , 
NN(
0, 
0, 
-1, 3.94557, 0, -1, 0.48076,-99) , 
7, 3.2623, 1, 0, 0.486426,-99) , 
3, 0.678145, 1, 0, 0.488929,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0552952);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48135,-99) , 
8, -3.91059, 1, 0, 0.527995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48092,-99) , 
4, 3.8412, 0, 0, 0.494857,-99) , 
0, 1.24325, 1, 0, 0.504645,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465608,-99) , 
2, 1.24004, 1, 0, 0.50244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417451,-99) , 
4, 4.5781, 0, 0, 0.451771,-99) , 
10, -2.34361, 1, 0, 0.485232,-99) , 
6, 4.46531, 1, 0, 0.496236,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0361207);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532012,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582845,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494528,-99) , 
7, 2.96852, 1, 0, 0.5004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438224,-99) , 
7, 5.41932, 1, 0, 0.492375,-99) , 
11, -4.23098, 1, 0, 0.494607,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0404962);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.82952, 0, 1, 0.530566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485885,-99) , 
5, 3.51705, 0, 0, 0.500976,-99) , 
0, 1.24325, 1, 0, 0.509709,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486935,-99) , 
11, -3.40367, 1, 0, 0.506609,-99) , 
NN(
0, 
0, 
-1, 4.5781, 0, -1, 0.460727,-99) , 
10, -2.34361, 1, 0, 0.49105,-99) , 
6, 4.46531, 1, 0, 0.501634,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.067944);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492723,-99) , 
9, -4.3471, 1, 0, 0.539706,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461604,-99) , 
11, -2.29351, 1, 0, 0.497034,-99) , 
1, 1.05621, 1, 0, 0.505209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421283,-99) , 
11, -3.64708, 1, 0, 0.459523,-99) , 
7, 3.02379, 1, 0, 0.484778,-99) , 
7, 3.84994, 0, 0, 0.499811,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0419565);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522929,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486414,-99) , 
5, 3.88227, 0, 0, 0.523459,-99) , 
NN(
0, 
0, 
-1, 5.20589, 1, -1, 0.482361,-99) , 
11, -3.86876, 1, 0, 0.490748,-99) , 
9, -5.20801, 1, 0, 0.494604,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0667059);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580208,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455962,-99) , 
7, 4.74264, 0, 0, 0.483781,-99) , 
9, -4.78475, 1, 0, 0.512513,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429189,-99) , 
7, 5.06968, 1, 0, 0.500613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450179,-99) , 
1, 2.91184, 1, 0, 0.494322,-99) , 
1, 1.55869, 1, 0, 0.500082,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0591819);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -4.75323, 1, 1, 0.546346,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459023,-99) , 
11, -3.44883, 0, 0, 0.476753,-99) , 
11, -2.9382, 0, 0, 0.510961,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483517,-99) , 
3, 1.81355, 1, 0, 0.495647,-99) , 
NN(
0, 
0, 
-1, 4.54729, 1, -1, 0.457184,-99) , 
2, 1.53785, 1, 0, 0.485961,-99) , 
1, 1.55869, 1, 0, 0.493867,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0537462);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478626,-99) , 
11, -2.43701, 1, 0, 0.518238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465099,-99) , 
7, 5.05187, 1, 0, 0.507769,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492709,-99) , 
8, -3.98285, 0, 0, 0.519598,-99) , 
NN(
0, 
0, 
-1, -2.34182, 1, -1, 0.475462,-99) , 
10, -3.09509, 1, 0, 0.491334,-99) , 
0, 1.62649, 1, 0, 0.498575,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0399299);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536998,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474355,-99) , 
8, -4.43733, 0, 0, 0.504546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452989,-99) , 
3, 3.36386, 1, 0, 0.49929,-99) , 
3, 0.678145, 1, 0, 0.501575,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0332797);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527056,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489094,-99) , 
9, -4.46146, 1, 0, 0.49889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462901,-99) , 
3, 3.36386, 1, 0, 0.495225,-99) , 
3, 0.678145, 1, 0, 0.497152,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0615165);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531337,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459117,-99) , 
9, -4.42734, 0, 0, 0.502293,-99) , 
1, 1.08637, 1, 0, 0.509104,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483877,-99) , 
1, 2.20766, 1, 0, 0.522669,-99) , 
NN(
0, 
0, 
-1, 1.49473, 0, -1, 0.470335,-99) , 
11, -2.77076, 0, 0, 0.492077,-99) , 
3, 2.38723, 0, 0, 0.499871,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0331125);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.2296, 1, 1, 0.529327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492564,-99) , 
2, 0.831934, 0, 0, 0.513809,-99) , 
NN(
NN(
0, 
0, 
-1, 4.51096, 0, 1, 0.5221,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448522,-99) , 
2, 1.53091, 1, 0, 0.488532,-99) , 
11, -3.71698, 1, 0, 0.497272,-99) , 
6, 3.61214, 1, 0, 0.500876,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0455738);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533085,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482903,-99) , 
10, -2.72635, 0, 0, 0.500873,-99) , 
6, 3.12461, 1, 0, 0.512528,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484301,-99) , 
10, -3.22734, 1, 0, 0.498903,-99) , 
NN(
0, 
0, 
-1, 1.99694, 1, -1, 0.463179,-99) , 
7, 5.05187, 1, 0, 0.491932,-99) , 
6, 3.61214, 1, 0, 0.496419,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0637534);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467943,-99) , 
9, -4.07185, 1, 0, 0.497879,-99) , 
9, -3.2197, 0, 0, 0.503526,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437474,-99) , 
11, -3.64708, 1, 0, 0.469685,-99) , 
7, 3.02379, 1, 0, 0.487516,-99) , 
7, 3.84994, 0, 0, 0.499309,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0296602);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489137,-99) , 
6, 4.57119, 0, 0, 0.509175,-99) , 
NN(
NN(
0, 
0, 
-1, 1.66274, 0, 1, 0.518801,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445968,-99) , 
8, -4.26837, 0, 0, 0.488428,-99) , 
0, 0.791723, 1, 0, 0.493044,-99) , 
2, -0.134857, 1, 0, 0.49508,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0374524);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495928,-99) , 
9, -4.25942, 1, 0, 0.510697,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488319,-99) , 
2, 0.464348, 1, 0, 0.494013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449877,-99) , 
0, 0.791723, 1, 0, 0.471336,-99) , 
2, 1.66274, 1, 0, 0.488467,-99) , 
2, -0.134857, 1, 0, 0.491272,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0248667);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497967,-99) , 
6, 4.57119, 0, 0, 0.512349,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494235,-99) , 
2, 1.23474, 0, 0, 0.499192,-99) , 
NN(
0, 
0, 
-1, 4.32637, 1, -1, 0.474927,-99) , 
2, 1.66274, 1, 0, 0.493262,-99) , 
2, -0.134857, 1, 0, 0.495671,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0169117);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.57119, 0, 1, 0.513628,-99) , 
NN(
NN(
0, 
0, 
-1, 5.55327, 0, 1, 0.502355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457172,-99) , 
6, 4.32637, 1, 0, 0.481131,-99) , 
2, 1.66274, 1, 0, 0.49717,-99) , 
2, -0.134857, 1, 0, 0.499247,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0258951);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499955,-99) , 
6, 4.57119, 0, 0, 0.509402,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480093,-99) , 
10, -2.73678, 0, 0, 0.508051,-99) , 
NN(
0, 
0, 
-1, 2.72911, 1, -1, 0.489885,-99) , 
6, 3.61214, 1, 0, 0.493982,-99) , 
2, -0.134857, 1, 0, 0.495927,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0306222);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518951,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498823,-99) , 
7, 4.71908, 0, 0, 0.507294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44453,-99) , 
7, 5.41932, 1, 0, 0.499163,-99) , 
11, -4.23098, 1, 0, 0.50028,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.023637);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -4.25942, 1, 1, 0.514251,-99) , 
NN(
NN(
0, 
0, 
-1, 5.55327, 0, 1, 0.506789,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473645,-99) , 
0, 0.791723, 1, 0, 0.489422,-99) , 
2, 1.66274, 1, 0, 0.50255,-99) , 
2, -0.134857, 1, 0, 0.504026,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0306154);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515109,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480828,-99) , 
9, -3.56323, 1, 0, 0.503604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457288,-99) , 
3, 3.36386, 1, 0, 0.498886,-99) , 
3, 0.678145, 1, 0, 0.499864,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0190949);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49831,-99) , 
10, -3.46124, 1, 0, 0.505667,-99) , 
NN(
NN(
0, 
0, 
-1, 1.66274, 0, 1, 0.510082,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461868,-99) , 
8, -4.26837, 0, 0, 0.492604,-99) , 
0, 0.791723, 1, 0, 0.49526,-99) , 
2, -0.134857, 1, 0, 0.496573,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0225106);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497969,-99) , 
2, -0.696617, 0, 0, 0.506355,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472608,-99) , 
3, 2.78773, 1, 0, 0.494508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476833,-99) , 
11, -1.72879, 1, 0, 0.492309,-99) , 
2, -0.134857, 1, 0, 0.49408,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0463569);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461966,-99) , 
9, -4.42734, 0, 0, 0.493434,-99) , 
1, 1.08637, 1, 0, 0.49855,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483767,-99) , 
11, -2.00622, 1, 0, 0.511582,-99) , 
NN(
0, 
0, 
-1, 1.49473, 0, -1, 0.471182,-99) , 
11, -2.77076, 0, 0, 0.487927,-99) , 
3, 2.38723, 0, 0, 0.492789,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0278708);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51636,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483423,-99) , 
7, 4.54158, 1, 0, 0.496404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458424,-99) , 
3, 3.36386, 1, 0, 0.492536,-99) , 
3, 0.678145, 1, 0, 0.493973,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0199154);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517939,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499245,-99) , 
9, -4.25942, 1, 0, 0.50694,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498154,-99) , 
2, 1.66274, 0, 0, 0.504616,-99) , 
NN(
0, 
0, 
-1, -4.26837, 0, -1, 0.48906,-99) , 
0, 0.791723, 1, 0, 0.491424,-99) , 
2, -0.134857, 1, 0, 0.493381,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0169721);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.966353, 1, 1, 0.507821,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496144,-99) , 
6, 5.55327, 0, 0, 0.498619,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468865,-99) , 
6, 4.32637, 1, 0, 0.486471,-99) , 
2, 1.66274, 1, 0, 0.495656,-99) , 
2, -0.134857, 1, 0, 0.497191,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0165039);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514647,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497621,-99) , 
11, -4.11846, 1, 0, 0.501029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470513,-99) , 
3, 3.36386, 1, 0, 0.497925,-99) , 
3, 0.678145, 1, 0, 0.498935,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0508193);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480802,-99) , 
10, -2.1992, 1, 0, 0.508903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470537,-99) , 
9, -5.20801, 0, 0, 0.504126,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540005,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458797,-99) , 
11, -3.64708, 1, 0, 0.482763,-99) , 
7, 3.02379, 1, 0, 0.495965,-99) , 
7, 3.84994, 0, 0, 0.50198,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0333492);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477456,-99) , 
10, -1.18114, 1, 0, 0.51328,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495489,-99) , 
11, -3.61554, 1, 0, 0.504158,-99) , 
NN(
0, 
0, 
-1, -3.73416, 1, -1, 0.484634,-99) , 
4, 3.71296, 0, 0, 0.496381,-99) , 
10, -1.87641, 0, 0, 0.499253,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0466633);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521758,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449875,-99) , 
1, 0.868483, 0, 0, 0.511274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473566,-99) , 
11, -3.41196, 1, 0, 0.492746,-99) , 
3, 2.24657, 1, 0, 0.501448,-99) , 
9, -5.20801, 1, 0, 0.503862,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0475749);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475389,-99) , 
7, 4.74264, 0, 0, 0.489854,-99) , 
9, -4.78475, 1, 0, 0.508656,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537732,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484417,-99) , 
7, 3.40213, 1, 0, 0.491489,-99) , 
0, 0.0859758, 1, 0, 0.495369,-99) , 
1, 1.55869, 1, 0, 0.49957,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0434052);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485765,-99) , 
0, 0.876072, 1, 0, 0.511407,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474316,-99) , 
9, -3.73416, 1, 0, 0.511683,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48285,-99) , 
3, 2.10178, 1, 0, 0.494928,-99) , 
8, -3.81009, 0, 0, 0.502689,-99) , 
10, -1.87641, 0, 0, 0.504168,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0476107);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464388,-99) , 
7, 4.70032, 1, 0, 0.507165,-99) , 
8, -3.47629, 0, 0, 0.510538,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495065,-99) , 
1, 2.20766, 1, 0, 0.521424,-99) , 
NN(
0, 
0, 
-1, 1.49473, 0, -1, 0.481195,-99) , 
11, -2.77076, 0, 0, 0.49784,-99) , 
3, 2.38723, 0, 0, 0.503653,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0318233);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484794,-99) , 
10, -1.18114, 1, 0, 0.514988,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494376,-99) , 
4, 3.92175, 0, 0, 0.506789,-99) , 
NN(
0, 
0, 
-1, 4.51891, 0, -1, 0.485346,-99) , 
3, 2.91013, 1, 0, 0.502195,-99) , 
10, -1.87641, 0, 0, 0.504366,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0369288);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48663,-99) , 
5, 4.36667, 1, 0, 0.515442,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476319,-99) , 
9, -4.86843, 0, 0, 0.506728,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462356,-99) , 
3, 2.26719, 0, 0, 0.491895,-99) , 
1, 1.11274, 0, 0, 0.503791,-99) , 
10, -1.87641, 0, 0, 0.505767,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0255643);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496273,-99) , 
9, -4.35937, 1, 0, 0.515559,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493555,-99) , 
11, -2.77076, 0, 0, 0.502062,-99) , 
NN(
0, 
0, 
-1, -3.81009, 0, -1, 0.485484,-99) , 
3, 2.91013, 1, 0, 0.49851,-99) , 
10, -1.87641, 0, 0, 0.5014,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0291118);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494599,-99) , 
10, -1.18114, 1, 0, 0.517055,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481254,-99) , 
9, -3.73416, 1, 0, 0.507383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475777,-99) , 
11, -2.49305, 1, 0, 0.496139,-99) , 
8, -3.81009, 0, 0, 0.501346,-99) , 
10, -1.87641, 0, 0, 0.504008,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0243393);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49923,-99) , 
0, 0.876072, 1, 0, 0.517466,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477542,-99) , 
0, 1.36552, 0, 0, 0.504123,-99) , 
NN(
0, 
0, 
-1, 3.46165, 0, -1, 0.492632,-99) , 
8, -3.81009, 0, 0, 0.497953,-99) , 
10, -1.87641, 0, 0, 0.50126,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0194705);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.36667, 1, 1, 0.519012,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474055,-99) , 
1, 1.67726, 0, 0, 0.512319,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474825,-99) , 
2, 2.00366, 1, 0, 0.497454,-99) , 
10, -3.6145, 1, 0, 0.499764,-99) , 
10, -1.87641, 0, 0, 0.503025,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0272969);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495511,-99) , 
5, 4.36667, 1, 0, 0.51415,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478912,-99) , 
1, 1.67726, 0, 0, 0.511276,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490506,-99) , 
9, -3.31723, 0, 0, 0.493712,-99) , 
10, -3.6145, 1, 0, 0.496439,-99) , 
10, -1.87641, 0, 0, 0.49944,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0170564);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.876072, 1, 1, 0.514238,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478166,-99) , 
1, 0.681736, 0, 0, 0.502923,-99) , 
NN(
0, 
0, 
-1, 4.51891, 0, -1, 0.490346,-99) , 
3, 2.91013, 1, 0, 0.500227,-99) , 
10, -1.87641, 0, 0, 0.502601,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0202368);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.57119, 0, 1, 0.51343,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492171,-99) , 
2, 0.977942, 1, 0, 0.501937,-99) , 
NN(
0, 
0, 
-1, 4.32637, 1, -1, 0.487606,-99) , 
2, 1.66274, 1, 0, 0.498447,-99) , 
2, -0.134857, 1, 0, 0.500341,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.036688);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541792,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463494,-99) , 
8, -3.47629, 1, 0, 0.492841,-99) , 
9, -4.78475, 1, 0, 0.507268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484443,-99) , 
11, -3.71698, 1, 0, 0.493936,-99) , 
6, 3.25877, 1, 0, 0.497149,-99) , 
1, 1.55869, 1, 0, 0.500344,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0196701);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.40709, 1, 1, 0.51051,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497787,-99) , 
9, -4.66149, 1, 0, 0.503285,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481705,-99) , 
7, 3.68627, 1, 0, 0.489191,-99) , 
3, 2.63967, 1, 0, 0.498604,-99) , 
4, 2.97919, 1, 0, 0.500365,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0103025);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.57119, 0, 1, 0.511196,-99) , 
NN(
NN(
0, 
0, 
-1, 5.55327, 0, 1, 0.502783,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47572,-99) , 
10, -2.25942, 1, 0, 0.492665,-99) , 
2, 1.66274, 1, 0, 0.50032,-99) , 
2, -0.134857, 1, 0, 0.501696,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0197523);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493515,-99) , 
0, 0.876072, 1, 0, 0.508486,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481698,-99) , 
11, -2.04299, 1, 0, 0.501897,-99) , 
NN(
0, 
0, 
-1, -3.73416, 1, -1, 0.491254,-99) , 
4, 3.71296, 0, 0, 0.497655,-99) , 
10, -1.87641, 0, 0, 0.499486,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0241544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492104,-99) , 
10, -1.18114, 1, 0, 0.509741,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497076,-99) , 
10, -3.6145, 1, 0, 0.502782,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486143,-99) , 
10, -2.70028, 0, 0, 0.493768,-99) , 
6, 4.37321, 0, 0, 0.497699,-99) , 
10, -1.87641, 0, 0, 0.499735,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0362323);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499362,-99) , 
4, 4.51096, 0, 0, 0.510993,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469209,-99) , 
3, 2.79508, 1, 0, 0.508181,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479163,-99) , 
2, 1.05725, 0, 0, 0.493358,-99) , 
11, -3.10612, 0, 0, 0.500417,-99) , 
6, 5.31849, 0, 0, 0.502194,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0224599);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496642,-99) , 
5, 4.51891, 1, 0, 0.513447,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491591,-99) , 
10, -2.91683, 0, 0, 0.507574,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470649,-99) , 
8, -4.19039, 0, 0, 0.494838,-99) , 
0, 1.24325, 1, 0, 0.498499,-99) , 
6, 5.31849, 0, 0, 0.501011,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0251753);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.51891, 1, 1, 0.512107,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491174,-99) , 
8, -3.91059, 1, 0, 0.507454,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485827,-99) , 
3, 1.81355, 1, 0, 0.491746,-99) , 
0, 1.24325, 1, 0, 0.496261,-99) , 
6, 5.31849, 0, 0, 0.498923,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0352361);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489814,-99) , 
1, 2.27042, 1, 0, 0.500953,-99) , 
1, 1.08637, 1, 0, 0.505021,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485255,-99) , 
7, 4.73086, 0, 0, 0.500065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45244,-99) , 
5, 5.03384, 1, 0, 0.494136,-99) , 
3, 2.38723, 0, 0, 0.499121,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0133468);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.06503, 0, 1, 0.511929,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498854,-99) , 
6, 5.55327, 0, 0, 0.501377,-99) , 
NN(
0, 
0, 
-1, -2.25942, 1, -1, 0.486439,-99) , 
2, 1.66274, 1, 0, 0.497741,-99) , 
2, -0.134857, 1, 0, 0.499533,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0193109);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.40709, 1, 1, 0.510836,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477409,-99) , 
8, -4.78589, 0, 0, 0.503176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483714,-99) , 
11, -1.95696, 1, 0, 0.500011,-99) , 
4, 2.97919, 1, 0, 0.501612,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0283308);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.84136, 1, 1, 0.509815,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486675,-99) , 
8, -3.49792, 0, 0, 0.495171,-99) , 
0, 1.45708, 1, 0, 0.501014,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519593,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478382,-99) , 
2, 0.781076, 1, 0, 0.488475,-99) , 
3, 1.45301, 1, 0, 0.493959,-99) , 
4, 4.51096, 1, 0, 0.498876,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.034934);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.79886, 0, 1, 0.508412,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44132,-99) , 
3, 1.90133, 1, 0, 0.469878,-99) , 
7, 5.01151, 1, 0, 0.500058,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496025,-99) , 
9, -4.30842, 1, 0, 0.514926,-99) , 
NN(
0, 
0, 
-1, 0.887811, 1, -1, 0.472371,-99) , 
0, 1.6932, 0, 0, 0.493504,-99) , 
8, -3.47629, 1, 0, 0.498407,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0329673);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507275,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472393,-99) , 
7, 4.70032, 1, 0, 0.494568,-99) , 
8, -3.47629, 0, 0, 0.49782,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488241,-99) , 
7, 4.76998, 0, 0, 0.499628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46423,-99) , 
7, 5.10515, 1, 0, 0.492311,-99) , 
3, 2.38723, 0, 0, 0.494834,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0237763);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505998,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49195,-99) , 
11, -4.00183, 1, 0, 0.497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460262,-99) , 
9, -5.20801, 0, 0, 0.494257,-99) , 
11, -1.72879, 0, 0, 0.495786,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0320876);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48599,-99) , 
11, -3.13492, 0, 0, 0.51473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460902,-99) , 
3, 1.60307, 0, 0, 0.503888,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495185,-99) , 
3, 1.23646, 1, 0, 0.500998,-99) , 
NN(
0, 
0, 
-1, -3.10612, 0, -1, 0.48197,-99) , 
4, 3.21948, 0, 0, 0.496919,-99) , 
5, 3.54134, 1, 0, 0.498691,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0221445);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.40709, 1, 1, 0.510739,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492408,-99) , 
3, 2.81544, 1, 0, 0.506068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484344,-99) , 
11, -1.95696, 1, 0, 0.502536,-99) , 
4, 2.97919, 1, 0, 0.503749,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0379099);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489126,-99) , 
11, -2.56284, 1, 0, 0.50971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455097,-99) , 
7, 5.41932, 1, 0, 0.50264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489924,-99) , 
11, -4.23098, 0, 0, 0.501923,-99)    );
   return;
};

// Clean up
inline void ReadBDTD::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDTD::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadBDTD::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 9.42282038883;
   fDecTF_1[0][0][1] = -0.159766194625;
   fDecTF_1[0][0][2] = -4.86984283129;
   fDecTF_1[0][0][3] = 0.0575770608586;
   fDecTF_1[0][0][4] = 1.17434728632;
   fDecTF_1[0][0][5] = -0.0383286953417;
   fDecTF_1[0][0][6] = -0.519447360211;
   fDecTF_1[0][0][7] = 0.0279301354495;
   fDecTF_1[0][0][8] = -8.43648005864;
   fDecTF_1[0][0][9] = 0.156899260782;
   fDecTF_1[0][0][10] = 4.44314210265;
   fDecTF_1[0][0][11] = -0.0692785580386;
   fDecTF_1[0][1][0] = -0.159766194625;
   fDecTF_1[0][1][1] = 7.19882784352;
   fDecTF_1[0][1][2] = -0.0065620971018;
   fDecTF_1[0][1][3] = -4.19344234532;
   fDecTF_1[0][1][4] = -0.029501251547;
   fDecTF_1[0][1][5] = 1.21150844041;
   fDecTF_1[0][1][6] = -0.0276491608561;
   fDecTF_1[0][1][7] = -0.619595929065;
   fDecTF_1[0][1][8] = 0.145871682076;
   fDecTF_1[0][1][9] = -5.72848296418;
   fDecTF_1[0][1][10] = 0.0338557232781;
   fDecTF_1[0][1][11] = 3.32863684757;
   fDecTF_1[0][2][0] = -4.86984283129;
   fDecTF_1[0][2][1] = -0.00656209710181;
   fDecTF_1[0][2][2] = 9.20317347235;
   fDecTF_1[0][2][3] = -0.121887881199;
   fDecTF_1[0][2][4] = 0.0052435666921;
   fDecTF_1[0][2][5] = -0.0587101028347;
   fDecTF_1[0][2][6] = 0.845512347498;
   fDecTF_1[0][2][7] = -0.0623667438771;
   fDecTF_1[0][2][8] = 4.26518991407;
   fDecTF_1[0][2][9] = 0.0384798339085;
   fDecTF_1[0][2][10] = -7.76056890189;
   fDecTF_1[0][2][11] = 0.148569065235;
   fDecTF_1[0][3][0] = 0.0575770608586;
   fDecTF_1[0][3][1] = -4.19344234532;
   fDecTF_1[0][3][2] = -0.121887881199;
   fDecTF_1[0][3][3] = 7.58045230776;
   fDecTF_1[0][3][4] = -0.0104622109402;
   fDecTF_1[0][3][5] = -0.422546764139;
   fDecTF_1[0][3][6] = 0.0124554318588;
   fDecTF_1[0][3][7] = 0.855574067032;
   fDecTF_1[0][3][8] = -0.0485403486362;
   fDecTF_1[0][3][9] = 3.0995068569;
   fDecTF_1[0][3][10] = 0.102849122804;
   fDecTF_1[0][3][11] = -5.30976736054;
   fDecTF_1[0][4][0] = 1.17434728632;
   fDecTF_1[0][4][1] = -0.029501251547;
   fDecTF_1[0][4][2] = 0.0052435666921;
   fDecTF_1[0][4][3] = -0.0104622109402;
   fDecTF_1[0][4][4] = 3.9178096203;
   fDecTF_1[0][4][5] = -0.135800944888;
   fDecTF_1[0][4][6] = -1.31012222213;
   fDecTF_1[0][4][7] = -0.00633738973863;
   fDecTF_1[0][4][8] = -2.70344131976;
   fDecTF_1[0][4][9] = 0.0350234542171;
   fDecTF_1[0][4][10] = 0.220907360962;
   fDecTF_1[0][4][11] = 0.0732290036637;
   fDecTF_1[0][5][0] = -0.0383286953417;
   fDecTF_1[0][5][1] = 1.21150844041;
   fDecTF_1[0][5][2] = -0.0587101028347;
   fDecTF_1[0][5][3] = -0.422546764139;
   fDecTF_1[0][5][4] = -0.135800944888;
   fDecTF_1[0][5][5] = 4.43667507327;
   fDecTF_1[0][5][6] = -0.000836514009708;
   fDecTF_1[0][5][7] = -1.57732126379;
   fDecTF_1[0][5][8] = 0.0743809033325;
   fDecTF_1[0][5][9] = -2.99799235379;
   fDecTF_1[0][5][10] = 0.0893191703298;
   fDecTF_1[0][5][11] = 0.729213249581;
   fDecTF_1[0][6][0] = -0.519447360211;
   fDecTF_1[0][6][1] = -0.0276491608561;
   fDecTF_1[0][6][2] = 0.845512347498;
   fDecTF_1[0][6][3] = 0.0124554318588;
   fDecTF_1[0][6][4] = -1.31012222213;
   fDecTF_1[0][6][5] = -0.000836514009709;
   fDecTF_1[0][6][6] = 4.01723152466;
   fDecTF_1[0][6][7] = -0.0982946389338;
   fDecTF_1[0][6][8] = 0.620815178306;
   fDecTF_1[0][6][9] = 0.0521128335927;
   fDecTF_1[0][6][10] = -2.6208885802;
   fDecTF_1[0][6][11] = 0.00336515513572;
   fDecTF_1[0][7][0] = 0.0279301354495;
   fDecTF_1[0][7][1] = -0.619595929065;
   fDecTF_1[0][7][2] = -0.0623667438771;
   fDecTF_1[0][7][3] = 0.855574067032;
   fDecTF_1[0][7][4] = -0.00633738973863;
   fDecTF_1[0][7][5] = -1.57732126379;
   fDecTF_1[0][7][6] = -0.0982946389338;
   fDecTF_1[0][7][7] = 4.42111482785;
   fDecTF_1[0][7][8] = -0.0253311284441;
   fDecTF_1[0][7][9] = 0.705110233369;
   fDecTF_1[0][7][10] = 0.0978613157602;
   fDecTF_1[0][7][11] = -2.61707140027;
   fDecTF_1[0][8][0] = -8.43648005864;
   fDecTF_1[0][8][1] = 0.145871682076;
   fDecTF_1[0][8][2] = 4.26518991407;
   fDecTF_1[0][8][3] = -0.0485403486362;
   fDecTF_1[0][8][4] = -2.70344131976;
   fDecTF_1[0][8][5] = 0.0743809033325;
   fDecTF_1[0][8][6] = 0.620815178306;
   fDecTF_1[0][8][7] = -0.0253311284441;
   fDecTF_1[0][8][8] = 10.3146433953;
   fDecTF_1[0][8][9] = -0.213728570608;
   fDecTF_1[0][8][10] = -4.97879124363;
   fDecTF_1[0][8][11] = 0.0865358260559;
   fDecTF_1[0][9][0] = 0.156899260782;
   fDecTF_1[0][9][1] = -5.72848296418;
   fDecTF_1[0][9][2] = 0.0384798339085;
   fDecTF_1[0][9][3] = 3.0995068569;
   fDecTF_1[0][9][4] = 0.0350234542171;
   fDecTF_1[0][9][5] = -2.99799235379;
   fDecTF_1[0][9][6] = 0.0521128335926;
   fDecTF_1[0][9][7] = 0.705110233369;
   fDecTF_1[0][9][8] = -0.213728570608;
   fDecTF_1[0][9][9] = 7.36474682086;
   fDecTF_1[0][9][10] = -0.036492021114;
   fDecTF_1[0][9][11] = -3.49601325633;
   fDecTF_1[0][10][0] = 4.44314210265;
   fDecTF_1[0][10][1] = 0.0338557232781;
   fDecTF_1[0][10][2] = -7.76056890189;
   fDecTF_1[0][10][3] = 0.102849122804;
   fDecTF_1[0][10][4] = 0.220907360962;
   fDecTF_1[0][10][5] = 0.0893191703298;
   fDecTF_1[0][10][6] = -2.6208885802;
   fDecTF_1[0][10][7] = 0.0978613157602;
   fDecTF_1[0][10][8] = -4.97879124363;
   fDecTF_1[0][10][9] = -0.036492021114;
   fDecTF_1[0][10][10] = 9.95766102107;
   fDecTF_1[0][10][11] = -0.263148365479;
   fDecTF_1[0][11][0] = -0.0692785580386;
   fDecTF_1[0][11][1] = 3.32863684757;
   fDecTF_1[0][11][2] = 0.148569065235;
   fDecTF_1[0][11][3] = -5.30976736054;
   fDecTF_1[0][11][4] = 0.0732290036637;
   fDecTF_1[0][11][5] = 0.729213249581;
   fDecTF_1[0][11][6] = 0.00336515513572;
   fDecTF_1[0][11][7] = -2.61707140027;
   fDecTF_1[0][11][8] = 0.0865358260559;
   fDecTF_1[0][11][9] = -3.49601325633;
   fDecTF_1[0][11][10] = -0.263148365479;
   fDecTF_1[0][11][11] = 6.75203225919;
   fDecTF_1[1][0][0] = 6.02872492797;
   fDecTF_1[1][0][1] = -0.210455543748;
   fDecTF_1[1][0][2] = -1.52434801443;
   fDecTF_1[1][0][3] = 0.0111901312989;
   fDecTF_1[1][0][4] = 0.707964868104;
   fDecTF_1[1][0][5] = -0.0604604227458;
   fDecTF_1[1][0][6] = 0.00727855856693;
   fDecTF_1[1][0][7] = 0.078350116977;
   fDecTF_1[1][0][8] = -5.10089892352;
   fDecTF_1[1][0][9] = 0.17119874126;
   fDecTF_1[1][0][10] = 1.20016042187;
   fDecTF_1[1][0][11] = 0.00176657871919;
   fDecTF_1[1][1][0] = -0.210455543748;
   fDecTF_1[1][1][1] = 4.23495295721;
   fDecTF_1[1][1][2] = 0.0463994603434;
   fDecTF_1[1][1][3] = -1.84609528755;
   fDecTF_1[1][1][4] = -0.0103730593123;
   fDecTF_1[1][1][5] = 0.477703513375;
   fDecTF_1[1][1][6] = -0.0677577947049;
   fDecTF_1[1][1][7] = -0.397201291111;
   fDecTF_1[1][1][8] = 0.186025958739;
   fDecTF_1[1][1][9] = -2.95247319913;
   fDecTF_1[1][1][10] = -0.0440070175791;
   fDecTF_1[1][1][11] = 1.81174247105;
   fDecTF_1[1][2][0] = -1.52434801443;
   fDecTF_1[1][2][1] = 0.0463994603434;
   fDecTF_1[1][2][2] = 5.02692390355;
   fDecTF_1[1][2][3] = -0.0242689896355;
   fDecTF_1[1][2][4] = 0.348947558537;
   fDecTF_1[1][2][5] = -0.0769048863422;
   fDecTF_1[1][2][6] = -0.11727503651;
   fDecTF_1[1][2][7] = -0.173836144987;
   fDecTF_1[1][2][8] = 1.20087345662;
   fDecTF_1[1][2][9] = 0.0536998401646;
   fDecTF_1[1][2][10] = -3.54834662584;
   fDecTF_1[1][2][11] = 0.0661025894106;
   fDecTF_1[1][3][0] = 0.0111901312989;
   fDecTF_1[1][3][1] = -1.84609528755;
   fDecTF_1[1][3][2] = -0.0242689896355;
   fDecTF_1[1][3][3] = 6.44076925666;
   fDecTF_1[1][3][4] = 0.0181167913009;
   fDecTF_1[1][3][5] = -0.376245369068;
   fDecTF_1[1][3][6] = 0.104287721205;
   fDecTF_1[1][3][7] = 0.451219357513;
   fDecTF_1[1][3][8] = 0.033155799896;
   fDecTF_1[1][3][9] = 1.56041401605;
   fDecTF_1[1][3][10] = -0.131021947366;
   fDecTF_1[1][3][11] = -3.56011669683;
   fDecTF_1[1][4][0] = 0.707964868104;
   fDecTF_1[1][4][1] = -0.0103730593123;
   fDecTF_1[1][4][2] = 0.348947558537;
   fDecTF_1[1][4][3] = 0.0181167913009;
   fDecTF_1[1][4][4] = 3.25706074211;
   fDecTF_1[1][4][5] = -0.0894160993352;
   fDecTF_1[1][4][6] = -0.571956949936;
   fDecTF_1[1][4][7] = 0.0271178607624;
   fDecTF_1[1][4][8] = -2.23386529438;
   fDecTF_1[1][4][9] = 0.021506235043;
   fDecTF_1[1][4][10] = -0.190423696088;
   fDecTF_1[1][4][11] = 0.00722598000457;
   fDecTF_1[1][5][0] = -0.0604604227458;
   fDecTF_1[1][5][1] = 0.477703513375;
   fDecTF_1[1][5][2] = -0.0769048863422;
   fDecTF_1[1][5][3] = -0.376245369068;
   fDecTF_1[1][5][4] = -0.0894160993352;
   fDecTF_1[1][5][5] = 2.63580323899;
   fDecTF_1[1][5][6] = 0.0341401708233;
   fDecTF_1[1][5][7] = -1.22233438144;
   fDecTF_1[1][5][8] = 0.0924925093139;
   fDecTF_1[1][5][9] = -1.81389430797;
   fDecTF_1[1][5][10] = 0.0622592580111;
   fDecTF_1[1][5][11] = 0.625152192396;
   fDecTF_1[1][6][0] = 0.00727855856693;
   fDecTF_1[1][6][1] = -0.0677577947049;
   fDecTF_1[1][6][2] = -0.11727503651;
   fDecTF_1[1][6][3] = 0.104287721205;
   fDecTF_1[1][6][4] = -0.571956949936;
   fDecTF_1[1][6][5] = 0.0341401708233;
   fDecTF_1[1][6][6] = 2.88701392649;
   fDecTF_1[1][6][7] = -0.148561273753;
   fDecTF_1[1][6][8] = -0.00312524457256;
   fDecTF_1[1][6][9] = 0.0363840298787;
   fDecTF_1[1][6][10] = -1.46018396983;
   fDecTF_1[1][6][11] = -0.0398808791467;
   fDecTF_1[1][7][0] = 0.078350116977;
   fDecTF_1[1][7][1] = -0.397201291111;
   fDecTF_1[1][7][2] = -0.173836144987;
   fDecTF_1[1][7][3] = 0.451219357513;
   fDecTF_1[1][7][4] = 0.0271178607624;
   fDecTF_1[1][7][5] = -1.22233438144;
   fDecTF_1[1][7][6] = -0.148561273753;
   fDecTF_1[1][7][7] = 2.57296855377;
   fDecTF_1[1][7][8] = -0.0979122017291;
   fDecTF_1[1][7][9] = 0.887117390171;
   fDecTF_1[1][7][10] = 0.302421353177;
   fDecTF_1[1][7][11] = -1.65811558744;
   fDecTF_1[1][8][0] = -5.10089892352;
   fDecTF_1[1][8][1] = 0.186025958739;
   fDecTF_1[1][8][2] = 1.20087345662;
   fDecTF_1[1][8][3] = 0.033155799896;
   fDecTF_1[1][8][4] = -2.23386529438;
   fDecTF_1[1][8][5] = 0.0924925093139;
   fDecTF_1[1][8][6] = -0.00312524457256;
   fDecTF_1[1][8][7] = -0.0979122017291;
   fDecTF_1[1][8][8] = 6.69479526244;
   fDecTF_1[1][8][9] = -0.261100568584;
   fDecTF_1[1][8][10] = -1.4461712203;
   fDecTF_1[1][8][11] = 0.0155245310155;
   fDecTF_1[1][9][0] = 0.17119874126;
   fDecTF_1[1][9][1] = -2.95247319913;
   fDecTF_1[1][9][2] = 0.0536998401646;
   fDecTF_1[1][9][3] = 1.56041401605;
   fDecTF_1[1][9][4] = 0.021506235043;
   fDecTF_1[1][9][5] = -1.81389430797;
   fDecTF_1[1][9][6] = 0.0363840298787;
   fDecTF_1[1][9][7] = 0.887117390171;
   fDecTF_1[1][9][8] = -0.261100568584;
   fDecTF_1[1][9][9] = 4.00193845338;
   fDecTF_1[1][9][10] = -0.0110004858174;
   fDecTF_1[1][9][11] = -2.28840745634;
   fDecTF_1[1][10][0] = 1.20016042187;
   fDecTF_1[1][10][1] = -0.0440070175791;
   fDecTF_1[1][10][2] = -3.54834662584;
   fDecTF_1[1][10][3] = -0.131021947366;
   fDecTF_1[1][10][4] = -0.190423696088;
   fDecTF_1[1][10][5] = 0.0622592580111;
   fDecTF_1[1][10][6] = -1.46018396983;
   fDecTF_1[1][10][7] = 0.302421353177;
   fDecTF_1[1][10][8] = -1.4461712203;
   fDecTF_1[1][10][9] = -0.0110004858174;
   fDecTF_1[1][10][10] = 5.03762188746;
   fDecTF_1[1][10][11] = -0.107339309664;
   fDecTF_1[1][11][0] = 0.00176657871919;
   fDecTF_1[1][11][1] = 1.81174247105;
   fDecTF_1[1][11][2] = 0.0661025894106;
   fDecTF_1[1][11][3] = -3.56011669683;
   fDecTF_1[1][11][4] = 0.00722598000457;
   fDecTF_1[1][11][5] = 0.625152192396;
   fDecTF_1[1][11][6] = -0.0398808791467;
   fDecTF_1[1][11][7] = -1.65811558744;
   fDecTF_1[1][11][8] = 0.0155245310155;
   fDecTF_1[1][11][9] = -2.28840745634;
   fDecTF_1[1][11][10] = -0.107339309664;
   fDecTF_1[1][11][11] = 4.62820428056;
   fDecTF_1[2][0][0] = 7.87048509818;
   fDecTF_1[2][0][1] = -0.229654234833;
   fDecTF_1[2][0][2] = -3.23147069795;
   fDecTF_1[2][0][3] = 0.0330527666652;
   fDecTF_1[2][0][4] = 0.949868671774;
   fDecTF_1[2][0][5] = -0.0244291522666;
   fDecTF_1[2][0][6] = -0.19175004509;
   fDecTF_1[2][0][7] = 0.0942378757954;
   fDecTF_1[2][0][8] = -6.88569037432;
   fDecTF_1[2][0][9] = 0.185157510958;
   fDecTF_1[2][0][10] = 2.77465965635;
   fDecTF_1[2][0][11] = -0.0557643392895;
   fDecTF_1[2][1][0] = -0.229654234833;
   fDecTF_1[2][1][1] = 5.86855956038;
   fDecTF_1[2][1][2] = 0.084114703984;
   fDecTF_1[2][1][3] = -3.4335588498;
   fDecTF_1[2][1][4] = -0.0355182050468;
   fDecTF_1[2][1][5] = 0.982950549896;
   fDecTF_1[2][1][6] = -0.0245117443804;
   fDecTF_1[2][1][7] = -0.614590763492;
   fDecTF_1[2][1][8] = 0.2105112844;
   fDecTF_1[2][1][9] = -4.49322398837;
   fDecTF_1[2][1][10] = -0.0538307526374;
   fDecTF_1[2][1][11] = 2.79912707795;
   fDecTF_1[2][2][0] = -3.23147069795;
   fDecTF_1[2][2][1] = 0.084114703984;
   fDecTF_1[2][2][2] = 7.21169329518;
   fDecTF_1[2][2][3] = -0.114082987979;
   fDecTF_1[2][2][4] = 0.243987364128;
   fDecTF_1[2][2][5] = -0.0897037332039;
   fDecTF_1[2][2][6] = 0.358597393556;
   fDecTF_1[2][2][7] = -0.192021506431;
   fDecTF_1[2][2][8] = 2.69162741979;
   fDecTF_1[2][2][9] = 0.034377776425;
   fDecTF_1[2][2][10] = -5.73333817835;
   fDecTF_1[2][2][11] = 0.110449566151;
   fDecTF_1[2][3][0] = 0.0330527666652;
   fDecTF_1[2][3][1] = -3.4335588498;
   fDecTF_1[2][3][2] = -0.114082987979;
   fDecTF_1[2][3][3] = 6.73413637539;
   fDecTF_1[2][3][4] = 0.00082041768007;
   fDecTF_1[2][3][5] = -0.268599013481;
   fDecTF_1[2][3][6] = 0.046540063067;
   fDecTF_1[2][3][7] = 0.619477086324;
   fDecTF_1[2][3][8] = 0.0230487406821;
   fDecTF_1[2][3][9] = 2.56584381668;
   fDecTF_1[2][3][10] = -0.00797714018342;
   fDecTF_1[2][3][11] = -4.63834167194;
   fDecTF_1[2][4][0] = 0.949868671774;
   fDecTF_1[2][4][1] = -0.0355182050468;
   fDecTF_1[2][4][2] = 0.243987364128;
   fDecTF_1[2][4][3] = 0.00082041768007;
   fDecTF_1[2][4][4] = 3.68648473228;
   fDecTF_1[2][4][5] = -0.111962377395;
   fDecTF_1[2][4][6] = -1.03680125698;
   fDecTF_1[2][4][7] = 0.016284621587;
   fDecTF_1[2][4][8] = -2.49690273296;
   fDecTF_1[2][4][9] = 0.024294906297;
   fDecTF_1[2][4][10] = -0.0108627797007;
   fDecTF_1[2][4][11] = 0.0750515439239;
   fDecTF_1[2][5][0] = -0.0244291522666;
   fDecTF_1[2][5][1] = 0.982950549896;
   fDecTF_1[2][5][2] = -0.0897037332039;
   fDecTF_1[2][5][3] = -0.268599013481;
   fDecTF_1[2][5][4] = -0.111962377395;
   fDecTF_1[2][5][5] = 3.66044463815;
   fDecTF_1[2][5][6] = -0.00397237585458;
   fDecTF_1[2][5][7] = -1.46443872246;
   fDecTF_1[2][5][8] = 0.0407444935116;
   fDecTF_1[2][5][9] = -2.57898887818;
   fDecTF_1[2][5][10] = 0.131766486292;
   fDecTF_1[2][5][11] = 0.708898890874;
   fDecTF_1[2][6][0] = -0.19175004509;
   fDecTF_1[2][6][1] = -0.0245117443804;
   fDecTF_1[2][6][2] = 0.358597393556;
   fDecTF_1[2][6][3] = 0.046540063067;
   fDecTF_1[2][6][4] = -1.03680125698;
   fDecTF_1[2][6][5] = -0.00397237585458;
   fDecTF_1[2][6][6] = 3.60508027633;
   fDecTF_1[2][6][7] = -0.135710120612;
   fDecTF_1[2][6][8] = 0.285724675597;
   fDecTF_1[2][6][9] = 0.0490955986993;
   fDecTF_1[2][6][10] = -2.08889262227;
   fDecTF_1[2][6][11] = -0.0236634706222;
   fDecTF_1[2][7][0] = 0.0942378757954;
   fDecTF_1[2][7][1] = -0.614590763492;
   fDecTF_1[2][7][2] = -0.192021506431;
   fDecTF_1[2][7][3] = 0.619477086324;
   fDecTF_1[2][7][4] = 0.016284621587;
   fDecTF_1[2][7][5] = -1.46443872246;
   fDecTF_1[2][7][6] = -0.135710120612;
   fDecTF_1[2][7][7] = 3.61895004685;
   fDecTF_1[2][7][8] = -0.0885906638527;
   fDecTF_1[2][7][9] = 0.910181980522;
   fDecTF_1[2][7][10] = 0.238800822601;
   fDecTF_1[2][7][11] = -2.24247837285;
   fDecTF_1[2][8][0] = -6.88569037432;
   fDecTF_1[2][8][1] = 0.2105112844;
   fDecTF_1[2][8][2] = 2.69162741979;
   fDecTF_1[2][8][3] = 0.0230487406821;
   fDecTF_1[2][8][4] = -2.49690273296;
   fDecTF_1[2][8][5] = 0.0407444935116;
   fDecTF_1[2][8][6] = 0.285724675597;
   fDecTF_1[2][8][7] = -0.0885906638527;
   fDecTF_1[2][8][8] = 8.6455670132;
   fDecTF_1[2][8][9] = -0.262487392472;
   fDecTF_1[2][8][10] = -3.18646293988;
   fDecTF_1[2][8][11] = 0.103450243486;
   fDecTF_1[2][9][0] = 0.185157510958;
   fDecTF_1[2][9][1] = -4.49322398837;
   fDecTF_1[2][9][2] = 0.0343777764251;
   fDecTF_1[2][9][3] = 2.56584381668;
   fDecTF_1[2][9][4] = 0.024294906297;
   fDecTF_1[2][9][5] = -2.57898887818;
   fDecTF_1[2][9][6] = 0.0490955986993;
   fDecTF_1[2][9][7] = 0.910181980522;
   fDecTF_1[2][9][8] = -0.262487392472;
   fDecTF_1[2][9][9] = 5.90802365415;
   fDecTF_1[2][9][10] = -0.00361719902661;
   fDecTF_1[2][9][11] = -3.07546276118;
   fDecTF_1[2][10][0] = 2.77465965635;
   fDecTF_1[2][10][1] = -0.0538307526374;
   fDecTF_1[2][10][2] = -5.73333817835;
   fDecTF_1[2][10][3] = -0.00797714018341;
   fDecTF_1[2][10][4] = -0.0108627797007;
   fDecTF_1[2][10][5] = 0.131766486292;
   fDecTF_1[2][10][6] = -2.08889262227;
   fDecTF_1[2][10][7] = 0.238800822601;
   fDecTF_1[2][10][8] = -3.18646293988;
   fDecTF_1[2][10][9] = -0.00361719902661;
   fDecTF_1[2][10][10] = 7.63410686765;
   fDecTF_1[2][10][11] = -0.269156749296;
   fDecTF_1[2][11][0] = -0.0557643392895;
   fDecTF_1[2][11][1] = 2.79912707795;
   fDecTF_1[2][11][2] = 0.110449566151;
   fDecTF_1[2][11][3] = -4.63834167194;
   fDecTF_1[2][11][4] = 0.0750515439239;
   fDecTF_1[2][11][5] = 0.708898890874;
   fDecTF_1[2][11][6] = -0.0236634706222;
   fDecTF_1[2][11][7] = -2.24247837285;
   fDecTF_1[2][11][8] = 0.103450243486;
   fDecTF_1[2][11][9] = -3.07546276118;
   fDecTF_1[2][11][10] = -0.269156749296;
   fDecTF_1[2][11][11] = 5.85390833728;
}

//_______________________________________________________________________
inline void ReadBDTD::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   }

   std::vector<double> tv;
   for (int i=0; i<12;i++) {
      double v = 0;
      for (int j=0; j<12; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<12;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadBDTD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadBDTD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
