[PROJECT]
PROJPATH     =  prod
PROJVERSION  =  19Jan31
PROJTITLE    =  ISS_PART06
PROJBIN      =  YiProdNtuple
PROJFLIST    =  flist.cern.iss.B1130.pass7
EVENTTYPE    =  ISS
FILEPEREXE   =  1
JOBREGION    =  PART
EXESATID     =  150000
EXEENDID     =  155849

[QUEUE]
QUEUE      =  tomorrow
STORAGE    =  EOS
EXEPERJOB  =  6
CONFIRM    =  NONE
