[PROJECT]
PROJPATH     =  prod
PROJVERSION  =  19May21
PROJTITLE    =  ISS_PART06
PROJBIN      =  YiProdNtuple
PROJFLIST    =  flist.cern.iss.B1130.pass7
EVENTTYPE    =  ISS
FILEPEREXE   =  10
JOBREGION    =  PART
EXESATID     =  15000
EXEENDID     =  16577

[QUEUE]
QUEUE      =  tomorrow
STORAGE    =  EOS
EXEPERJOB  =  1
CONFIRM    =  NONE
