#ifndef __TRACKSys_H__
#define __TRACKSys_H__


#include "Sys.h"
#include "Math.h"
#include "TmeMeas.h"
#include "IonEloss.h"
#include "GmIonEloss.h"
#include "PartInfo.h"
#include "PhySt.h"
#include "MagEnv.h"
#include "MagEnvAms.h"
#include "MatEnv.h"
#include "MatEnvAms.h"
#include "Prop.h"
#include "HitSt.h"
#include "TrFitPar.h"
#include "SimpleTrFit.h"
#include "PhyTrFit.h"
#include "PhyBtaFit.h"
//#include "PhyMuFit.h"
#include "InterfaceAms.h"

#include "Sys.C"
#include "Math.C"
#include "TmeMeas.C"
#include "IonEloss.C"
#include "GmIonEloss.C"
#include "PartInfo.C"
#include "PhySt.C"
#include "MagEnv.C"
#include "MagEnvAms.C"
#include "MatEnv.C"
#include "MatEnvAms.C"
#include "Prop.C"
#include "HitSt.C"
#include "TrFitPar.C"
#include "SimpleTrFit.C"
#include "PhyTrFit.C"
#include "PhyBtaFit.C"
//#include "PhyMuFit.C"
#include "InterfaceAms.C"


#endif // __TRACKSys_H__
