/********************************************************************
* rootdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablerootdict();
extern void G__cpp_setup_inheritancerootdict();
extern void G__cpp_setup_typetablerootdict();
extern void G__cpp_setup_memvarrootdict();
extern void G__cpp_setup_globalrootdict();
extern void G__cpp_setup_memfuncrootdict();
extern void G__cpp_setup_funcrootdict();
extern void G__set_cpp_environmentrootdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "HitState.h"
#include "SimpleHitState.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootdictLN_TClass;
extern G__linked_taginfo G__rootdictLN_TBuffer;
extern G__linked_taginfo G__rootdictLN_TMemberInspector;
extern G__linked_taginfo G__rootdictLN_TObject;
extern G__linked_taginfo G__rootdictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictLN_SimpleHitState;
extern G__linked_taginfo G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__rootdictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__rootdictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__rootdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__rootdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__rootdictLN_HitState;
extern G__linked_taginfo G__rootdictLN_vectorlEHitStatecOallocatorlEHitStategRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEHitStatecOallocatorlEHitStategRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictLN_vectorlESimpleHitStatecOallocatorlESimpleHitStategRsPgR;
extern G__linked_taginfo G__rootdictLN_vectorlESimpleHitStatecOallocatorlESimpleHitStategRsPgRcLcLiterator;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlESimpleHitStatecOallocatorlESimpleHitStategRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<SimpleHitState,allocator<SimpleHitState> > G__vectorlESimpleHitStatecOallocatorlESimpleHitStategRsPgR;
