using namespace MGROOT;

//#include "MgntHitSt.h"
//#include "MgntPhySt.h"
//#include "MgntMag.h"
//#include "MgntMat.h"
//#include "MgntProp.h"
//#include "MgntProp.C"
//#include "MgntRecon.h"
//#include "MgntRecon.C"

#include "PartInfo.h"
#include "PartInfo.C"
#include "PhySt.h"
#include "PhySt.C"
#include "HitSt.h"
#include "HitSt.C"
#include "MagEnv.h"
#include "MagEnv.C"
#include "MatEnv.h"
#include "MatEnv.C"
#include "Prop.h"
#include "Prop.C"
#include "PhyTr.h"
#include "PhyTr.C"
