// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : hchou
Date           : Sat Mar 14 10:51:47 2020
Host           : Linux lcgapp-centos7-x86-64-25.cern.ch 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/h/hchou/AMSProject/apflux
Training events: 250000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
lxin                          lxin                          lxin                          lxin                          units                             'F'    [-13.6213407516,3.62821340561]
lyin                          lyin                          lyin                          lyin                          units                             'F'    [-12.6075334549,5.60300254822]
lxex                          lxex                          lxex                          lxex                          units                             'F'    [-5.39945793152,3.47817993164]
lyex                          lyex                          lyex                          lyex                          units                             'F'    [-5.38689899445,5.96375608444]
nlxin                         nlxin                         nlxin                         nlxin                         units                             'F'    [0.000393887341488,6.48450136185]
nlyin                         nlyin                         nlyin                         nlyin                         units                             'F'    [0.00157873239368,19.9187240601]
nlxex                         nlxex                         nlxex                         nlxex                         units                             'F'    [0.0568397901952,7.20413017273]
nlyex                         nlyex                         nlyex                         nlyex                         units                             'F'    [0.0753777995706,33.1219215393]
lxinC                         lxinC                         lxinC                         lxinC                         units                             'F'    [-11.7956790924,5.34278678894]
lyinC                         lyinC                         lyinC                         lyinC                         units                             'F'    [-13.0330018997,8.29169178009]
lxexC                         lxexC                         lxexC                         lxexC                         units                             'F'    [-5.98990488052,4.65408277512]
lyexC                         lyexC                         lyexC                         lyexC                         units                             'F'    [-6.09984731674,9.26662731171]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTGNode

#ifndef BDTGNode__def
#define BDTGNode__def

class BDTGNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 12 )
   {
      // the training input variables
      const char* inputVars[] = { "lxin", "lyin", "lxex", "lyex", "nlxin", "nlyin", "nlxex", "nlyex", "lxinC", "lyinC", "lxexC", "lyexC" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -36.9916152954102;
      fVmax[0] = 16.0991554260254;
      fVmin[1] = -23.3115634918213;
      fVmax[1] = 11.990514755249;
      fVmin[2] = -7.82190799713135;
      fVmax[2] = 25.4478912353516;
      fVmin[3] = -11.9930953979492;
      fVmax[3] = 18.7951183319092;
      fVmin[4] = -7.6027569770813;
      fVmax[4] = 17.9718780517578;
      fVmin[5] = -27.6613731384277;
      fVmax[5] = 27.2652435302734;
      fVmin[6] = -0.597503900527954;
      fVmax[6] = 15.8361597061157;
      fVmin[7] = -3.3253653049469;
      fVmax[7] = 73.8278503417969;
      fVmin[8] = -30.4487037658691;
      fVmax[8] = 34.2172966003418;
      fVmin[9] = -18.9261150360107;
      fVmax[9] = 28.1801795959473;
      fVmin[10] = -28.1813106536865;
      fVmax[10] = 9.20821571350098;
      fVmin[11] = -43.1375617980957;
      fVmax[11] = 18.1437511444092;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][12][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDTG::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897824,0.0795648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649053,0.0298107) , 
3, 1.97398, 1, 0, 0.849996,0.349996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0375785) , 
3, 2.36519, 1, 0, 0.742088,0.242088) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517678,0.00353555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43797,-0.012406) , 
7, 2.41043, 1, 0, 0.473722,-0.0262782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347862,-0.0304275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148001,-0.0703998) , 
11, -1.67612, 1, 0, 0.218895,-0.281105) , 
7, 3.01427, 1, 0, 0.280143,-0.219857) , 
11, -2.28335, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.935097,0.0795813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738024,0.0420368) , 
3, 1.58279, 1, 0, 0.849996,0.315065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0338702) , 
3, 2.36519, 1, 0, 0.742088,0.217932) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.738523,0.0512251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267527,-0.0408503) , 
11, -1.31063, 1, 0, 0.428197,-0.0468112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264177,-0.0429527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100389,-0.0764208) , 
9, -3.81083, 1, 0, 0.210322,-0.269153) , 
3, 1.23808, 1, 0, 0.280143,-0.197901) , 
11, -2.28335, 1, 0, 0.5,9.61427e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897824,0.0663249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649053,0.0227553) , 
3, 1.97398, 1, 0, 0.849996,0.283773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0306015) , 
3, 2.36519, 1, 0, 0.742088,0.196305) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517678,0.00744436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43797,-0.00741541) , 
7, 2.41043, 1, 0, 0.473722,-0.00371075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347862,-0.024013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148001,-0.0600118) , 
11, -1.67612, 1, 0, 0.218895,-0.233395) , 
7, 3.01427, 1, 0, 0.280143,-0.17819) , 
11, -2.28335, 1, 0, 0.5,4.61942e-05)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.935097,0.0681996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738024,0.0338834) , 
3, 1.58279, 1, 0, 0.849996,0.25569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0276952) , 
3, 2.36519, 1, 0, 0.742088,0.176902) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645719,0.0326665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259118,-0.0348192) , 
7, 3.01427, 1, 0, 0.340841,-0.099709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124616,-0.0642963) , 
3, 2.34068, 1, 0, 0.280143,-0.160491) , 
11, -2.28335, 1, 0, 0.5,8.71388e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896804,0.0589743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725557,0.0228088) , 
10, -2.07938, 1, 0, 0.849996,0.230461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.025094) , 
3, 2.36519, 1, 0, 0.742088,0.159475) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.738523,0.050551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267527,-0.0307067) , 
11, -1.31063, 1, 0, 0.428197,-0.0120032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264177,-0.0322259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100389,-0.0644152) , 
9, -3.81083, 1, 0, 0.210322,-0.207092) , 
3, 1.23808, 1, 0, 0.280143,-0.144573) , 
11, -2.28335, 1, 0, 0.5,0.000134716)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.935097,0.060635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738024,0.0265343) , 
3, 1.58279, 1, 0, 0.849996,0.207732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0227541) , 
3, 2.36519, 1, 0, 0.742088,0.143773) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645719,0.0315327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259118,-0.0294882) , 
7, 3.01427, 1, 0, 0.340841,-0.0777078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124616,-0.0558372) , 
3, 2.34068, 1, 0, 0.280143,-0.13026) , 
11, -2.28335, 1, 0, 0.5,0.000162459)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896804,0.0519379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725557,0.0167762) , 
10, -2.07938, 1, 0, 0.849996,0.187311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0206411) , 
3, 2.36519, 1, 0, 0.742088,0.129669) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711273,0.0458557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25208,-0.0286181) , 
7, 2.90533, 1, 0, 0.35477,-0.0540902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206698,-0.0365592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103643,-0.0590882) , 
11, -1.22427, 1, 0, 0.153524,-0.224767) , 
9, -3.81083, 1, 0, 0.280143,-0.117381) , 
11, -2.28335, 1, 0, 0.5,0.000199184)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897824,0.0478729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649053,0.00622837) , 
3, 1.97398, 1, 0, 0.849996,0.168887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0187278) , 
3, 2.36519, 1, 0, 0.742088,0.11694) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.738523,0.0483489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267527,-0.0234336) , 
11, -1.31063, 1, 0, 0.428197,0.00984581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30817,-0.0160645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140927,-0.0484153) , 
11, -1.70508, 1, 0, 0.210322,-0.160331) , 
3, 1.23808, 1, 0, 0.280143,-0.105796) , 
11, -2.28335, 1, 0, 0.5,0.000212344)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.908515,0.0494357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763611,0.0177238) , 
11, -2.87437, 1, 0, 0.849996,0.15231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0169918) , 
3, 2.36519, 1, 0, 0.742088,0.105488) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4877,0.0135186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206353,-0.0336394) , 
11, -1.31063, 1, 0, 0.340841,-0.0489706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124616,-0.0480751) , 
3, 2.34068, 1, 0, 0.280143,-0.0953561) , 
11, -2.28335, 1, 0, 0.5,0.000233023)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724912,0.0344991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399499,-0.0149835) , 
7, 4.02256, 1, 0, 0.634674,0.08926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510959,-0.00655934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198118,-0.0502275) , 
3, 1.61384, 1, 0, 0.321224,-0.149513) , 
10, -1.57874, 1, 0, 0.575159,0.0439246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0454704) , 
9, -3.22402, 1, 0, 0.5,0.000227771)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.935097,0.0492668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738024,0.0141101) , 
3, 1.58279, 1, 0, 0.849996,0.130874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312107,-0.0148856) , 
3, 2.36519, 1, 0, 0.742088,0.0905348) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486261,0.0156559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243595,-0.0226537) , 
3, 1.23808, 1, 0, 0.32202,-0.0446331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127381,-0.049499) , 
2, 1.68375, 1, 0, 0.280143,-0.0818922) , 
11, -2.28335, 1, 0, 0.5,0.000172303)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724912,0.0312332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399499,-0.0134158) , 
7, 4.02256, 1, 0, 0.634674,0.0783811) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510959,-0.00749128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198118,-0.0451038) , 
3, 1.61384, 1, 0, 0.321224,-0.132834) , 
10, -1.57874, 1, 0, 0.575159,0.0382781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0412839) , 
9, -3.22402, 1, 0, 0.5,0.000196944)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.903197,0.0447154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469662,-0.000530476) , 
3, 2.02076, 1, 0, 0.758239,0.110065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462094,0.0116387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220147,-0.0250667) , 
3, 1.23808, 1, 0, 0.301405,-0.0538549) , 
11, -2.14507, 1, 0, 0.550724,0.0356048) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433849,-0.0148054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18502,-0.0503909) , 
3, 1.34031, 1, 0, 0.267406,-0.162452) , 
2, 1.68375, 1, 0, 0.5,0.000145671)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768427,0.0340245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42777,-0.0122622) , 
1, 2.3473, 1, 0, 0.642399,0.0642465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172355,-0.0350726) , 
3, 2.66796, 1, 0, 0.575159,0.0334548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0375977) , 
9, -3.22402, 1, 0, 0.5,0.000182413)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680133,0.0248276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211385,-0.024523) , 
3, 2.66796, 1, 0, 0.617907,0.0714294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63904,0.00523284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20642,-0.0353637) , 
11, -2.662, 1, 0, 0.327247,-0.101007) , 
10, -1.81857, 1, 0, 0.550724,0.0315725) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433849,-0.0136785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18502,-0.0460719) , 
3, 1.34031, 1, 0, 0.267406,-0.143941) , 
2, 1.68375, 1, 0, 0.5,0.000149534)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73399,0.0284811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422512,-0.011934) , 
10, -1.81857, 1, 0, 0.663571,0.0755049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484808,-0.00713949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144522,-0.043269) , 
3, 2.02076, 1, 0, 0.356264,-0.0849348) , 
7, 4.02256, 1, 0, 0.575159,0.0293467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0343532) , 
9, -3.22402, 1, 0, 0.5,9.74471e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806933,0.0309997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458315,-0.0166085) , 
10, -1.51843, 1, 0, 0.758239,0.0872081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462094,0.011229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220147,-0.0220706) , 
3, 1.23808, 1, 0, 0.301405,-0.0436469) , 
11, -2.14507, 1, 0, 0.550724,0.0277677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357809,-0.0157369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194135,-0.0457741) , 
6, 4.00542, 1, 0, 0.267406,-0.127011) , 
2, 1.68375, 1, 0, 0.5,5.68773e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687589,0.0235103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310739,-0.0261626) , 
1, 2.67832, 1, 0, 0.62375,0.0540688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231899,-0.0353124) , 
7, 4.40082, 1, 0, 0.564937,0.0241891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.0331865) , 
3, 2.66796, 1, 0, 0.5,5.66842e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864412,0.0417866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539767,0.00371288) , 
3, 1.43438, 1, 0, 0.663571,0.0638287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484808,-0.00535754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144522,-0.0384276) , 
3, 2.02076, 1, 0, 0.356264,-0.0687191) , 
7, 4.02256, 1, 0, 0.575159,0.0256949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0314481) , 
9, -3.22402, 1, 0, 0.5,1.99635e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815095,0.029161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352338,-0.00126561) , 
11, -2.14507, 1, 0, 0.617907,0.0549683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63904,0.0060963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20642,-0.0295273) , 
11, -2.662, 1, 0, 0.327247,-0.077136) , 
10, -1.81857, 1, 0, 0.550724,0.0244338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433849,-0.0101918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18502,-0.0392356) , 
3, 1.34031, 1, 0, 0.267406,-0.111936) , 
2, 1.68375, 1, 0, 0.5,1.87728e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940769,0.0531655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860311,0.0338024) , 
3, 0.841447, 1, 0, 0.907617,0.145661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283877,-0.0106649) , 
11, -1.40373, 1, 0, 0.672851,0.0743551) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869315,0.0383838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660193,0.00691458) , 
10, -2.30398, 1, 0, 0.780678,0.0841831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414297,-0.00417536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200764,-0.0353917) , 
10, -2.21596, 1, 0, 0.331515,-0.0625772) , 
11, -2.9153, 1, 0, 0.426978,-0.0313853) , 
3, 1.20185, 1, 0, 0.5,1.85332e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690918,0.0190371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204138,-0.025721) , 
11, -0.879679, 1, 0, 0.614791,0.0416608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174271,-0.0251339) , 
3, 2.66796, 1, 0, 0.550724,0.0216651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357809,-0.0112977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194135,-0.0401473) , 
6, 4.00542, 1, 0, 0.267406,-0.0990102) , 
2, 1.68375, 1, 0, 0.5,6.00119e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818418,0.0436116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608337,0.00582687) , 
1, 1.53498, 1, 0, 0.663571,0.0535553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484808,-0.00586408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144522,-0.034605) , 
3, 2.02076, 1, 0, 0.356264,-0.0607231) , 
7, 4.02256, 1, 0, 0.575159,0.0206776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0270464) , 
9, -3.22402, 1, 0, 0.5,2.70399e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.787005,0.0244963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264739,-0.0137763) , 
11, -1.72834, 1, 0, 0.615849,0.0379215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177827,-0.0221932) , 
3, 2.66796, 1, 0, 0.553277,0.0207919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202391,-0.0361425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365312,-0.00666228) , 
8, -4.32711, 1, 0, 0.26505,-0.0916341) , 
10, -1.47451, 1, 0, 0.5,1.08216e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940769,0.0491215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860311,0.0295687) , 
3, 0.841447, 1, 0, 0.907617,0.119622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283877,-0.00590194) , 
11, -1.40373, 1, 0, 0.672851,0.0658924) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869315,0.0343215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660193,0.00592786) , 
10, -2.30398, 1, 0, 0.780678,0.0693813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414297,-0.00397818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200764,-0.0317802) , 
10, -2.21596, 1, 0, 0.331515,-0.0540591) , 
11, -2.9153, 1, 0, 0.426978,-0.0278236) , 
3, 1.20185, 1, 0, 0.5,9.1409e-06)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78318,0.0421661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600477,0.00607614) , 
7, 2.81019, 1, 0, 0.630989,0.0451761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457284,-0.000147478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225863,-0.0279564) , 
5, 4.40863, 1, 0, 0.35883,-0.0446151) , 
9, -3.76081, 1, 0, 0.550724,0.0186948) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38623,-0.00652301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196849,-0.0360588) , 
7, 3.39375, 1, 0, 0.267406,-0.0854847) , 
2, 1.68375, 1, 0, 0.5,4.30045e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972369,0.0546701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.875407,0.0312181) , 
3, 0.481054, 1, 0, 0.907617,0.107383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283877,-0.00504337) , 
11, -1.40373, 1, 0, 0.672851,0.0596479) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869315,0.0319851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660193,0.00560795) , 
10, -2.30398, 1, 0, 0.780678,0.0626984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484348,0.00454637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264639,-0.020812) , 
3, 1.79421, 1, 0, 0.331515,-0.0488753) , 
11, -2.9153, 1, 0, 0.426978,-0.0251619) , 
3, 1.20185, 1, 0, 0.5,2.57737e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.917957,0.0387043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313479,0.00088526) , 
11, -1.40373, 1, 0, 0.703029,0.0678153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581673,0.00589799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157229,-0.0253221) , 
11, -1.76914, 1, 0, 0.446642,-0.0132273) , 
3, 1.20185, 1, 0, 0.522609,0.0107854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236025,-0.0361028) , 
6, 5.66294, 1, 0, 0.5,6.12819e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653501,0.0131056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193075,-0.0161106) , 
3, 2.66796, 1, 0, 0.589739,0.0299839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237818,-0.0257517) , 
10, -0.899673, 1, 0, 0.550724,0.0165588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357809,-0.00808741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194135,-0.0351526) , 
6, 4.00542, 1, 0, 0.267406,-0.0755844) , 
2, 1.68375, 1, 0, 0.5,6.19121e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729879,0.0228416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368074,-0.0105194) , 
7, 4.02256, 1, 0, 0.618933,0.0425469) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72445,0.0059224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178257,-0.0205667) , 
11, -2.29678, 1, 0, 0.451844,-0.0260191) , 
9, -3.96708, 1, 0, 0.553277,0.0156044) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205013,-0.0312069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348168,-0.00468907) , 
4, 4.38005, 1, 0, 0.26505,-0.0686188) , 
10, -1.47451, 1, 0, 0.5,3.63751e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940769,0.042875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860311,0.022341) , 
3, 0.841447, 1, 0, 0.907617,0.0860751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283877,-0.00338853) , 
11, -1.40373, 1, 0, 0.672851,0.0488855) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760156,0.0183015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173052,-0.0223766) , 
11, -1.67489, 1, 0, 0.58753,0.0195412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334001,-0.00845749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152735,-0.0338392) , 
2, 1.22807, 1, 0, 0.271774,-0.0594477) , 
3, 2.03963, 1, 0, 0.426978,-0.020622) , 
3, 1.20185, 1, 0, 0.5,2.10105e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485192,-0.00202936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268691,-0.0312651) , 
0, 1.64211, 1, 0, 0.380094,-0.0552913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67184,0.0160478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389593,-0.00717031) , 
9, -3.76081, 1, 0, 0.593547,0.031532) , 
8, -4.61261, 1, 0, 0.550724,0.0141134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38623,-0.00285433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196849,-0.0315071) , 
7, 3.39375, 1, 0, 0.267406,-0.0645429) , 
2, 1.68375, 1, 0, 0.5,3.12095e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852126,0.047536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597913,0.024322) , 
9, -4.21577, 1, 0, 0.715451,0.0989231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929456,0.0307078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319883,-0.0167227) , 
11, -2.04021, 1, 0, 0.641616,0.00491674) , 
3, 0.57351, 1, 0, 0.672851,0.0446848) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869315,0.0280897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660193,0.00574528) , 
10, -2.30398, 1, 0, 0.780678,0.0522418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439055,0.00586734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280338,-0.0193035) , 
7, 3.2097, 1, 0, 0.331515,-0.0380464) , 
11, -2.9153, 1, 0, 0.426978,-0.0188569) , 
3, 1.20185, 1, 0, 0.5,1.43848e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648585,0.0126273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247881,-0.0259705) , 
7, 4.40082, 1, 0, 0.589964,0.0209355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155458,-0.0186998) , 
3, 2.66796, 1, 0, 0.522609,0.00844161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236025,-0.0306566) , 
6, 5.66294, 1, 0, 0.5,2.83934e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729879,0.0194234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368074,-0.00862706) , 
7, 4.02256, 1, 0, 0.618933,0.0348326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72445,0.00479399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178257,-0.0174132) , 
11, -2.29678, 1, 0, 0.451844,-0.0212666) , 
9, -3.96708, 1, 0, 0.553277,0.0127889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202391,-0.0269525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365312,-0.00259001) , 
8, -4.32711, 1, 0, 0.26505,-0.0563632) , 
10, -1.47451, 1, 0, 0.5,6.63213e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852126,0.0443089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597913,0.023477) , 
9, -4.21577, 1, 0, 0.715451,0.0899694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929456,0.0285089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319883,-0.0145249) , 
11, -2.04021, 1, 0, 0.641616,0.00513213) , 
3, 0.57351, 1, 0, 0.672851,0.0410214) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760156,0.016428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173052,-0.0197532) , 
11, -1.67489, 1, 0, 0.58753,0.0173768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334001,-0.00761717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152735,-0.0304045) , 
2, 1.22807, 1, 0, 0.271774,-0.0508896) , 
3, 2.03963, 1, 0, 0.426978,-0.0173344) , 
3, 1.20185, 1, 0, 0.5,-3.33036e-06)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541174,0.00102079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250862,-0.0250672) , 
3, 1.61384, 1, 0, 0.380094,-0.0446944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67184,0.0136727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389593,-0.00558462) , 
9, -3.76081, 1, 0, 0.593547,0.0261413) , 
8, -4.61261, 1, 0, 0.550724,0.0119302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357809,-0.00462235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194135,-0.0301579) , 
6, 4.00542, 1, 0, 0.267406,-0.054716) , 
2, 1.68375, 1, 0, 0.5,-1.7794e-06)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748512,0.0351205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669871,0.00465742) , 
3, 0.57351, 1, 0, 0.703029,0.0463842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581673,0.00474878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157229,-0.0206279) , 
11, -1.76914, 1, 0, 0.446642,-0.00959315) , 
3, 1.20185, 1, 0, 0.522609,0.00699281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236025,-0.026873) , 
6, 5.66294, 1, 0, 0.5,-1.25819e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691304,0.0121248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364049,-0.00536523) , 
9, -3.63632, 1, 0, 0.617907,0.0248276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425855,0.00845593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273703,-0.0221093) , 
0, 1.13234, 1, 0, 0.327247,-0.0365664) , 
10, -1.81857, 1, 0, 0.550724,0.010637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38623,-0.00115472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196849,-0.026929) , 
7, 3.39375, 1, 0, 0.267406,-0.0489198) , 
2, 1.68375, 1, 0, 0.5,-2.57615e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940769,0.0373658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860311,0.0182004) , 
3, 0.841447, 1, 0, 0.907617,0.0624197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283877,-0.00390124) , 
11, -1.40373, 1, 0, 0.672851,0.0336042) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544403,0.00888252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12836,-0.0237682) , 
9, -3.31542, 1, 0, 0.448687,0.00687291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459708,-0.00765291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230869,-0.033236) , 
1, 2.78798, 1, 0, 0.375794,-0.0640317) , 
1, 2.38017, 1, 0, 0.426978,-0.0142438) , 
3, 1.20185, 1, 0, 0.5,-3.34694e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687589,0.0168229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310739,-0.0221706) , 
1, 2.67832, 1, 0, 0.62375,0.0259564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231899,-0.025727) , 
7, 4.40082, 1, 0, 0.564937,0.0090277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.0165067) , 
3, 2.66796, 1, 0, 0.5,-2.73823e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485192,2.16521e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268691,-0.0249344) , 
0, 1.64211, 1, 0, 0.380094,-0.0377229) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675445,0.0221299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577033,0.00360418) , 
7, 2.81019, 1, 0, 0.593547,0.0213856) , 
8, -4.61261, 1, 0, 0.550724,0.00952721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357809,-0.00310878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194135,-0.0264064) , 
6, 4.00542, 1, 0, 0.267406,-0.0438908) , 
2, 1.68375, 1, 0, 0.5,-3.64828e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852126,0.0384552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597913,0.0193881) , 
9, -4.21577, 1, 0, 0.715451,0.0708331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929456,0.0244839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319883,-0.0133375) , 
11, -2.04021, 1, 0, 0.641616,0.00106312) , 
3, 0.57351, 1, 0, 0.672851,0.0305783) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737976,0.0265351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51714,-0.00380554) , 
7, 3.35017, 1, 0, 0.58753,0.0176024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336268,-0.0033779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220422,-0.0208568) , 
7, 3.39375, 1, 0, 0.271774,-0.0425381) , 
3, 2.03963, 1, 0, 0.426978,-0.0129771) , 
3, 1.20185, 1, 0, 0.5,-4.15447e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739596,0.0195828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278585,-0.00601677) , 
11, -1.53841, 1, 0, 0.616133,0.0357998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58533,0.000771916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234051,-0.0212109) , 
2, 1.88778, 1, 0, 0.501849,-0.0123212) , 
2, 0.709765, 1, 0, 0.553277,0.00933324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323951,-2.34491e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224864,-0.0235617) , 
2, 0.424049, 1, 0, 0.26505,-0.0413252) , 
10, -1.47451, 1, 0, 0.5,-3.05987e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637397,0.0115314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211601,-0.0161455) , 
11, -0.859058, 1, 0, 0.575953,0.0213668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654024,0.0060528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339142,-0.0123331) , 
3, 1.20185, 1, 0, 0.430617,-0.0220143) , 
2, 1.05615, 1, 0, 0.522609,0.00544417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236025,-0.0225243) , 
6, 5.66294, 1, 0, 0.5,-3.18717e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792783,0.0336753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216752,-0.00246349) , 
3, 1.96276, 1, 0, 0.582326,0.0441103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402084,-0.0211925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259491,-0.0101433) , 
3, 1.7371, 1, 0, 0.321761,-0.0449208) , 
5, 4.58242, 1, 0, 0.509982,0.0193914) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684849,0.0148939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401778,-0.0128911) , 
3, 1.86719, 1, 0, 0.549689,0.000821901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237308,-0.0266904) , 
1, 2.86481, 1, 0, 0.490754,-0.0180307) , 
1, 1.90421, 1, 0, 0.5,-3.5886e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719512,0.0217558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60738,-0.00429243) , 
7, 3.32276, 1, 0, 0.663571,0.0266422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316767,-0.0188275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403815,-0.00341306) , 
8, -4.03593, 1, 0, 0.356264,-0.0362059) , 
7, 4.02256, 1, 0, 0.575159,0.00856089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0141128) , 
9, -3.22402, 1, 0, 0.5,-2.76201e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852126,0.0361858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597913,0.0181071) , 
9, -4.21577, 1, 0, 0.715451,0.0633667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929456,0.0210987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319883,-0.0115553) , 
11, -2.04021, 1, 0, 0.641616,-0.000279547) , 
3, 0.57351, 1, 0, 0.672851,0.0266451) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83212,0.0257978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749266,0.00834744) , 
2, 0.543251, 1, 0, 0.780678,0.0405957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484348,0.00700336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264639,-0.0142017) , 
3, 1.79421, 1, 0, 0.331515,-0.0252993) , 
11, -2.9153, 1, 0, 0.426978,-0.0112942) , 
3, 1.20185, 1, 0, 0.5,-2.66028e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.835582,0.0355944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51256,0.00200743) , 
7, 3.37686, 1, 0, 0.654739,0.0409008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153972,-0.0142473) , 
9, -3.31542, 1, 0, 0.509982,0.0176914) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684849,0.0130854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401778,-0.0113562) , 
3, 1.86719, 1, 0, 0.549689,0.000520132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237308,-0.0244608) , 
1, 2.86481, 1, 0, 0.490754,-0.0164231) , 
1, 1.90421, 1, 0, 0.5,-1.87813e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633253,0.0236962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564009,0.00820158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35884,-0.00465339) , 
3, 1.65255, 1, 0, 0.457362,0.00344583) , 
0, 1.01887, 1, 0, 0.534155,0.0327687) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687536,0.0127003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321219,-0.0119808) , 
3, 1.7778, 1, 0, 0.522483,0.000563951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267571,-0.0231049) , 
5, 4.92319, 1, 0, 0.490875,-0.00877217) , 
2, 0.0994728, 1, 0, 0.5,-1.35822e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739596,0.0168941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278585,-0.00502964) , 
11, -1.53841, 1, 0, 0.616133,0.0296301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540545,0.00141059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391609,-0.0184605) , 
6, 4.67249, 1, 0, 0.501849,-0.00963653) , 
2, 0.709765, 1, 0, 0.553277,0.00803342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323951,-0.000430113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224864,-0.0211449) , 
2, 0.424049, 1, 0, 0.26505,-0.0355226) , 
10, -1.47451, 1, 0, 0.5,-1.75755e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45334,-0.00659967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595845,0.00821529) , 
8, -4.32711, 1, 0, 0.550107,0.010226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219056,-0.0215468) , 
2, 2.16591, 1, 0, 0.522609,0.00464295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236025,-0.0202291) , 
6, 5.66294, 1, 0, 0.5,-1.80312e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792783,0.0292826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216752,-0.000532437) , 
3, 1.96276, 1, 0, 0.582326,0.0371234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402084,-0.0195631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259491,-0.0085312) , 
3, 1.7371, 1, 0, 0.321761,-0.0383141) , 
5, 4.58242, 1, 0, 0.509982,0.0161787) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684849,0.0111343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401778,-0.00970086) , 
3, 1.86719, 1, 0, 0.549689,0.000281776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237308,-0.0225864) , 
1, 2.86481, 1, 0, 0.490754,-0.0150288) , 
1, 1.90421, 1, 0, 0.5,-2.23411e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719512,0.0196603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60738,-0.00368365) , 
7, 3.32276, 1, 0, 0.663571,0.0231367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316767,-0.017204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403815,-0.0036942) , 
8, -4.03593, 1, 0, 0.356264,-0.0328369) , 
7, 4.02256, 1, 0, 0.575159,0.00703322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0120182) , 
9, -3.22402, 1, 0, 0.5,-1.80732e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556579,0.00180558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411542,-0.0104136) , 
2, 0.774855, 1, 0, 0.485881,-0.0112926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263861,-0.0228231) , 
6, 4.88038, 1, 0, 0.399038,-0.0303396) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712911,0.0176679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364615,-0.00499711) , 
3, 1.7778, 1, 0, 0.554734,0.0166171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225504,-0.0266765) , 
5, 5.08333, 1, 0, 0.523892,0.00715795) , 
4, 3.3578, 1, 0, 0.5,-1.75706e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.835582,0.0311967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51256,0.00247951) , 
7, 3.37686, 1, 0, 0.654739,0.0344138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153972,-0.0121344) , 
9, -3.31542, 1, 0, 0.509982,0.0151406) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815203,0.0146662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395968,-0.00693077) , 
11, -2.71551, 1, 0, 0.549689,-0.00014131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237308,-0.0209297) , 
1, 2.86481, 1, 0, 0.490754,-0.0140637) , 
1, 1.90421, 1, 0, 0.5,-2.05355e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633253,0.0208483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564009,0.00718727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35884,-0.00416385) , 
3, 1.65255, 1, 0, 0.457362,0.00271045) , 
0, 1.01887, 1, 0, 0.534155,0.0278833) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687536,0.0103585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321219,-0.0100693) , 
3, 1.7778, 1, 0, 0.522483,-0.000200831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267571,-0.019038) , 
5, 4.92319, 1, 0, 0.490875,-0.00746742) , 
2, 0.0994728, 1, 0, 0.5,-1.39872e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739596,0.0149685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278585,-0.0048494) , 
11, -1.53841, 1, 0, 0.616133,0.0250031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572824,0.00269089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393893,-0.0124211) , 
9, -3.96708, 1, 0, 0.501849,-0.00842434) , 
2, 0.709765, 1, 0, 0.553277,0.00661797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323951,-0.000195235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224864,-0.0184441) , 
2, 0.424049, 1, 0, 0.26505,-0.0292742) , 
10, -1.47451, 1, 0, 0.5,-1.64336e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254625,-0.00440932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682316,0.0208153) , 
5, 3.047, 1, 0, 0.582326,0.0307813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402084,-0.0167034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259491,-0.00644689) , 
3, 1.7371, 1, 0, 0.321761,-0.0299352) , 
5, 4.58242, 1, 0, 0.509982,0.0139238) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599269,0.00839351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484343,-0.0111754) , 
7, 3.75737, 1, 0, 0.549689,-0.000194097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237308,-0.0194329) , 
1, 2.86481, 1, 0, 0.490754,-0.0129291) , 
1, 1.90421, 1, 0, 0.5,-1.66265e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687589,0.012375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310739,-0.0139317) , 
1, 2.67832, 1, 0, 0.62375,0.0181405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231899,-0.0206302) , 
7, 4.40082, 1, 0, 0.564937,0.00579181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.011668) , 
3, 2.66796, 1, 0, 0.5,-1.90931e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717479,0.0150576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239398,-0.0102437) , 
11, -1.49843, 1, 0, 0.583593,0.0193239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660774,0.00733564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325972,-0.0111971) , 
3, 1.4362, 1, 0, 0.455351,-0.0134429) , 
10, -2.45804, 1, 0, 0.522609,0.00374192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236025,-0.017383) , 
6, 5.66294, 1, 0, 0.5,-2.41424e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369248,0.01943) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61185,0.00778679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341269,-0.0144616) , 
5, 4.7923, 1, 0, 0.565111,0.00788799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432604,-0.00157535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316375,-0.0170334) , 
2, 0.580268, 1, 0, 0.36028,-0.0374969) , 
1, 2.46459, 1, 0, 0.511888,-0.00390475) , 
1, 0.223155, 1, 0, 0.5,-2.41338e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706237,0.02674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655479,0.00205327) , 
7, 2.62295, 1, 0, 0.663571,0.018195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316767,-0.0144828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403815,-0.00182599) , 
8, -4.03593, 1, 0, 0.356264,-0.0248813) , 
7, 4.02256, 1, 0, 0.575159,0.00580205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154522,-0.0102858) , 
9, -3.22402, 1, 0, 0.5,-2.80799e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769163,0.0162243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445189,-0.0035802) , 
3, 1.80754, 1, 0, 0.642957,0.0175946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1767,-0.0184898) , 
11, -0.879679, 1, 0, 0.564937,0.00541752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.0110644) , 
3, 2.66796, 1, 0, 0.5,-2.68877e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876431,0.0184118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526152,0.0291235) , 
7, 3.70958, 1, 0, 0.715451,0.0533006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704578,0.00534665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494774,-0.0164472) , 
5, 4.41787, 1, 0, 0.641616,-0.0065631) , 
3, 0.57351, 1, 0, 0.672851,0.0187614) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769279,0.00816355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.801376,0.0200733) , 
4, 4.61909, 1, 0, 0.780678,0.0317928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400174,-0.00177492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118079,-0.0233106) , 
11, -1.31917, 1, 0, 0.331515,-0.0186954) , 
11, -2.9153, 1, 0, 0.426978,-0.00796486) , 
3, 1.20185, 1, 0, 0.5,-2.74202e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369248,0.019216) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61185,0.00697432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341269,-0.0130559) , 
5, 4.7923, 1, 0, 0.565111,0.0068518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432604,-0.00136833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316375,-0.0157754) , 
2, 0.580268, 1, 0, 0.36028,-0.0341565) , 
1, 2.46459, 1, 0, 0.511888,-0.00380375) , 
1, 0.223155, 1, 0, 0.5,-3.44472e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514953,0.00165812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462518,-0.00766186) , 
6, 3.57591, 1, 0, 0.485881,-0.00901424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263861,-0.0196188) , 
6, 4.88038, 1, 0, 0.399038,-0.0243011) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712911,0.0146625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364615,-0.0041353) , 
3, 1.7778, 1, 0, 0.554734,0.0126719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225504,-0.0210003) , 
5, 5.08333, 1, 0, 0.523892,0.00570534) , 
4, 3.3578, 1, 0, 0.5,-3.67028e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633253,0.0179859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564009,0.00595134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35884,-0.00391215) , 
3, 1.65255, 1, 0, 0.457362,0.00133056) , 
0, 1.01887, 1, 0, 0.534155,0.0225955) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594401,0.0318781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542548,-0.00214708) , 
1, 1.01889, 1, 0, 0.552422,0.00744911) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654436,-0.00371189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144128,-0.0167422) , 
11, -2.29678, 1, 0, 0.394732,-0.0272216) , 
9, -3.96708, 1, 0, 0.490875,-0.00608306) , 
2, 0.0994728, 1, 0, 0.5,-3.64111e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729879,0.0114963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368074,-0.00551876) , 
7, 4.02256, 1, 0, 0.618933,0.016263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524181,0.00257627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393893,-0.0105437) , 
2, 0.709765, 1, 0, 0.451844,-0.0115101) , 
9, -3.96708, 1, 0, 0.553277,0.00534976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303554,-0.000719991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225524,-0.0167818) , 
9, -4.12775, 1, 0, 0.26505,-0.0238113) , 
10, -1.47451, 1, 0, 0.5,-4.04423e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687589,0.0104912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310739,-0.0109797) , 
1, 2.67832, 1, 0, 0.62375,0.0151101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231899,-0.0179537) , 
7, 4.40082, 1, 0, 0.564937,0.00477518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.00994776) , 
3, 2.66796, 1, 0, 0.5,-3.82854e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369248,0.0166071) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770426,0.0319409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537862,-0.000511753) , 
3, 0.483234, 1, 0, 0.565111,0.00574787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439807,-0.0025398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269014,-0.0163002) , 
10, -2.31027, 1, 0, 0.36028,-0.0289851) , 
1, 2.46459, 1, 0, 0.511888,-0.00327711) , 
1, 0.223155, 1, 0, 0.5,-3.95722e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633253,0.0162297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564009,0.00552176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35884,-0.00351337) , 
3, 1.65255, 1, 0, 0.457362,0.00142199) , 
0, 1.01887, 1, 0, 0.534155,0.020325) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600596,0.00332853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269198,-0.00868891) , 
9, -3.61941, 1, 0, 0.520033,0.000880611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33095,-0.016955) , 
6, 5.11473, 1, 0, 0.490875,-0.00548039) , 
2, 0.0994728, 1, 0, 0.5,-3.95203e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769163,0.0141478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445189,-0.00260074) , 
3, 1.80754, 1, 0, 0.642957,0.0152743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1767,-0.0172349) , 
11, -0.879679, 1, 0, 0.564937,0.00441773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.0092906) , 
3, 2.66796, 1, 0, 0.5,-3.86587e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369248,0.0156629) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42801,-0.00110573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274477,-0.0215944) , 
0, 1.44895, 1, 0, 0.356728,-0.0286883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656929,0.014587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539661,-0.000867373) , 
7, 2.81019, 1, 0, 0.559063,0.00470065) , 
8, -4.57996, 1, 0, 0.511888,-0.00308406) , 
1, 0.223155, 1, 0, 0.5,-3.79219e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626348,0.010694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528305,-0.00330053) , 
2, 0.778438, 1, 0, 0.593729,0.0161717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659317,0.0146397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44475,-0.00829992) , 
3, 0.84365, 1, 0, 0.48591,-0.0127149) , 
0, 1.89022, 1, 0, 0.550724,0.00464995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357809,0.0010607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194135,-0.0189718) , 
6, 4.00542, 1, 0, 0.267406,-0.0215383) , 
2, 1.68375, 1, 0, 0.5,-3.86565e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5901,0.0234882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628486,0.00202778) , 
9, -4.918, 1, 0, 0.62375,0.013491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231899,-0.0166023) , 
7, 4.40082, 1, 0, 0.564937,0.00414384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.00879158) , 
3, 2.66796, 1, 0, 0.5,-3.83854e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876431,0.0119735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526152,0.0271952) , 
7, 3.70958, 1, 0, 0.715451,0.0437217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929456,0.0110316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319883,-0.00961735) , 
11, -2.04021, 1, 0, 0.641616,-0.00666838) , 
3, 0.57351, 1, 0, 0.672851,0.0146484) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.89817,0.00954389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550717,0.0148041) , 
3, 2.03965, 1, 0, 0.780678,0.0294929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439055,0.00531064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280338,-0.0108082) , 
7, 3.2097, 1, 0, 0.331515,-0.0158906) , 
11, -2.9153, 1, 0, 0.426978,-0.00624496) , 
3, 1.20185, 1, 0, 0.5,-3.9823e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676179,0.0218159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593045,6.94947e-05) , 
1, 1.53498, 1, 0, 0.618933,0.0138247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72445,0.0021147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178257,-0.00911238) , 
11, -2.29678, 1, 0, 0.451844,-0.00986745) , 
9, -3.96708, 1, 0, 0.553277,0.00451505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303554,-9.08694e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225524,-0.0151348) , 
9, -4.12775, 1, 0, 0.26505,-0.0201313) , 
10, -1.47451, 1, 0, 0.5,-4.06483e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514953,0.00110515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462518,-0.00715877) , 
6, 3.57591, 1, 0, 0.485881,-0.00864949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263861,-0.0156765) , 
6, 4.88038, 1, 0, 0.399038,-0.0194348) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712911,0.0127865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364615,-0.00348867) , 
3, 1.7778, 1, 0, 0.554734,0.0105842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225504,-0.0191036) , 
5, 5.08333, 1, 0, 0.523892,0.0045492) , 
4, 3.3578, 1, 0, 0.5,-4.03828e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600679,0.00521692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525138,-0.0082477) , 
2, 1.26923, 1, 0, 0.589739,0.00883204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237818,-0.0125063) , 
10, -0.899673, 1, 0, 0.550724,0.00419155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357809,0.000667734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194135,-0.017306) , 
6, 4.00542, 1, 0, 0.267406,-0.0194378) , 
2, 1.68375, 1, 0, 0.5,-3.89289e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369248,0.0140925) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770426,0.0276565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537862,-0.000146818) , 
3, 0.483234, 1, 0, 0.565111,0.00542882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437354,-0.00356041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223738,-0.0157987) , 
1, 2.91821, 1, 0, 0.36028,-0.0259992) , 
1, 2.46459, 1, 0, 0.511888,-0.0027374) , 
1, 0.223155, 1, 0, 0.5,-3.87889e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798584,0.020118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601956,0.00209348) , 
7, 3.01908, 1, 0, 0.642957,0.0141051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1767,-0.0170061) , 
11, -0.879679, 1, 0, 0.564937,0.00376742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.00810526) , 
3, 2.66796, 1, 0, 0.5,-3.85819e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633253,0.0137833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564009,0.00469807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35884,-0.00268626) , 
3, 1.65255, 1, 0, 0.457362,0.00160485) , 
0, 1.01887, 1, 0, 0.534155,0.0170571) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658646,0.0061488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212684,-0.0132265) , 
11, -1.23586, 1, 0, 0.571622,0.00473337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41484,-0.00198994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220575,-0.0238427) , 
6, 4.50852, 1, 0, 0.346059,-0.0213516) , 
2, 1.30655, 1, 0, 0.490875,-0.00460453) , 
2, 0.0994728, 1, 0, 0.5,-3.73426e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876431,0.00953717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526152,0.0250618) , 
7, 3.70958, 1, 0, 0.715451,0.0386508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704578,0.00463681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494774,-0.014006) , 
5, 4.41787, 1, 0, 0.641616,-0.00520593) , 
3, 0.57351, 1, 0, 0.672851,0.013347) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.89817,0.00827088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550717,0.01396) , 
3, 2.03965, 1, 0, 0.780678,0.0264234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400174,-0.00106603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118079,-0.0207206) , 
11, -1.31917, 1, 0, 0.331515,-0.0143634) , 
11, -2.9153, 1, 0, 0.426978,-0.00569477) , 
3, 1.20185, 1, 0, 0.5,-3.95396e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369248,0.0138692) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61185,0.0051398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341269,-0.00990195) , 
5, 4.7923, 1, 0, 0.565111,0.00460563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439807,-0.00205078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269014,-0.0137599) , 
10, -2.31027, 1, 0, 0.36028,-0.023413) , 
1, 2.46459, 1, 0, 0.511888,-0.00267469) , 
1, 0.223155, 1, 0, 0.5,-4.44402e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720475,0.0102918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509439,-0.00321264) , 
10, -2.22407, 1, 0, 0.642957,0.0124118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1767,-0.0149838) , 
11, -0.879679, 1, 0, 0.564937,0.0034876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.00758673) , 
3, 2.66796, 1, 0, 0.5,-4.34761e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876431,0.00903038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526152,0.0233946) , 
7, 3.70958, 1, 0, 0.715451,0.0360944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704578,0.00431657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494774,-0.0122568) , 
5, 4.41787, 1, 0, 0.641616,-0.00418665) , 
3, 0.57351, 1, 0, 0.672851,0.0128537) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610784,0.0276261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467723,-0.00185325) , 
9, -4.55423, 1, 0, 0.504194,0.0215762) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774661,0.00785214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284382,-0.00935576) , 
11, -2.9153, 1, 0, 0.397038,-0.0159857) , 
7, 3.13205, 1, 0, 0.426978,-0.00549055) , 
3, 1.20185, 1, 0, 0.5,-4.24926e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369248,0.0130872) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42801,-0.000139415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274477,-0.0187016) , 
0, 1.44895, 1, 0, 0.356728,-0.0225421) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770297,0.00659873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295112,-0.00353024) , 
11, -2.14507, 1, 0, 0.559063,0.00358048) , 
8, -4.57996, 1, 0, 0.511888,-0.00251006) , 
1, 0.223155, 1, 0, 0.5,-4.21433e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708062,0.0175889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553228,0.00450456) , 
0, 1.06984, 1, 0, 0.629279,0.0288711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391075,-0.00127076) , 
9, -3.88399, 1, 0, 0.534155,0.0159377) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594401,0.0258268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542548,-0.00196467) , 
1, 1.01889, 1, 0, 0.552422,0.00507334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469816,-0.00334646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270065,-0.0162586) , 
2, 1.30656, 1, 0, 0.394732,-0.0189677) , 
9, -3.96708, 1, 0, 0.490875,-0.00431001) , 
2, 0.0994728, 1, 0, 0.5,-4.09315e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5901,0.0219362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628486,0.00168912) , 
9, -4.918, 1, 0, 0.62375,0.0115914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231899,-0.0150535) , 
7, 4.40082, 1, 0, 0.564937,0.00343677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.00750235) , 
3, 2.66796, 1, 0, 0.5,-3.97572e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876431,0.00748116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526152,0.0223445) , 
7, 3.70958, 1, 0, 0.715451,0.0334947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704578,0.00424873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494774,-0.0107008) , 
5, 4.41787, 1, 0, 0.641616,-0.0030062) , 
3, 0.57351, 1, 0, 0.672851,0.012435) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525455,0.00421976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357489,-0.0110027) , 
10, -2.77203, 1, 0, 0.418623,-0.0141189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452023,0.014822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454643,0.00494074) , 
5, 3.72527, 1, 0, 0.453773,0.0229397) , 
8, -3.58425, 1, 0, 0.426978,-0.00530982) , 
3, 1.20185, 1, 0, 0.5,-3.9779e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383442,8.48228e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553577,-0.00408095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306515,-0.0121876) , 
3, 1.50889, 1, 0, 0.406924,-0.0231577) , 
5, 3.72527, 1, 0, 0.399038,-0.0153196) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712911,0.0114709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364615,-0.00355594) , 
3, 1.7778, 1, 0, 0.554734,0.00851129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225504,-0.0164293) , 
5, 5.08333, 1, 0, 0.523892,0.00357567) , 
4, 3.3578, 1, 0, 0.5,-4.01301e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608333,0.0258773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675619,0.00218418) , 
1, 0.890855, 1, 0, 0.654739,0.0183005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153972,-0.00764243) , 
9, -3.31542, 1, 0, 0.509982,0.0077258) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656848,0.0086906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440115,-0.00533484) , 
3, 1.96718, 1, 0, 0.575534,0.00664879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39526,-0.00466943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337683,-0.0181368) , 
0, 2.06513, 1, 0, 0.377815,-0.0257156) , 
10, -2.31027, 1, 0, 0.490754,-0.00722876) , 
1, 1.90421, 1, 0, 0.5,-3.77088e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48157,-0.00252608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605187,0.0157619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529297,0.0045818) , 
9, -4.25462, 1, 0, 0.560745,0.0249545) , 
6, 3.66604, 1, 0, 0.534155,0.0141778) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658646,0.00546319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212684,-0.0122073) , 
11, -1.23586, 1, 0, 0.571622,0.0039362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41484,-0.00133655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220575,-0.0214104) , 
6, 4.50852, 1, 0, 0.346059,-0.0177736) , 
2, 1.30655, 1, 0, 0.490875,-0.00383547) , 
2, 0.0994728, 1, 0, 0.5,-3.74986e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769163,0.0114109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445189,-0.0020915) , 
3, 1.80754, 1, 0, 0.642957,0.0113587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1767,-0.014467) , 
11, -0.879679, 1, 0, 0.564937,0.00301736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.00667868) , 
3, 2.66796, 1, 0, 0.5,-3.85481e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.835582,0.0213829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51256,-0.000493237) , 
7, 3.37686, 1, 0, 0.654739,0.0163716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153972,-0.00621343) , 
9, -3.31542, 1, 0, 0.509982,0.00743032) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656848,0.00757525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440115,-0.00468511) , 
3, 1.96718, 1, 0, 0.575534,0.00563289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267055,-0.0154215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476101,-0.00237433) , 
8, -4.32711, 1, 0, 0.377815,-0.0237198) , 
10, -2.31027, 1, 0, 0.490754,-0.00695327) , 
1, 1.90421, 1, 0, 0.5,-3.67768e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48157,-0.00210714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605187,0.0140676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529297,0.00448017) , 
9, -4.25462, 1, 0, 0.560745,0.0226728) , 
6, 3.66604, 1, 0, 0.534155,0.013077) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731308,0.00907271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272433,6.52048e-05) , 
11, -2.14507, 1, 0, 0.506512,0.0108829) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601965,0.00432619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406986,-0.00914417) , 
7, 3.39207, 1, 0, 0.484066,-0.00981187) , 
6, 3.58309, 1, 0, 0.490875,-0.00353447) , 
2, 0.0994728, 1, 0, 0.5,-3.20743e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876431,0.00579639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526152,0.021455) , 
7, 3.70958, 1, 0, 0.715451,0.0307385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929456,0.00752217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319883,-0.00663553) , 
11, -2.04021, 1, 0, 0.641616,-0.0044217) , 
3, 0.57351, 1, 0, 0.672851,0.0104523) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610784,0.0233013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467723,-0.000611515) , 
9, -4.55423, 1, 0, 0.504194,0.019479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774661,0.0077561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284382,-0.00842072) , 
11, -2.9153, 1, 0, 0.397038,-0.0137392) , 
7, 3.13205, 1, 0, 0.426978,-0.00445775) , 
3, 1.20185, 1, 0, 0.5,-2.96099e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5901,0.0192756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628486,0.00165751) , 
9, -4.918, 1, 0, 0.62375,0.0102616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231899,-0.0140984) , 
7, 4.40082, 1, 0, 0.564937,0.0028363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149119,-0.00632167) , 
3, 2.66796, 1, 0, 0.5,-2.95535e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792783,0.0154648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216752,-0.000693688) , 
3, 1.96276, 1, 0, 0.582326,0.014502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402084,-0.0142243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259491,7.36574e-05) , 
3, 1.7371, 1, 0, 0.321761,-0.0131822) , 
5, 4.58242, 1, 0, 0.509982,0.00681567) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599269,0.00747498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484343,-0.00932999) , 
7, 3.75737, 1, 0, 0.549689,0.00045433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237308,-0.0115443) , 
1, 2.86481, 1, 0, 0.490754,-0.00637044) , 
1, 1.90421, 1, 0, 0.5,-2.97644e-05)    );
   return;
};

// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadBDTG::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 9.54682438481;
   fDecTF_1[0][0][1] = -0.132838199374;
   fDecTF_1[0][0][2] = -4.87373468024;
   fDecTF_1[0][0][3] = 0.0348922032029;
   fDecTF_1[0][0][4] = 1.08900429569;
   fDecTF_1[0][0][5] = -0.0267825562252;
   fDecTF_1[0][0][6] = -0.429567174243;
   fDecTF_1[0][0][7] = -0.0255874473482;
   fDecTF_1[0][0][8] = -8.47459455016;
   fDecTF_1[0][0][9] = 0.137236349897;
   fDecTF_1[0][0][10] = 4.43292612732;
   fDecTF_1[0][0][11] = -0.0265835202215;
   fDecTF_1[0][1][0] = -0.132838199374;
   fDecTF_1[0][1][1] = 7.117682064;
   fDecTF_1[0][1][2] = 0.00880730464017;
   fDecTF_1[0][1][3] = -3.9996541007;
   fDecTF_1[0][1][4] = -0.0104287275435;
   fDecTF_1[0][1][5] = 1.04147560116;
   fDecTF_1[0][1][6] = -0.0144707689857;
   fDecTF_1[0][1][7] = -0.321557184528;
   fDecTF_1[0][1][8] = 0.10548552038;
   fDecTF_1[0][1][9] = -5.46615293704;
   fDecTF_1[0][1][10] = 0.0204126229467;
   fDecTF_1[0][1][11] = 2.94925358887;
   fDecTF_1[0][2][0] = -4.87373468024;
   fDecTF_1[0][2][1] = 0.00880730464018;
   fDecTF_1[0][2][2] = 9.02730816686;
   fDecTF_1[0][2][3] = -0.151811755385;
   fDecTF_1[0][2][4] = 0.087024265957;
   fDecTF_1[0][2][5] = -0.0354975836888;
   fDecTF_1[0][2][6] = 0.6775243144;
   fDecTF_1[0][2][7] = -0.0322993331689;
   fDecTF_1[0][2][8] = 4.23198936098;
   fDecTF_1[0][2][9] = 0.0229644611721;
   fDecTF_1[0][2][10] = -7.54315826834;
   fDecTF_1[0][2][11] = 0.141066386718;
   fDecTF_1[0][3][0] = 0.0348922032029;
   fDecTF_1[0][3][1] = -3.9996541007;
   fDecTF_1[0][3][2] = -0.151811755385;
   fDecTF_1[0][3][3] = 7.24708430851;
   fDecTF_1[0][3][4] = -0.0309373746472;
   fDecTF_1[0][3][5] = -0.224843860989;
   fDecTF_1[0][3][6] = -0.0175993514601;
   fDecTF_1[0][3][7] = 0.414936826169;
   fDecTF_1[0][3][8] = 0.0020332693685;
   fDecTF_1[0][3][9] = 2.69009940949;
   fDecTF_1[0][3][10] = 0.12914740673;
   fDecTF_1[0][3][11] = -4.68343700689;
   fDecTF_1[0][4][0] = 1.08900429569;
   fDecTF_1[0][4][1] = -0.0104287275435;
   fDecTF_1[0][4][2] = 0.087024265957;
   fDecTF_1[0][4][3] = -0.0309373746472;
   fDecTF_1[0][4][4] = 4.15573927069;
   fDecTF_1[0][4][5] = -0.132772560136;
   fDecTF_1[0][4][6] = -1.43286796363;
   fDecTF_1[0][4][7] = 0.0149954965592;
   fDecTF_1[0][4][8] = -2.72873951471;
   fDecTF_1[0][4][9] = 0.0293768298911;
   fDecTF_1[0][4][10] = 0.144824050951;
   fDecTF_1[0][4][11] = 0.0585484622963;
   fDecTF_1[0][5][0] = -0.0267825562252;
   fDecTF_1[0][5][1] = 1.04147560116;
   fDecTF_1[0][5][2] = -0.0354975836888;
   fDecTF_1[0][5][3] = -0.224843860989;
   fDecTF_1[0][5][4] = -0.132772560136;
   fDecTF_1[0][5][5] = 4.51748674176;
   fDecTF_1[0][5][6] = 0.0307634963299;
   fDecTF_1[0][5][7] = -1.5240649188;
   fDecTF_1[0][5][8] = 0.0592983092236;
   fDecTF_1[0][5][9] = -2.81473195655;
   fDecTF_1[0][5][10] = 0.054546238219;
   fDecTF_1[0][5][11] = 0.420940074972;
   fDecTF_1[0][6][0] = -0.429567174243;
   fDecTF_1[0][6][1] = -0.0144707689857;
   fDecTF_1[0][6][2] = 0.6775243144;
   fDecTF_1[0][6][3] = -0.0175993514601;
   fDecTF_1[0][6][4] = -1.43286796363;
   fDecTF_1[0][6][5] = 0.0307634963299;
   fDecTF_1[0][6][6] = 4.04929341626;
   fDecTF_1[0][6][7] = -0.142212870512;
   fDecTF_1[0][6][8] = 0.437151389703;
   fDecTF_1[0][6][9] = 0.0300183565849;
   fDecTF_1[0][6][10] = -2.32958862958;
   fDecTF_1[0][6][11] = 0.0572045236624;
   fDecTF_1[0][7][0] = -0.0255874473482;
   fDecTF_1[0][7][1] = -0.321557184528;
   fDecTF_1[0][7][2] = -0.0322993331689;
   fDecTF_1[0][7][3] = 0.414936826169;
   fDecTF_1[0][7][4] = 0.0149954965592;
   fDecTF_1[0][7][5] = -1.5240649188;
   fDecTF_1[0][7][6] = -0.142212870512;
   fDecTF_1[0][7][7] = 4.13526782672;
   fDecTF_1[0][7][8] = 0.023583596923;
   fDecTF_1[0][7][9] = 0.211819460221;
   fDecTF_1[0][7][10] = 0.0864198364572;
   fDecTF_1[0][7][11] = -1.86196396135;
   fDecTF_1[0][8][0] = -8.47459455016;
   fDecTF_1[0][8][1] = 0.10548552038;
   fDecTF_1[0][8][2] = 4.23198936098;
   fDecTF_1[0][8][3] = 0.00203326936849;
   fDecTF_1[0][8][4] = -2.72873951471;
   fDecTF_1[0][8][5] = 0.0592983092236;
   fDecTF_1[0][8][6] = 0.437151389703;
   fDecTF_1[0][8][7] = 0.023583596923;
   fDecTF_1[0][8][8] = 10.5335678754;
   fDecTF_1[0][8][9] = -0.185570038076;
   fDecTF_1[0][8][10] = -5.00627659857;
   fDecTF_1[0][8][11] = 0.0398139258823;
   fDecTF_1[0][9][0] = 0.137236349897;
   fDecTF_1[0][9][1] = -5.46615293704;
   fDecTF_1[0][9][2] = 0.0229644611721;
   fDecTF_1[0][9][3] = 2.69009940949;
   fDecTF_1[0][9][4] = 0.0293768298911;
   fDecTF_1[0][9][5] = -2.81473195655;
   fDecTF_1[0][9][6] = 0.0300183565849;
   fDecTF_1[0][9][7] = 0.211819460221;
   fDecTF_1[0][9][8] = -0.185570038076;
   fDecTF_1[0][9][9] = 7.0219876017;
   fDecTF_1[0][9][10] = -0.0213189540824;
   fDecTF_1[0][9][11] = -2.86387684924;
   fDecTF_1[0][10][0] = 4.43292612732;
   fDecTF_1[0][10][1] = 0.0204126229467;
   fDecTF_1[0][10][2] = -7.54315826834;
   fDecTF_1[0][10][3] = 0.12914740673;
   fDecTF_1[0][10][4] = 0.144824050951;
   fDecTF_1[0][10][5] = 0.054546238219;
   fDecTF_1[0][10][6] = -2.32958862958;
   fDecTF_1[0][10][7] = 0.0864198364572;
   fDecTF_1[0][10][8] = -5.00627659857;
   fDecTF_1[0][10][9] = -0.0213189540824;
   fDecTF_1[0][10][10] = 9.72583162927;
   fDecTF_1[0][10][11] = -0.272822807742;
   fDecTF_1[0][11][0] = -0.0265835202215;
   fDecTF_1[0][11][1] = 2.94925358887;
   fDecTF_1[0][11][2] = 0.141066386718;
   fDecTF_1[0][11][3] = -4.68343700689;
   fDecTF_1[0][11][4] = 0.0585484622964;
   fDecTF_1[0][11][5] = 0.420940074972;
   fDecTF_1[0][11][6] = 0.0572045236624;
   fDecTF_1[0][11][7] = -1.86196396135;
   fDecTF_1[0][11][8] = 0.0398139258823;
   fDecTF_1[0][11][9] = -2.86387684924;
   fDecTF_1[0][11][10] = -0.272822807742;
   fDecTF_1[0][11][11] = 5.69355104428;
   fDecTF_1[1][0][0] = 5.59855553973;
   fDecTF_1[1][0][1] = -0.194556683213;
   fDecTF_1[1][0][2] = -1.35919802075;
   fDecTF_1[1][0][3] = 0.0370811684779;
   fDecTF_1[1][0][4] = 0.511780367948;
   fDecTF_1[1][0][5] = -0.120828349574;
   fDecTF_1[1][0][6] = 0.0680332529469;
   fDecTF_1[1][0][7] = 0.102534791002;
   fDecTF_1[1][0][8] = -4.49359856721;
   fDecTF_1[1][0][9] = 0.179750497391;
   fDecTF_1[1][0][10] = 1.0152193191;
   fDecTF_1[1][0][11] = -0.00981623413032;
   fDecTF_1[1][1][0] = -0.194556683213;
   fDecTF_1[1][1][1] = 4.265091342;
   fDecTF_1[1][1][2] = 0.0223592691814;
   fDecTF_1[1][1][3] = -1.65249838804;
   fDecTF_1[1][1][4] = 0.0266989752835;
   fDecTF_1[1][1][5] = 0.354531676641;
   fDecTF_1[1][1][6] = -0.0949151074119;
   fDecTF_1[1][1][7] = -0.369662212887;
   fDecTF_1[1][1][8] = 0.136566645263;
   fDecTF_1[1][1][9] = -2.8071554409;
   fDecTF_1[1][1][10] = -0.0134775200271;
   fDecTF_1[1][1][11] = 1.73576706824;
   fDecTF_1[1][2][0] = -1.35919802075;
   fDecTF_1[1][2][1] = 0.0223592691814;
   fDecTF_1[1][2][2] = 4.45664910942;
   fDecTF_1[1][2][3] = -0.0994258200266;
   fDecTF_1[1][2][4] = 0.360220518007;
   fDecTF_1[1][2][5] = -0.0646545305466;
   fDecTF_1[1][2][6] = -0.314034998162;
   fDecTF_1[1][2][7] = -0.134085923707;
   fDecTF_1[1][2][8] = 1.01453897724;
   fDecTF_1[1][2][9] = 0.0362206807965;
   fDecTF_1[1][2][10] = -2.89909494547;
   fDecTF_1[1][2][11] = 0.105341825639;
   fDecTF_1[1][3][0] = 0.0370811684779;
   fDecTF_1[1][3][1] = -1.65249838804;
   fDecTF_1[1][3][2] = -0.0994258200266;
   fDecTF_1[1][3][3] = 6.32001767537;
   fDecTF_1[1][3][4] = -0.0154986713453;
   fDecTF_1[1][3][5] = -0.351557297023;
   fDecTF_1[1][3][6] = 0.157750314773;
   fDecTF_1[1][3][7] = 0.345364364818;
   fDecTF_1[1][3][8] = 0.038595729402;
   fDecTF_1[1][3][9] = 1.36232461331;
   fDecTF_1[1][3][10] = -0.119772060344;
   fDecTF_1[1][3][11] = -3.24480036924;
   fDecTF_1[1][4][0] = 0.511780367948;
   fDecTF_1[1][4][1] = 0.0266989752835;
   fDecTF_1[1][4][2] = 0.360220518007;
   fDecTF_1[1][4][3] = -0.0154986713453;
   fDecTF_1[1][4][4] = 3.26577545289;
   fDecTF_1[1][4][5] = -0.126517978478;
   fDecTF_1[1][4][6] = -0.577465483496;
   fDecTF_1[1][4][7] = 0.0469512095675;
   fDecTF_1[1][4][8] = -2.12730814801;
   fDecTF_1[1][4][9] = 0.0166317775095;
   fDecTF_1[1][4][10] = -0.21336264522;
   fDecTF_1[1][4][11] = 0.0355346720008;
   fDecTF_1[1][5][0] = -0.120828349574;
   fDecTF_1[1][5][1] = 0.354531676641;
   fDecTF_1[1][5][2] = -0.0646545305466;
   fDecTF_1[1][5][3] = -0.351557297023;
   fDecTF_1[1][5][4] = -0.126517978478;
   fDecTF_1[1][5][5] = 2.40379183467;
   fDecTF_1[1][5][6] = 0.0509506071857;
   fDecTF_1[1][5][7] = -1.13648964786;
   fDecTF_1[1][5][8] = 0.171870467213;
   fDecTF_1[1][5][9] = -1.55820098598;
   fDecTF_1[1][5][10] = 0.0624681366005;
   fDecTF_1[1][5][11] = 0.46235310288;
   fDecTF_1[1][6][0] = 0.0680332529469;
   fDecTF_1[1][6][1] = -0.0949151074119;
   fDecTF_1[1][6][2] = -0.314034998162;
   fDecTF_1[1][6][3] = 0.157750314773;
   fDecTF_1[1][6][4] = -0.577465483496;
   fDecTF_1[1][6][5] = 0.0509506071857;
   fDecTF_1[1][6][6] = 2.72052005545;
   fDecTF_1[1][6][7] = -0.171177301448;
   fDecTF_1[1][6][8] = -0.138538720199;
   fDecTF_1[1][6][9] = 0.0404593941275;
   fDecTF_1[1][6][10] = -1.12978001279;
   fDecTF_1[1][6][11] = -0.0287314066535;
   fDecTF_1[1][7][0] = 0.102534791002;
   fDecTF_1[1][7][1] = -0.369662212887;
   fDecTF_1[1][7][2] = -0.134085923707;
   fDecTF_1[1][7][3] = 0.345364364818;
   fDecTF_1[1][7][4] = 0.0469512095675;
   fDecTF_1[1][7][5] = -1.13648964786;
   fDecTF_1[1][7][6] = -0.171177301448;
   fDecTF_1[1][7][7] = 2.29307541166;
   fDecTF_1[1][7][8] = -0.108540100029;
   fDecTF_1[1][7][9] = 0.779096444766;
   fDecTF_1[1][7][10] = 0.272078900094;
   fDecTF_1[1][7][11] = -1.37321961089;
   fDecTF_1[1][8][0] = -4.49359856721;
   fDecTF_1[1][8][1] = 0.136566645263;
   fDecTF_1[1][8][2] = 1.01453897724;
   fDecTF_1[1][8][3] = 0.038595729402;
   fDecTF_1[1][8][4] = -2.12730814801;
   fDecTF_1[1][8][5] = 0.171870467213;
   fDecTF_1[1][8][6] = -0.138538720199;
   fDecTF_1[1][8][7] = -0.108540100029;
   fDecTF_1[1][8][8] = 6.17433889193;
   fDecTF_1[1][8][9] = -0.292989992811;
   fDecTF_1[1][8][10] = -1.29077424593;
   fDecTF_1[1][8][11] = 0.015440229705;
   fDecTF_1[1][9][0] = 0.179750497391;
   fDecTF_1[1][9][1] = -2.8071554409;
   fDecTF_1[1][9][2] = 0.0362206807965;
   fDecTF_1[1][9][3] = 1.36232461331;
   fDecTF_1[1][9][4] = 0.0166317775095;
   fDecTF_1[1][9][5] = -1.55820098598;
   fDecTF_1[1][9][6] = 0.0404593941275;
   fDecTF_1[1][9][7] = 0.779096444766;
   fDecTF_1[1][9][8] = -0.292989992811;
   fDecTF_1[1][9][9] = 3.74968540878;
   fDecTF_1[1][9][10] = 0.00955018338899;
   fDecTF_1[1][9][11] = -2.19409817685;
   fDecTF_1[1][10][0] = 1.0152193191;
   fDecTF_1[1][10][1] = -0.0134775200271;
   fDecTF_1[1][10][2] = -2.89909494547;
   fDecTF_1[1][10][3] = -0.119772060344;
   fDecTF_1[1][10][4] = -0.21336264522;
   fDecTF_1[1][10][5] = 0.0624681366005;
   fDecTF_1[1][10][6] = -1.12978001279;
   fDecTF_1[1][10][7] = 0.272078900094;
   fDecTF_1[1][10][8] = -1.29077424593;
   fDecTF_1[1][10][9] = 0.00955018338899;
   fDecTF_1[1][10][10] = 4.30175848778;
   fDecTF_1[1][10][11] = -0.129757659361;
   fDecTF_1[1][11][0] = -0.00981623413032;
   fDecTF_1[1][11][1] = 1.73576706824;
   fDecTF_1[1][11][2] = 0.105341825639;
   fDecTF_1[1][11][3] = -3.24480036924;
   fDecTF_1[1][11][4] = 0.0355346720008;
   fDecTF_1[1][11][5] = 0.46235310288;
   fDecTF_1[1][11][6] = -0.0287314066535;
   fDecTF_1[1][11][7] = -1.37321961089;
   fDecTF_1[1][11][8] = 0.015440229705;
   fDecTF_1[1][11][9] = -2.19409817685;
   fDecTF_1[1][11][10] = -0.129757659361;
   fDecTF_1[1][11][11] = 4.30991060656;
   fDecTF_1[2][0][0] = 7.60299063374;
   fDecTF_1[2][0][1] = -0.179193237028;
   fDecTF_1[2][0][2] = -2.95626177299;
   fDecTF_1[2][0][3] = -0.0334155546492;
   fDecTF_1[2][0][4] = 0.806237706787;
   fDecTF_1[2][0][5] = -0.0307202409155;
   fDecTF_1[2][0][6] = -0.0678150166427;
   fDecTF_1[2][0][7] = 0.0545304545437;
   fDecTF_1[2][0][8] = -6.49484602471;
   fDecTF_1[2][0][9] = 0.155723854415;
   fDecTF_1[2][0][10] = 2.45312480766;
   fDecTF_1[2][0][11] = 0.00954543583733;
   fDecTF_1[2][1][0] = -0.179193237028;
   fDecTF_1[2][1][1] = 5.70494561753;
   fDecTF_1[2][1][2] = 0.0620872946188;
   fDecTF_1[2][1][3] = -3.28686146894;
   fDecTF_1[2][1][4] = -0.00362360352611;
   fDecTF_1[2][1][5] = 0.814888962593;
   fDecTF_1[2][1][6] = -0.0409828894391;
   fDecTF_1[2][1][7] = -0.470419327341;
   fDecTF_1[2][1][8] = 0.140537612196;
   fDecTF_1[2][1][9] = -4.1498677333;
   fDecTF_1[2][1][10] = -0.018009543831;
   fDecTF_1[2][1][11] = 2.55897386782;
   fDecTF_1[2][2][0] = -2.95626177299;
   fDecTF_1[2][2][1] = 0.0620872946188;
   fDecTF_1[2][2][2] = 6.64490757323;
   fDecTF_1[2][2][3] = -0.0904282552458;
   fDecTF_1[2][2][4] = 0.337210231258;
   fDecTF_1[2][2][5] = -0.11168548645;
   fDecTF_1[2][2][6] = 0.116593267598;
   fDecTF_1[2][2][7] = -0.144951759589;
   fDecTF_1[2][2][8] = 2.3686964383;
   fDecTF_1[2][2][9] = 0.0512866653866;
   fDecTF_1[2][2][10] = -5.08117099033;
   fDecTF_1[2][2][11] = 0.0657664071916;
   fDecTF_1[2][3][0] = -0.0334155546492;
   fDecTF_1[2][3][1] = -3.28686146894;
   fDecTF_1[2][3][2] = -0.0904282552458;
   fDecTF_1[2][3][3] = 6.39230430551;
   fDecTF_1[2][3][4] = -0.044810274236;
   fDecTF_1[2][3][5] = -0.0707128468605;
   fDecTF_1[2][3][6] = 0.056082276701;
   fDecTF_1[2][3][7] = 0.300823307047;
   fDecTF_1[2][3][8] = 0.137638998204;
   fDecTF_1[2][3][9] = 2.22694250118;
   fDecTF_1[2][3][10] = -0.0745137679256;
   fDecTF_1[2][3][11] = -4.12263629813;
   fDecTF_1[2][4][0] = 0.806237706787;
   fDecTF_1[2][4][1] = -0.00362360352611;
   fDecTF_1[2][4][2] = 0.337210231258;
   fDecTF_1[2][4][3] = -0.044810274236;
   fDecTF_1[2][4][4] = 3.83558803042;
   fDecTF_1[2][4][5] = -0.127022739956;
   fDecTF_1[2][4][6] = -1.09086658699;
   fDecTF_1[2][4][7] = 0.0399545689907;
   fDecTF_1[2][4][8] = -2.45670273401;
   fDecTF_1[2][4][9] = 0.01532920749;
   fDecTF_1[2][4][10] = -0.107138383065;
   fDecTF_1[2][4][11] = 0.0832570581953;
   fDecTF_1[2][5][0] = -0.0307202409155;
   fDecTF_1[2][5][1] = 0.814888962593;
   fDecTF_1[2][5][2] = -0.11168548645;
   fDecTF_1[2][5][3] = -0.0707128468605;
   fDecTF_1[2][5][4] = -0.127022739956;
   fDecTF_1[2][5][5] = 3.47159195766;
   fDecTF_1[2][5][6] = 0.0204981783375;
   fDecTF_1[2][5][7] = -1.38032763018;
   fDecTF_1[2][5][8] = 0.0421010188998;
   fDecTF_1[2][5][9] = -2.27265828519;
   fDecTF_1[2][5][10] = 0.161348994213;
   fDecTF_1[2][5][11] = 0.404436650117;
   fDecTF_1[2][6][0] = -0.0678150166427;
   fDecTF_1[2][6][1] = -0.0409828894391;
   fDecTF_1[2][6][2] = 0.116593267598;
   fDecTF_1[2][6][3] = 0.056082276701;
   fDecTF_1[2][6][4] = -1.09086658699;
   fDecTF_1[2][6][5] = 0.0204981783375;
   fDecTF_1[2][6][6] = 3.52698605359;
   fDecTF_1[2][6][7] = -0.172808542985;
   fDecTF_1[2][6][8] = 0.0762752485938;
   fDecTF_1[2][6][9] = 0.0486287130912;
   fDecTF_1[2][6][10] = -1.71618856166;
   fDecTF_1[2][6][11] = -0.00695423949048;
   fDecTF_1[2][7][0] = 0.0545304545437;
   fDecTF_1[2][7][1] = -0.470419327341;
   fDecTF_1[2][7][2] = -0.144951759589;
   fDecTF_1[2][7][3] = 0.300823307047;
   fDecTF_1[2][7][4] = 0.0399545689907;
   fDecTF_1[2][7][5] = -1.38032763018;
   fDecTF_1[2][7][6] = -0.172808542985;
   fDecTF_1[2][7][7] = 3.25121654369;
   fDecTF_1[2][7][8] = -0.0394571501911;
   fDecTF_1[2][7][9] = 0.611058382642;
   fDecTF_1[2][7][10] = 0.195954259148;
   fDecTF_1[2][7][11] = -1.6425996067;
   fDecTF_1[2][8][0] = -6.49484602471;
   fDecTF_1[2][8][1] = 0.140537612196;
   fDecTF_1[2][8][2] = 2.3686964383;
   fDecTF_1[2][8][3] = 0.137638998204;
   fDecTF_1[2][8][4] = -2.45670273401;
   fDecTF_1[2][8][5] = 0.0421010188998;
   fDecTF_1[2][8][6] = 0.0762752485938;
   fDecTF_1[2][8][7] = -0.0394571501911;
   fDecTF_1[2][8][8] = 8.39091838576;
   fDecTF_1[2][8][9] = -0.228700407466;
   fDecTF_1[2][8][10] = -2.88237213108;
   fDecTF_1[2][8][11] = 0.0174498048654;
   fDecTF_1[2][9][0] = 0.155723854415;
   fDecTF_1[2][9][1] = -4.1498677333;
   fDecTF_1[2][9][2] = 0.0512866653866;
   fDecTF_1[2][9][3] = 2.22694250118;
   fDecTF_1[2][9][4] = 0.01532920749;
   fDecTF_1[2][9][5] = -2.27265828519;
   fDecTF_1[2][9][6] = 0.0486287130912;
   fDecTF_1[2][9][7] = 0.611058382642;
   fDecTF_1[2][9][8] = -0.228700407466;
   fDecTF_1[2][9][9] = 5.4186571768;
   fDecTF_1[2][9][10] = -0.0378172615548;
   fDecTF_1[2][9][11] = -2.66041474522;
   fDecTF_1[2][10][0] = 2.45312480766;
   fDecTF_1[2][10][1] = -0.018009543831;
   fDecTF_1[2][10][2] = -5.08117099033;
   fDecTF_1[2][10][3] = -0.0745137679256;
   fDecTF_1[2][10][4] = -0.107138383065;
   fDecTF_1[2][10][5] = 0.161348994213;
   fDecTF_1[2][10][6] = -1.71618856166;
   fDecTF_1[2][10][7] = 0.195954259148;
   fDecTF_1[2][10][8] = -2.88237213108;
   fDecTF_1[2][10][9] = -0.0378172615548;
   fDecTF_1[2][10][10] = 6.90331543843;
   fDecTF_1[2][10][11] = -0.218106457742;
   fDecTF_1[2][11][0] = 0.00954543583733;
   fDecTF_1[2][11][1] = 2.55897386782;
   fDecTF_1[2][11][2] = 0.0657664071916;
   fDecTF_1[2][11][3] = -4.12263629813;
   fDecTF_1[2][11][4] = 0.0832570581953;
   fDecTF_1[2][11][5] = 0.404436650117;
   fDecTF_1[2][11][6] = -0.00695423949048;
   fDecTF_1[2][11][7] = -1.6425996067;
   fDecTF_1[2][11][8] = 0.0174498048654;
   fDecTF_1[2][11][9] = -2.66041474522;
   fDecTF_1[2][11][10] = -0.218106457742;
   fDecTF_1[2][11][11] = 5.06450337529;
}

//_______________________________________________________________________
inline void ReadBDTG::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   }

   std::vector<double> tv;
   for (int i=0; i<12;i++) {
      double v = 0;
      for (int j=0; j<12; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<12;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadBDTG::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadBDTG::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
