// Class: ReadBDTD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTD
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : hchou
Date           : Fri Mar 13 17:48:35 2020
Host           : Linux lcgapp-centos7-x86-64-25.cern.ch 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/h/hchou/AMSProject/apflux
Training events: 250000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
lxin                          lxin                          lxin                          lxin                          units                             'F'    [-14.313117981,3.63619494438]
lyin                          lyin                          lyin                          lyin                          units                             'F'    [-8.29461574554,6.13294172287]
lxex                          lxex                          lxex                          lxex                          units                             'F'    [-9.54836368561,3.47817993164]
lyex                          lyex                          lyex                          lyex                          units                             'F'    [-5.62161397934,5.97065973282]
nlxin                         nlxin                         nlxin                         nlxin                         units                             'F'    [0.000644195941277,6.8876285553]
nlyin                         nlyin                         nlyin                         nlyin                         units                             'F'    [0.0193728767335,20.8976020813]
nlxex                         nlxex                         nlxex                         nlxex                         units                             'F'    [0.00876429025084,7.83990812302]
nlyex                         nlyex                         nlyex                         nlyex                         units                             'F'    [0.0759664475918,37.5671310425]
lyinC                         lyinC                         lyinC                         lyinC                         units                             'F'    [-8.83702659607,7.79565906525]
lyexC                         lyexC                         lyexC                         lyexC                         units                             'F'    [-6.42896032333,9.77897167206]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTDNode

#ifndef BDTDNode__def
#define BDTDNode__def

class BDTDNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTDNode ( BDTDNode* left,BDTDNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTDNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTDNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTDNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTDNode*   fLeft;     // pointer to the left daughter node
   BDTDNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTDNode::~BDTDNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTDNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTDNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTD : public IClassifierReader {

 public:

   // constructor
   ReadBDTD( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDTD" ),
        fNvars( 10 )
   {
      // the training input variables
      const char* inputVars[] = { "lxin", "lyin", "lxex", "lyex", "nlxin", "nlyin", "nlxex", "nlyex", "lyinC", "lyexC" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -30.0537071228027;
      fVmax[0] = 1.21732711791992;
      fVmin[1] = -22.0314311981201;
      fVmax[1] = 8.51880931854248;
      fVmin[2] = -15.4012594223022;
      fVmax[2] = 10.0851240158081;
      fVmin[3] = -7.20114850997925;
      fVmax[3] = 10.8160371780396;
      fVmin[4] = -3.96100425720215;
      fVmax[4] = 13.2719650268555;
      fVmin[5] = -27.7029151916504;
      fVmax[5] = 25.5147380828857;
      fVmin[6] = -0.326755046844482;
      fVmax[6] = 14.5486631393433;
      fVmin[7] = -0.846426248550415;
      fVmax[7] = 92.7395172119141;
      fVmin[8] = -29.9176654815674;
      fVmax[8] = 29.6979122161865;
      fVmin[9] = -38.8476905822754;
      fVmax[9] = 8.17418384552002;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadBDTD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][10][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTDNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTD::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTDNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTDNode*)current->GetRight();
         else current=(BDTDNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDTD::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.615990192516361);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.77934, 1, 1, 0.89613,-99) , 
NN(
0, 
0, 
-1, 2.13965, 0, -1, 0.428609,-99) , 
3, 2.1543, 1, 0, 0.769053,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331651,-99) , 
3, 1.74458, 1, 0, 0.5394,-99) , 
NN(
0, 
0, 
-1, -2.35923, 1, -1, 0.243619,-99) , 
7, 3.89046, 1, 0, 0.308188,-99) , 
9, -3.0215, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.489051);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.36687, 1, 1, 0.746176,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289733,-99) , 
3, 2.16152, 1, 0, 0.521448,-99) , 
NN(
0, 
0, 
-1, 0.783158, 1, -1, 0.265942,-99) , 
9, -1.95523, 1, 0, 0.416274,-99) , 
9, -3.0215, 1, 0, 0.550275,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.373075);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473418,-99) , 
1, 2.70381, 1, 0, 0.706722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261688,-99) , 
2, -0.510865, 1, 0, 0.463975,-99) , 
3, 1.80853, 1, 0, 0.583047,-99) , 
NN(
0, 
0, 
-1, 1.46828, 1, -1, 0.27636,-99) , 
8, -4.36813, 1, 0, 0.52734,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.32833);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.94945, 1, 1, 0.694873,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336922,-99) , 
3, 2.56582, 1, 0, 0.512695,-99) , 
NN(
0, 
0, 
-1, -2.56737, 1, -1, 0.297868,-99) , 
7, 4.96523, 1, 0, 0.434617,-99) , 
3, 1.37846, 1, 0, 0.516835,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.281098);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.73901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413838,-99) , 
9, -2.05285, 1, 0, 0.617821,-99) , 
NN(
0, 
0, 
-1, 5.29079, 1, -1, 0.435397,-99) , 
3, 1.80853, 1, 0, 0.525421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232883,-99) , 
2, 0.376026, 1, 0, 0.496278,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.264686);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -4.84076, 1, 1, 0.692491,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424538,-99) , 
9, -2.1792, 1, 0, 0.541527,-99) , 
7, 4.48839, 1, 0, 0.600915,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439374,-99) , 
9, -3.34854, 1, 0, 0.496972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.275784,-99) , 
6, 3.52453, 1, 0, 0.43286,-99) , 
2, -0.837612, 1, 0, 0.528255,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.247706);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.756516,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448666,-99) , 
7, 4.48839, 1, 0, 0.530945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324216,-99) , 
8, -4.36813, 1, 0, 0.49716,-99) , 
3, 0.520503, 1, 0, 0.524789,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.207632);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.94945, 1, 1, 0.640904,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402992,-99) , 
3, 2.72669, 1, 0, 0.529301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358516,-99) , 
9, -2.17887, 1, 0, 0.490657,-99) , 
3, 1.37846, 1, 0, 0.536582,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.191992);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.989467, 1, 1, 0.585713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367499,-99) , 
9, -2.75319, 1, 0, 0.459388,-99) , 
8, -5.06087, 1, 0, 0.534145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309534,-99) , 
2, 0.376026, 1, 0, 0.512744,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.137281);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.94945, 1, 1, 0.606875,-99) , 
NN(
0, 
0, 
-1, -0.0583173, 1, -1, 0.466822,-99) , 
3, 1.37846, 1, 0, 0.508643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286136,-99) , 
6, 4.63172, 1, 0, 0.490375,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.145324);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422661,-99) , 
9, -2.17887, 1, 0, 0.509099,-99) , 
3, 0.520503, 1, 0, 0.524342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31845,-99) , 
4, 0.962701, 0, 0, 0.505912,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.148167);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488766,-99) , 
8, -5.06087, 1, 0, 0.540528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333321,-99) , 
6, 2.30421, 1, 0, 0.409782,-99) , 
2, -0.173538, 1, 0, 0.515692,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313138,-99) , 
4, 3.40573, 0, 0, 0.377325,-99) , 
6, 3.92336, 1, 0, 0.491875,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.177456);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408899,-99) , 
7, 5.461, 1, 0, 0.539329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39852,-99) , 
3, 2.94174, 1, 0, 0.51953,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397114,-99) , 
3, 1.89376, 1, 0, 0.464231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325275,-99) , 
6, 3.21501, 1, 0, 0.416023,-99) , 
1, 2.69972, 1, 0, 0.490553,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.1061);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611733,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391201,-99) , 
2, -0.160998, 1, 0, 0.489165,-99) , 
NN(
0, 
0, 
-1, 2.73603, 0, -1, 0.371848,-99) , 
6, 3.92336, 1, 0, 0.469478,-99) , 
3, 0.520503, 1, 0, 0.483405,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.119306);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 5.59545, 1, 1, 0.57428,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571213,-99) , 
NN(
0, 
0, 
-1, -2.56737, 1, -1, 0.444378,-99) , 
3, 0.579445, 1, 0, 0.45823,-99) , 
7, 3.61005, 1, 0, 0.472237,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.122036);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416672,-99) , 
5, 6.27844, 1, 0, 0.516084,-99) , 
NN(
0, 
0, 
-1, 2.50652, 1, -1, 0.418914,-99) , 
2, -0.128134, 1, 0, 0.498681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373465,-99) , 
6, 4.63172, 1, 0, 0.489037,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.150322);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39406,-99) , 
7, 5.53349, 1, 0, 0.524284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403971,-99) , 
8, -3.99697, 1, 0, 0.50349,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474587,-99) , 
2, -1.06484, 1, 0, 0.498553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369855,-99) , 
1, 2.97682, 1, 0, 0.428297,-99) , 
1, 2.69972, 1, 0, 0.482485,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.139847);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.692459,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463778,-99) , 
4, 2.26359, 0, 0, 0.481391,-99) , 
8, -6.1029, 1, 0, 0.545447,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430597,-99) , 
9, -1.82494, 1, 0, 0.528216,-99) , 
NN(
0, 
0, 
-1, 3.21501, 1, -1, 0.436308,-99) , 
3, 1.44918, 1, 0, 0.464994,-99) , 
1, 1.24494, 1, 0, 0.479526,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0911672);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.29453, 1, 1, 0.56798,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479363,-99) , 
7, 4.48839, 1, 0, 0.500979,-99) , 
3, 1.09833, 1, 0, 0.514509,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470508,-99) , 
3, 1.30942, 1, 0, 0.50233,-99) , 
NN(
0, 
0, 
-1, 2.10839, 1, -1, 0.403487,-99) , 
2, -0.837612, 1, 0, 0.45678,-99) , 
6, 3.21501, 1, 0, 0.495363,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0811161);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.22708, 1, 1, 0.559186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557479,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434623,-99) , 
9, -2.56737, 1, 0, 0.485272,-99) , 
3, 0.520503, 1, 0, 0.492251,-99) , 
2, -2.05125, 1, 0, 0.499776,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0753374);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674567,-99) , 
NN(
0, 
0, 
-1, 1.3463, 0, -1, 0.477005,-99) , 
8, -6.1029, 1, 0, 0.536218,-99) , 
NN(
NN(
0, 
0, 
-1, -5.10394, 1, 1, 0.548963,-99) , 
NN(
0, 
0, 
-1, 2.97683, 1, -1, 0.472036,-99) , 
3, 0.872494, 1, 0, 0.482334,-99) , 
1, 1.24494, 1, 0, 0.492098,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0764018);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.69937, 1, 1, 0.530847,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422275,-99) , 
9, -2.94553, 1, 0, 0.477619,-99) , 
5, 6.17774, 1, 0, 0.518355,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479174,-99) , 
8, -5.0688, 1, 0, 0.506983,-99) , 
NN(
0, 
0, 
-1, 2.57349, 1, -1, 0.448168,-99) , 
5, 5.54252, 1, 0, 0.476464,-99) , 
4, 1.78332, 0, 0, 0.504765,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0678615);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57379,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458038,-99) , 
1, 2.9079, 1, 0, 0.503966,-99) , 
1, 0.663518, 1, 0, 0.510841,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483819,-99) , 
2, -1.53119, 1, 0, 0.509344,-99) , 
NN(
0, 
0, 
-1, 2.10839, 1, -1, 0.427396,-99) , 
2, -0.837612, 1, 0, 0.471612,-99) , 
6, 3.21501, 1, 0, 0.497876,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0753831);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484472,-99) , 
7, 3.1856, 1, 0, 0.539221,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466927,-99) , 
3, 2.04386, 1, 0, 0.502023,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403659,-99) , 
6, 2.88265, 1, 0, 0.457953,-99) , 
2, -0.573301, 1, 0, 0.488156,-99) , 
7, 3.61005, 1, 0, 0.494297,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0610267);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.1856, 1, 1, 0.541767,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475614,-99) , 
3, 1.36687, 0, 0, 0.53142,-99) , 
NN(
0, 
0, 
-1, -0.573301, 1, -1, 0.475245,-99) , 
1, 1.24494, 1, 0, 0.485398,-99) , 
7, 3.61005, 1, 0, 0.492168,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0645613);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 5.4525, 0, 1, 0.540247,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466197,-99) , 
5, 6.23504, 1, 0, 0.506866,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434731,-99) , 
8, -5.76013, 1, 0, 0.46388,-99) , 
2, -0.317453, 1, 0, 0.495502,-99) , 
2, -2.05125, 1, 0, 0.500543,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.03867);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 5.4525, 0, 1, 0.524175,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488864,-99) , 
3, 0.828987, 1, 0, 0.495838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452783,-99) , 
2, 0.260468, 1, 0, 0.490707,-99) , 
2, -2.05125, 1, 0, 0.494476,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.059004);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490301,-99) , 
7, 3.1856, 1, 0, 0.529027,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499281,-99) , 
9, -3.92533, 1, 0, 0.510791,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36652,-99) , 
9, -1.30613, 1, 0, 0.459215,-99) , 
9, -2.1792, 1, 0, 0.495771,-99) , 
7, 3.61005, 1, 0, 0.499755,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0847154);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 6.14954, 0, 1, 0.53688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45865,-99) , 
6, 2.62902, 1, 0, 0.489534,-99) , 
2, -0.573301, 1, 0, 0.521152,-99) , 
NN(
NN(
0, 
0, 
-1, 1.44901, 1, 1, 0.528368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398888,-99) , 
9, -1.42211, 1, 0, 0.497627,-99) , 
9, -3.0215, 1, 0, 0.506907,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0901984);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616953,-99) , 
NN(
0, 
0, 
-1, 2.84001, 0, -1, 0.47811,-99) , 
8, -6.1029, 1, 0, 0.519391,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471945,-99) , 
9, -3.44831, 1, 0, 0.499925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443551,-99) , 
1, 2.97682, 1, 0, 0.489662,-99) , 
1, 1.24494, 1, 0, 0.495022,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0421746);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543821,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497952,-99) , 
9, -3.64735, 1, 0, 0.510579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445288,-99) , 
3, 2.97189, 1, 0, 0.503225,-99) , 
3, 0.520503, 1, 0, 0.507089,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0590046);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.1856, 1, 1, 0.548228,-99) , 
NN(
NN(
0, 
0, 
-1, -3.92533, 1, 1, 0.521031,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420012,-99) , 
9, -1.30613, 1, 0, 0.477888,-99) , 
9, -2.1792, 1, 0, 0.50854,-99) , 
7, 3.61005, 1, 0, 0.513297,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0551723);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.1856, 1, 1, 0.533576,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479706,-99) , 
9, -2.45812, 1, 0, 0.515501,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472131,-99) , 
2, -1.63982, 1, 0, 0.484664,-99) , 
0, -1.20089, 0, 0, 0.497176,-99) , 
7, 3.61005, 1, 0, 0.501534,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0513249);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595718,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48202,-99) , 
6, 2.84001, 0, 0, 0.498442,-99) , 
8, -6.1029, 1, 0, 0.527247,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439822,-99) , 
1, 3.11449, 1, 0, 0.502042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45754,-99) , 
3, 2.60256, 1, 0, 0.496017,-99) , 
1, 1.24494, 1, 0, 0.501651,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0495429);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481458,-99) , 
4, 2.26359, 1, 0, 0.499347,-99) , 
8, -6.1029, 1, 0, 0.524137,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479198,-99) , 
9, -2.36016, 1, 0, 0.512649,-99) , 
NN(
0, 
0, 
-1, 3.33414, 1, -1, 0.479564,-99) , 
4, 2.60394, 0, 0, 0.489803,-99) , 
1, 1.24494, 1, 0, 0.495992,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.054985);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540071,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486479,-99) , 
3, 2.15475, 0, 0, 0.503976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442691,-99) , 
3, 2.97189, 1, 0, 0.497044,-99) , 
3, 0.520503, 1, 0, 0.50113,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0570912);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54281,-99) , 
NN(
NN(
0, 
0, 
-1, -6.32297, 1, 1, 0.517058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417497,-99) , 
7, 5.67398, 1, 0, 0.501611,-99) , 
6, 1.7983, 1, 0, 0.50505,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0482216);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528611,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49317,-99) , 
8, -6.32297, 1, 0, 0.502792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431443,-99) , 
7, 5.67398, 1, 0, 0.491757,-99) , 
6, 1.7983, 1, 0, 0.494831,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0372581);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481432,-99) , 
1, 0.609396, 1, 0, 0.494086,-99) , 
2, -0.766297, 0, 0, 0.523152,-99) , 
NN(
NN(
0, 
0, 
-1, 0.488034, 0, 1, 0.537783,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461379,-99) , 
3, 2.41034, 1, 0, 0.493425,-99) , 
3, 0.872494, 1, 0, 0.499247,-99) , 
1, 1.24494, 1, 0, 0.503533,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0434231);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484247,-99) , 
3, 1.3463, 0, 0, 0.498805,-99) , 
8, -6.1029, 1, 0, 0.5196,-99) , 
NN(
NN(
0, 
0, 
-1, 0.488034, 0, 1, 0.52851,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481422,-99) , 
1, 1.93771, 1, 0, 0.488516,-99) , 
3, 0.872494, 1, 0, 0.493761,-99) , 
1, 1.24494, 1, 0, 0.498391,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0531792);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475798,-99) , 
8, -5.15117, 1, 0, 0.519729,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494004,-99) , 
8, -5.48057, 1, 0, 0.521113,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406011,-99) , 
7, 5.67398, 1, 0, 0.492938,-99) , 
0, -0.811533, 0, 0, 0.498518,-99) , 
4, 3.42455, 0, 0, 0.501328,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0385889);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489075,-99) , 
8, -5.15117, 1, 0, 0.519069,-99) , 
NN(
NN(
0, 
0, 
-1, 2.35329, 0, 1, 0.52429,-99) , 
NN(
0, 
0, 
-1, 5.67398, 1, -1, 0.48388,-99) , 
0, -0.811533, 0, 0, 0.491882,-99) , 
4, 3.42455, 0, 0, 0.49548,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0292002);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554958,-99) , 
NN(
0, 
0, 
-1, 0.609396, 0, -1, 0.492602,-99) , 
2, -0.766297, 0, 0, 0.516989,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494615,-99) , 
4, 3.40573, 0, 0, 0.500247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461943,-99) , 
2, 0.376026, 1, 0, 0.496868,-99) , 
1, 1.24494, 1, 0, 0.500469,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.041716);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536926,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642526,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463773,-99) , 
9, -2.05259, 1, 0, 0.495283,-99) , 
3, 0.170406, 1, 0, 0.503436,-99) , 
0, -3.24996, 1, 0, 0.505311,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0883188);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485303,-99) , 
1, 2.49375, 1, 0, 0.525764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452749,-99) , 
5, 6.09117, 1, 0, 0.507062,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536614,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440858,-99) , 
9, -3.69777, 1, 0, 0.474139,-99) , 
1, 2.69972, 0, 0, 0.487574,-99) , 
9, -3.0215, 0, 0, 0.499355,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0891725);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4316,-99) , 
9, -1.42211, 1, 0, 0.524409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438855,-99) , 
7, 5.92055, 1, 0, 0.510419,-99) , 
NN(
NN(
0, 
0, 
-1, 2.13965, 0, 1, 0.523408,-99) , 
NN(
0, 
0, 
-1, -3.32202, 1, -1, 0.467172,-99) , 
3, 2.1543, 0, 0, 0.488465,-99) , 
9, -3.0215, 0, 0, 0.50174,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0991683);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.07036, 1, 1, 0.549854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443054,-99) , 
7, 4.80897, 0, 0, 0.488252,-99) , 
8, -5.46225, 1, 0, 0.511162,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464781,-99) , 
1, 2.03009, 1, 0, 0.498606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415077,-99) , 
3, 3.05353, 1, 0, 0.475533,-99) , 
3, 2.23642, 1, 0, 0.499536,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0869021);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -5.15752, 1, 1, 0.539216,-99) , 
NN(
0, 
0, 
-1, 2.77393, 0, -1, 0.473256,-99) , 
7, 4.888, 1, 0, 0.510126,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559955,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454158,-99) , 
9, -3.58568, 1, 0, 0.473237,-99) , 
3, 0.989467, 1, 0, 0.488789,-99) , 
5, 5.24135, 1, 0, 0.49714,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0463057);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495443,-99) , 
7, 3.1856, 1, 0, 0.525409,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488402,-99) , 
2, -1.03833, 1, 0, 0.522376,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484655,-99) , 
1, 0.663518, 1, 0, 0.491212,-99) , 
8, -4.36813, 0, 0, 0.497056,-99) , 
7, 3.61005, 1, 0, 0.500434,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0453945);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496295,-99) , 
3, 1.66695, 1, 0, 0.524226,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546521,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418519,-99) , 
5, 6.51432, 1, 0, 0.496388,-99) , 
1, 0.344362, 1, 0, 0.501064,-99) , 
1, 2.69972, 0, 0, 0.507546,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0406355);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.06484, 0, 1, 0.558034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497844,-99) , 
1, 2.97682, 1, 0, 0.525832,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44133,-99) , 
9, -1.25825, 1, 0, 0.498158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45866,-99) , 
3, 2.94174, 1, 0, 0.492409,-99) , 
1, 2.69972, 0, 0, 0.50176,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0433012);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.66695, 1, 1, 0.526573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538331,-99) , 
NN(
0, 
0, 
-1, 5.71094, 1, -1, 0.482191,-99) , 
1, 0.344362, 1, 0, 0.487419,-99) , 
1, 2.69972, 0, 0, 0.49837,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.033985);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499123,-99) , 
2, -0.837612, 0, 0, 0.525993,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493241,-99) , 
9, -2.19099, 1, 0, 0.519924,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489378,-99) , 
1, 0.663518, 1, 0, 0.493441,-99) , 
8, -4.36813, 0, 0, 0.498408,-99) , 
7, 3.61005, 1, 0, 0.501689,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0338904);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.66695, 1, 1, 0.522882,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495803,-99) , 
8, -5.69471, 1, 0, 0.50582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471075,-99) , 
3, 2.94174, 1, 0, 0.500776,-99) , 
1, 2.69972, 0, 0, 0.50696,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0310774);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.1856, 1, 1, 0.527718,-99) , 
NN(
NN(
0, 
0, 
-1, -1.03833, 1, 1, 0.527279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474529,-99) , 
3, 2.51384, 1, 0, 0.500557,-99) , 
8, -4.36813, 0, 0, 0.505572,-99) , 
7, 3.61005, 1, 0, 0.508198,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0262638);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.67537, 0, 1, 0.507649,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458501,-99) , 
6, 2.50652, 1, 0, 0.490133,-99) , 
2, -0.128134, 1, 0, 0.504545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479301,-99) , 
6, 4.63172, 1, 0, 0.502668,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.034182);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619389,-99) , 
NN(
0, 
0, 
-1, 0.638442, 0, -1, 0.489446,-99) , 
3, 0.170406, 1, 0, 0.496538,-99) , 
0, -3.24996, 1, 0, 0.498246,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.032355);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.1856, 1, 1, 0.522572,-99) , 
NN(
NN(
0, 
0, 
-1, 2.95605, 0, 1, 0.513839,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4827,-99) , 
9, -3.11957, 1, 0, 0.494901,-99) , 
0, -1.20089, 0, 0, 0.502586,-99) , 
7, 3.61005, 1, 0, 0.504956,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0320286);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -5.28266, 0, 1, 0.518726,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494296,-99) , 
3, 2.00105, 1, 0, 0.520764,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486349,-99) , 
6, 2.43446, 1, 0, 0.495267,-99) , 
2, -1.47329, 1, 0, 0.500011,-99) , 
2, -2.05125, 1, 0, 0.502113,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0201624);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526226,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53288,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466323,-99) , 
6, 3.67011, 1, 0, 0.497951,-99) , 
4, 3.89348, 0, 0, 0.500758,-99) , 
4, 0.962701, 1, 0, 0.502949,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0285298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521197,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527858,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488751,-99) , 
0, -0.814242, 0, 0, 0.494179,-99) , 
4, 3.89348, 0, 0, 0.496885,-99) , 
4, 0.962701, 1, 0, 0.498976,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0391127);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540071,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474757,-99) , 
9, -2.84723, 1, 0, 0.49852,-99) , 
8, -5.78999, 1, 0, 0.509624,-99) , 
NN(
NN(
0, 
0, 
-1, -2.94142, 1, 1, 0.519218,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485606,-99) , 
6, 1.93232, 1, 0, 0.491006,-99) , 
2, -1.70045, 1, 0, 0.497869,-99) , 
4, 2.60394, 0, 0, 0.501535,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.020204);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523044,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49696,-99) , 
3, 0.989467, 1, 0, 0.502581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475519,-99) , 
2, 0.376026, 1, 0, 0.500556,-99) , 
4, 0.962701, 1, 0, 0.502492,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0309628);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497426,-99) , 
2, -0.837612, 0, 0, 0.518653,-99) , 
NN(
NN(
0, 
0, 
-1, -2.19099, 1, 1, 0.522252,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490387,-99) , 
5, 4.76182, 1, 0, 0.499058,-99) , 
8, -4.36813, 0, 0, 0.503404,-99) , 
7, 3.61005, 1, 0, 0.505213,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0465108);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496055,-99) , 
3, 1.66695, 1, 0, 0.515033,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457995,-99) , 
7, 5.53349, 1, 0, 0.508412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477387,-99) , 
8, -3.99697, 1, 0, 0.503134,-99) , 
1, 2.69972, 0, 0, 0.506458,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0533084);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.06484, 0, 1, 0.541578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495093,-99) , 
1, 2.97682, 1, 0, 0.516675,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490421,-99) , 
7, 4.01049, 1, 0, 0.512297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478027,-99) , 
3, 0.279471, 1, 0, 0.490837,-99) , 
3, 2.1543, 0, 0, 0.499296,-99) , 
1, 2.69972, 0, 0, 0.504152,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0474461);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.22919, 1, 1, 0.527793,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497223,-99) , 
3, 1.78898, 1, 0, 0.509302,-99) , 
2, -0.510865, 0, 0, 0.514753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606894,-99) , 
NN(
0, 
0, 
-1, 0.61975, 0, -1, 0.47667,-99) , 
3, 0.152791, 1, 0, 0.500627,-99) , 
3, 1.37846, 0, 0, 0.510734,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0407357);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.51425, 1, 1, 0.526589,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490587,-99) , 
3, 2.08644, 0, 0, 0.505457,-99) , 
2, -1.12658, 1, 0, 0.515598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492509,-99) , 
2, 0.376026, 1, 0, 0.513527,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0399718);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.66695, 1, 1, 0.518747,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463077,-99) , 
9, -1.25825, 1, 0, 0.512097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484943,-99) , 
3, 2.94174, 1, 0, 0.508154,-99) , 
1, 2.69972, 0, 0, 0.511115,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.024415);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523262,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584973,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429697,-99) , 
3, 0.638442, 0, 0, 0.499007,-99) , 
3, 0.170406, 1, 0, 0.503662,-99) , 
0, -3.24996, 1, 0, 0.504763,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0515458);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.86917, 1, 1, 0.540812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415267,-99) , 
9, -0.965118, 1, 0, 0.483043,-99) , 
9, -2.48836, 1, 0, 0.503073,-99) , 
NN(
NN(
0, 
0, 
-1, 2.13965, 1, 1, 0.523681,-99) , 
NN(
0, 
0, 
-1, -3.32202, 1, -1, 0.475493,-99) , 
3, 2.1543, 0, 0, 0.493636,-99) , 
9, -3.0215, 0, 0, 0.499305,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0301429);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512942,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584515,-99) , 
NN(
0, 
0, 
-1, 0.134991, 1, -1, 0.488761,-99) , 
3, 0.170406, 1, 0, 0.493927,-99) , 
0, -3.24996, 1, 0, 0.494995,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0340982);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.03913, 0, 1, 0.510712,-99) , 
NN(
0, 
0, 
-1, 2.45307, 0, -1, 0.475312,-99) , 
2, -0.325371, 1, 0, 0.50448,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526598,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467703,-99) , 
9, -3.26572, 1, 0, 0.48144,-99) , 
7, 4.04388, 1, 0, 0.492151,-99) , 
0, -1.76087, 0, 0, 0.500917,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0243115);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51237,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493262,-99) , 
3, 0.989467, 1, 0, 0.499545,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467747,-99) , 
9, -2.71038, 1, 0, 0.485592,-99) , 
0, -1.76373, 0, 0, 0.495714,-99) , 
4, 0.962701, 1, 0, 0.49715,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.026167);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499559,-99) , 
0, -1.17272, 0, 0, 0.522512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477088,-99) , 
6, 3.25947, 1, 0, 0.495222,-99) , 
4, 2.93817, 0, 0, 0.502278,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486953,-99) , 
2, -0.496743, 0, 0, 0.498499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461521,-99) , 
4, 2.60394, 1, 0, 0.491597,-99) , 
0, -1.76087, 0, 0, 0.499193,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0213238);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488022,-99) , 
6, 3.73346, 0, 0, 0.513603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51533,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492647,-99) , 
2, -2.3023, 1, 0, 0.494442,-99) , 
4, 3.07284, 0, 0, 0.495928,-99) , 
4, 3.42455, 0, 0, 0.498255,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0374003);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.71857, 0, 1, 0.530356,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461299,-99) , 
9, -2.66317, 1, 0, 0.493384,-99) , 
1, 2.10839, 1, 0, 0.508797,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489872,-99) , 
8, -5.46225, 1, 0, 0.510347,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485911,-99) , 
8, -4.93411, 0, 0, 0.493361,-99) , 
2, -0.455343, 0, 0, 0.497882,-99) , 
6, 3.21501, 0, 0, 0.501455,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0129989);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493566,-99) , 
6, 3.73346, 0, 0, 0.511661,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499118,-99) , 
0, -0.596927, 0, 0, 0.501872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485709,-99) , 
6, 4.03505, 1, 0, 0.500015,-99) , 
4, 3.42455, 0, 0, 0.501547,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0234057);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549009,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493578,-99) , 
5, 5.24135, 1, 0, 0.500601,-99) , 
3, 1.01085, 1, 0, 0.505057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492145,-99) , 
3, 0.520503, 0, 0, 0.503862,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0339304);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494782,-99) , 
3, 1.66695, 1, 0, 0.510769,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445995,-99) , 
7, 5.71094, 1, 0, 0.499618,-99) , 
1, 0.344362, 1, 0, 0.502639,-99) , 
1, 2.69972, 0, 0, 0.504912,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0238663);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.97682, 1, 1, 0.521574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491108,-99) , 
8, -5.07123, 1, 0, 0.511988,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443156,-99) , 
5, 6.51432, 1, 0, 0.493629,-99) , 
1, 0.344362, 1, 0, 0.496418,-99) , 
1, 2.69972, 0, 0, 0.500771,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0416273);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530908,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483508,-99) , 
8, -5.75253, 1, 0, 0.500399,-99) , 
9, -3.0215, 1, 0, 0.50978,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517529,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478927,-99) , 
9, -3.44831, 1, 0, 0.489202,-99) , 
1, 0.344362, 1, 0, 0.491848,-99) , 
1, 2.69972, 0, 0, 0.496861,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.04501);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489517,-99) , 
2, -1.06484, 0, 0, 0.519815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497274,-99) , 
1, 2.97682, 1, 0, 0.507739,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451994,-99) , 
7, 5.03467, 0, 0, 0.510431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475987,-99) , 
7, 4.68468, 1, 0, 0.490028,-99) , 
9, -2.1119, 0, 0, 0.49531,-99) , 
1, 2.69972, 0, 0, 0.498784,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0432833);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.66695, 1, 1, 0.513354,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459933,-99) , 
7, 4.5295, 0, 0, 0.491403,-99) , 
8, -6.1029, 1, 0, 0.495234,-99) , 
1, 2.69972, 0, 0, 0.5003,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0591924);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.86917, 1, 1, 0.537248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462702,-99) , 
8, -6.46052, 1, 0, 0.478854,-99) , 
9, -2.48836, 1, 0, 0.499191,-99) , 
NN(
NN(
0, 
0, 
-1, 2.13965, 1, 1, 0.508453,-99) , 
NN(
0, 
0, 
-1, 4.5715, 0, -1, 0.477741,-99) , 
3, 2.1543, 0, 0, 0.489307,-99) , 
9, -3.0215, 0, 0, 0.495236,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0502809);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497147,-99) , 
3, 1.26027, 1, 0, 0.509583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469672,-99) , 
5, 6.27844, 1, 0, 0.502986,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467937,-99) , 
7, 4.1846, 1, 0, 0.498881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447904,-99) , 
3, 3.05353, 1, 0, 0.484773,-99) , 
3, 2.23642, 1, 0, 0.497028,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0519166);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.07036, 1, 1, 0.525151,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417759,-99) , 
7, 3.81538, 0, 0, 0.498354,-99) , 
8, -5.46225, 1, 0, 0.508347,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461537,-99) , 
7, 4.72897, 1, 0, 0.50257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460367,-99) , 
3, 3.05353, 1, 0, 0.490895,-99) , 
3, 2.23642, 1, 0, 0.502644,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0474474);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494655,-99) , 
8, -5.68556, 1, 0, 0.508191,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478364,-99) , 
2, -0.510865, 0, 0, 0.489272,-99) , 
3, 2.27728, 1, 0, 0.500077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565794,-99) , 
NN(
0, 
0, 
-1, 0.61975, 0, -1, 0.467013,-99) , 
3, 0.152791, 1, 0, 0.485079,-99) , 
3, 1.37846, 0, 0, 0.495849,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0234645);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495631,-99) , 
2, -1.47285, 1, 0, 0.501721,-99) , 
3, 1.01085, 1, 0, 0.504604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474601,-99) , 
3, 0.520503, 0, 0, 0.501844,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0361996);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.1119, 0, 1, 0.516315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488299,-99) , 
9, -3.58568, 1, 0, 0.499977,-99) , 
5, 5.24135, 1, 0, 0.506447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480455,-99) , 
3, 0.520503, 0, 0, 0.504057,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0440988);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.04386, 1, 1, 0.519357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451274,-99) , 
7, 4.81759, 1, 0, 0.487301,-99) , 
2, -0.573301, 1, 0, 0.509316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531456,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482739,-99) , 
2, -0.160998, 0, 0, 0.491025,-99) , 
6, 3.92336, 0, 0, 0.497724,-99) , 
5, 5.24135, 0, 0, 0.504749,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0290247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467655,-99) , 
7, 4.83941, 0, 0, 0.515827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495843,-99) , 
7, 3.61005, 1, 0, 0.500301,-99) , 
8, -4.36813, 0, 0, 0.503052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481452,-99) , 
6, 4.63172, 1, 0, 0.501453,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0291502);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.1119, 0, 1, 0.516895,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492865,-99) , 
9, -3.58568, 1, 0, 0.501864,-99) , 
5, 5.24135, 1, 0, 0.50782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487987,-99) , 
3, 0.520503, 0, 0, 0.506002,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0222552);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525507,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483568,-99) , 
6, 4.03505, 1, 0, 0.505552,-99) , 
4, 3.40573, 0, 0, 0.508238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489537,-99) , 
2, 0.376026, 1, 0, 0.506556,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0309304);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528954,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494547,-99) , 
9, -3.58568, 1, 0, 0.501687,-99) , 
3, 0.989467, 1, 0, 0.506441,-99) , 
NN(
NN(
0, 
0, 
-1, 3.75478, 0, 1, 0.515086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478512,-99) , 
2, -0.510844, 0, 0, 0.489137,-99) , 
6, 3.21501, 0, 0, 0.49747,-99) , 
5, 5.24135, 0, 0, 0.502904,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0398798);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -5.68556, 1, 1, 0.516064,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487179,-99) , 
6, 2.56104, 1, 0, 0.497173,-99) , 
3, 2.27728, 1, 0, 0.507965,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5644,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438593,-99) , 
1, 1.94096, 0, 0, 0.47959,-99) , 
3, 0.152791, 1, 0, 0.495079,-99) , 
3, 1.37846, 0, 0, 0.504339,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0184823);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521054,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493811,-99) , 
7, 4.48839, 1, 0, 0.499655,-99) , 
3, 1.01085, 1, 0, 0.501606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481486,-99) , 
3, 0.520503, 0, 0, 0.499765,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0296332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.78468, 0, 1, 0.511529,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466151,-99) , 
6, 2.88968, 1, 0, 0.490924,-99) , 
2, -0.573301, 1, 0, 0.505077,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491373,-99) , 
0, -0.999228, 0, 0, 0.49963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475027,-99) , 
3, 1.29193, 0, 0, 0.493558,-99) , 
5, 5.24135, 0, 0, 0.500535,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0368626);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514394,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469054,-99) , 
7, 5.26354, 1, 0, 0.498847,-99) , 
4, 1.47235, 1, 0, 0.501821,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558036,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44792,-99) , 
9, -2.23626, 1, 0, 0.476828,-99) , 
3, 0.152791, 1, 0, 0.491629,-99) , 
3, 1.37846, 0, 0, 0.498955,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0587258);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444954,-99) , 
9, -1.42211, 1, 0, 0.50703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452993,-99) , 
7, 5.92055, 1, 0, 0.498058,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482965,-99) , 
5, 6.14954, 0, 0, 0.49775,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449075,-99) , 
2, -0.16699, 1, 0, 0.469681,-99) , 
2, -0.573301, 1, 0, 0.488408,-99) , 
9, -3.0215, 0, 0, 0.494181,-99)    );
   return;
};

// Clean up
inline void ReadBDTD::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDTD::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadBDTD::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 2.1304771425;
   fDecTF_1[0][0][1] = -0.0319562794098;
   fDecTF_1[0][0][2] = -0.812960735387;
   fDecTF_1[0][0][3] = 0.0137605532902;
   fDecTF_1[0][0][4] = -1.07109492508;
   fDecTF_1[0][0][5] = 0.017658561536;
   fDecTF_1[0][0][6] = 0.0876212275811;
   fDecTF_1[0][0][7] = -0.0136443354077;
   fDecTF_1[0][0][8] = -0.0105691952206;
   fDecTF_1[0][0][9] = 0.0172568381001;
   fDecTF_1[0][1][0] = -0.0319562794098;
   fDecTF_1[0][1][1] = 7.23412951159;
   fDecTF_1[0][1][2] = 0.0192499474201;
   fDecTF_1[0][1][3] = -4.11201954287;
   fDecTF_1[0][1][4] = 0.0241993841893;
   fDecTF_1[0][1][5] = 1.05422155357;
   fDecTF_1[0][1][6] = -0.00149641113169;
   fDecTF_1[0][1][7] = -0.335735472396;
   fDecTF_1[0][1][8] = -5.55637484367;
   fDecTF_1[0][1][9] = 3.03713342467;
   fDecTF_1[0][2][0] = -0.812960735387;
   fDecTF_1[0][2][1] = 0.0192499474201;
   fDecTF_1[0][2][2] = 2.58701204657;
   fDecTF_1[0][2][3] = -0.0308231622281;
   fDecTF_1[0][2][4] = 0.290347469476;
   fDecTF_1[0][2][5] = 0.0124659772984;
   fDecTF_1[0][2][6] = -1.18673037024;
   fDecTF_1[0][2][7] = 0.0450017952903;
   fDecTF_1[0][2][8] = 0.00855539492599;
   fDecTF_1[0][2][9] = -0.0762839189284;
   fDecTF_1[0][3][0] = 0.0137605532902;
   fDecTF_1[0][3][1] = -4.11201954287;
   fDecTF_1[0][3][2] = -0.0308231622281;
   fDecTF_1[0][3][3] = 7.36171694118;
   fDecTF_1[0][3][4] = -0.00335556603703;
   fDecTF_1[0][3][5] = -0.245037986151;
   fDecTF_1[0][3][6] = 0.0300039394433;
   fDecTF_1[0][3][7] = 0.427921975154;
   fDecTF_1[0][3][8] = 2.77514554777;
   fDecTF_1[0][3][9] = -4.77242222226;
   fDecTF_1[0][4][0] = -1.07109492508;
   fDecTF_1[0][4][1] = 0.0241993841893;
   fDecTF_1[0][4][2] = 0.290347469476;
   fDecTF_1[0][4][3] = -0.00335556603703;
   fDecTF_1[0][4][4] = 3.20973745061;
   fDecTF_1[0][4][5] = -0.0961590069434;
   fDecTF_1[0][4][6] = -1.68135243109;
   fDecTF_1[0][4][7] = 0.0357203228349;
   fDecTF_1[0][4][8] = -0.0356457170063;
   fDecTF_1[0][4][9] = 0.0258688325627;
   fDecTF_1[0][5][0] = 0.017658561536;
   fDecTF_1[0][5][1] = 1.05422155357;
   fDecTF_1[0][5][2] = 0.0124659772984;
   fDecTF_1[0][5][3] = -0.245037986151;
   fDecTF_1[0][5][4] = -0.0961590069434;
   fDecTF_1[0][5][5] = 4.57729539711;
   fDecTF_1[0][5][6] = 0.0531888193852;
   fDecTF_1[0][5][7] = -1.49816366959;
   fDecTF_1[0][5][8] = -2.8652665033;
   fDecTF_1[0][5][9] = 0.432982025296;
   fDecTF_1[0][6][0] = 0.0876212275811;
   fDecTF_1[0][6][1] = -0.00149641113169;
   fDecTF_1[0][6][2] = -1.18673037024;
   fDecTF_1[0][6][3] = 0.0300039394433;
   fDecTF_1[0][6][4] = -1.68135243109;
   fDecTF_1[0][6][5] = 0.0531888193852;
   fDecTF_1[0][6][6] = 3.40570814839;
   fDecTF_1[0][6][7] = -0.115712363341;
   fDecTF_1[0][6][8] = 0.00088427993085;
   fDecTF_1[0][6][9] = -0.0151335474831;
   fDecTF_1[0][7][0] = -0.0136443354077;
   fDecTF_1[0][7][1] = -0.335735472396;
   fDecTF_1[0][7][2] = 0.0450017952903;
   fDecTF_1[0][7][3] = 0.427921975154;
   fDecTF_1[0][7][4] = 0.0357203228349;
   fDecTF_1[0][7][5] = -1.49816366959;
   fDecTF_1[0][7][6] = -0.115712363341;
   fDecTF_1[0][7][7] = 4.1718454501;
   fDecTF_1[0][7][8] = 0.209339602657;
   fDecTF_1[0][7][9] = -1.89556158873;
   fDecTF_1[0][8][0] = -0.0105691952206;
   fDecTF_1[0][8][1] = -5.55637484367;
   fDecTF_1[0][8][2] = 0.00855539492599;
   fDecTF_1[0][8][3] = 2.77514554777;
   fDecTF_1[0][8][4] = -0.0356457170063;
   fDecTF_1[0][8][5] = -2.8652665033;
   fDecTF_1[0][8][6] = 0.00088427993085;
   fDecTF_1[0][8][7] = 0.209339602657;
   fDecTF_1[0][8][8] = 7.12154885484;
   fDecTF_1[0][8][9] = -2.92920776799;
   fDecTF_1[0][9][0] = 0.0172568381001;
   fDecTF_1[0][9][1] = 3.03713342467;
   fDecTF_1[0][9][2] = -0.0762839189284;
   fDecTF_1[0][9][3] = -4.77242222226;
   fDecTF_1[0][9][4] = 0.0258688325627;
   fDecTF_1[0][9][5] = 0.432982025296;
   fDecTF_1[0][9][6] = -0.0151335474831;
   fDecTF_1[0][9][7] = -1.89556158873;
   fDecTF_1[0][9][8] = -2.92920776799;
   fDecTF_1[0][9][9] = 5.77749703647;
   fDecTF_1[1][0][0] = 1.95457500418;
   fDecTF_1[1][0][1] = -0.0630867194604;
   fDecTF_1[1][0][2] = -0.422402986446;
   fDecTF_1[1][0][3] = 0.0659890723767;
   fDecTF_1[1][0][4] = -1.07091277024;
   fDecTF_1[1][0][5] = 0.0187151249034;
   fDecTF_1[1][0][6] = 0.0128426419873;
   fDecTF_1[1][0][7] = 0.00456498378273;
   fDecTF_1[1][0][8] = -0.0432721141989;
   fDecTF_1[1][0][9] = -0.000771695010316;
   fDecTF_1[1][1][0] = -0.0630867194604;
   fDecTF_1[1][1][1] = 4.35793258546;
   fDecTF_1[1][1][2] = 0.0143556801491;
   fDecTF_1[1][1][3] = -1.67988877811;
   fDecTF_1[1][1][4] = 0.0748959733015;
   fDecTF_1[1][1][5] = 0.469329737413;
   fDecTF_1[1][1][6] = -0.096862744879;
   fDecTF_1[1][1][7] = -0.319833175157;
   fDecTF_1[1][1][8] = -2.94966662872;
   fDecTF_1[1][1][9] = 1.74272489555;
   fDecTF_1[1][2][0] = -0.422402986446;
   fDecTF_1[1][2][1] = 0.0143556801491;
   fDecTF_1[1][2][2] = 2.19992241442;
   fDecTF_1[1][2][3] = -0.182018704253;
   fDecTF_1[1][2][4] = 0.230602728694;
   fDecTF_1[1][2][5] = -0.00183055378974;
   fDecTF_1[1][2][6] = -1.12883421096;
   fDecTF_1[1][2][7] = 0.0843621553963;
   fDecTF_1[1][2][8] = 0.019076893838;
   fDecTF_1[1][2][9] = 0.00395560791485;
   fDecTF_1[1][3][0] = 0.0659890723767;
   fDecTF_1[1][3][1] = -1.67988877811;
   fDecTF_1[1][3][2] = -0.182018704253;
   fDecTF_1[1][3][3] = 6.54139070215;
   fDecTF_1[1][3][4] = -0.0174120520006;
   fDecTF_1[1][3][5] = -0.300493954086;
   fDecTF_1[1][3][6] = 0.116279737829;
   fDecTF_1[1][3][7] = 0.552214096317;
   fDecTF_1[1][3][8] = 1.3430569895;
   fDecTF_1[1][3][9] = -3.50579073605;
   fDecTF_1[1][4][0] = -1.07091277024;
   fDecTF_1[1][4][1] = 0.0748959733015;
   fDecTF_1[1][4][2] = 0.230602728694;
   fDecTF_1[1][4][3] = -0.0174120520006;
   fDecTF_1[1][4][4] = 2.38143105258;
   fDecTF_1[1][4][5] = -0.0636526881258;
   fDecTF_1[1][4][6] = -0.827260647976;
   fDecTF_1[1][4][7] = 0.0369492490317;
   fDecTF_1[1][4][8] = -0.0873470001176;
   fDecTF_1[1][4][9] = 0.0200568755527;
   fDecTF_1[1][5][0] = 0.0187151249034;
   fDecTF_1[1][5][1] = 0.469329737413;
   fDecTF_1[1][5][2] = -0.00183055378974;
   fDecTF_1[1][5][3] = -0.300493954086;
   fDecTF_1[1][5][4] = -0.0636526881258;
   fDecTF_1[1][5][5] = 2.8165469292;
   fDecTF_1[1][5][6] = 0.0615564831243;
   fDecTF_1[1][5][7] = -0.869438553384;
   fDecTF_1[1][5][8] = -1.903513524;
   fDecTF_1[1][5][9] = 0.359452130207;
   fDecTF_1[1][6][0] = 0.0128426419873;
   fDecTF_1[1][6][1] = -0.096862744879;
   fDecTF_1[1][6][2] = -1.12883421096;
   fDecTF_1[1][6][3] = 0.116279737829;
   fDecTF_1[1][6][4] = -0.827260647976;
   fDecTF_1[1][6][5] = 0.0615564831243;
   fDecTF_1[1][6][6] = 2.38230355356;
   fDecTF_1[1][6][7] = -0.113343379045;
   fDecTF_1[1][6][8] = 0.0418160158332;
   fDecTF_1[1][6][9] = -0.0656233936447;
   fDecTF_1[1][7][0] = 0.00456498378273;
   fDecTF_1[1][7][1] = -0.319833175157;
   fDecTF_1[1][7][2] = 0.0843621553963;
   fDecTF_1[1][7][3] = 0.552214096317;
   fDecTF_1[1][7][4] = 0.0369492490317;
   fDecTF_1[1][7][5] = -0.869438553384;
   fDecTF_1[1][7][6] = -0.113343379045;
   fDecTF_1[1][7][7] = 2.78979043582;
   fDecTF_1[1][7][8] = 0.588190483265;
   fDecTF_1[1][7][9] = -1.71542574361;
   fDecTF_1[1][8][0] = -0.0432721141989;
   fDecTF_1[1][8][1] = -2.94966662872;
   fDecTF_1[1][8][2] = 0.019076893838;
   fDecTF_1[1][8][3] = 1.3430569895;
   fDecTF_1[1][8][4] = -0.0873470001176;
   fDecTF_1[1][8][5] = -1.903513524;
   fDecTF_1[1][8][6] = 0.0418160158332;
   fDecTF_1[1][8][7] = 0.588190483265;
   fDecTF_1[1][8][8] = 4.09192004356;
   fDecTF_1[1][8][9] = -2.1265329463;
   fDecTF_1[1][9][0] = -0.000771695010316;
   fDecTF_1[1][9][1] = 1.74272489555;
   fDecTF_1[1][9][2] = 0.00395560791485;
   fDecTF_1[1][9][3] = -3.50579073605;
   fDecTF_1[1][9][4] = 0.0200568755527;
   fDecTF_1[1][9][5] = 0.359452130207;
   fDecTF_1[1][9][6] = -0.0656233936447;
   fDecTF_1[1][9][7] = -1.71542574361;
   fDecTF_1[1][9][8] = -2.1265329463;
   fDecTF_1[1][9][9] = 4.68462161847;
   fDecTF_1[2][0][0] = 2.06802424543;
   fDecTF_1[2][0][1] = -0.0479636182949;
   fDecTF_1[2][0][2] = -0.697721641958;
   fDecTF_1[2][0][3] = 0.0601190665149;
   fDecTF_1[2][0][4] = -1.08876230654;
   fDecTF_1[2][0][5] = 0.0049159736184;
   fDecTF_1[2][0][6] = 0.0910847539647;
   fDecTF_1[2][0][7] = 0.00799326883305;
   fDecTF_1[2][0][8] = -0.0223746258886;
   fDecTF_1[2][0][9] = 0.020484185022;
   fDecTF_1[2][1][0] = -0.0479636182949;
   fDecTF_1[2][1][1] = 5.81447449315;
   fDecTF_1[2][1][2] = 0.0449817258583;
   fDecTF_1[2][1][3] = -3.36821508897;
   fDecTF_1[2][1][4] = 0.0400463425151;
   fDecTF_1[2][1][5] = 0.890427790379;
   fDecTF_1[2][1][6] = -0.0368463250188;
   fDecTF_1[2][1][7] = -0.475740098212;
   fDecTF_1[2][1][8] = -4.27502268488;
   fDecTF_1[2][1][9] = 2.61498830666;
   fDecTF_1[2][2][0] = -0.697721641958;
   fDecTF_1[2][2][1] = 0.0449817258583;
   fDecTF_1[2][2][2] = 2.44006066829;
   fDecTF_1[2][2][3] = -0.128158571098;
   fDecTF_1[2][2][4] = 0.308915983052;
   fDecTF_1[2][2][5] = 0.0219180349882;
   fDecTF_1[2][2][6] = -1.19810535333;
   fDecTF_1[2][2][7] = 0.0262801076011;
   fDecTF_1[2][2][8] = 0.0115818592991;
   fDecTF_1[2][2][9] = -0.0912589546445;
   fDecTF_1[2][3][0] = 0.0601190665149;
   fDecTF_1[2][3][1] = -3.36821508897;
   fDecTF_1[2][3][2] = -0.128158571098;
   fDecTF_1[2][3][3] = 6.50942468791;
   fDecTF_1[2][3][4] = 0.00584740639078;
   fDecTF_1[2][3][5] = -0.115932546332;
   fDecTF_1[2][3][6] = 0.0494285175362;
   fDecTF_1[2][3][7] = 0.317423680749;
   fDecTF_1[2][3][8] = 2.30082961948;
   fDecTF_1[2][3][9] = -4.220022029;
   fDecTF_1[2][4][0] = -1.08876230654;
   fDecTF_1[2][4][1] = 0.0400463425151;
   fDecTF_1[2][4][2] = 0.308915983052;
   fDecTF_1[2][4][3] = 0.00584740639078;
   fDecTF_1[2][4][4] = 2.90372693539;
   fDecTF_1[2][4][5] = -0.0961059576998;
   fDecTF_1[2][4][6] = -1.36178172236;
   fDecTF_1[2][4][7] = 0.0523220317084;
   fDecTF_1[2][4][8] = -0.0653053800059;
   fDecTF_1[2][4][9] = 0.055778567692;
   fDecTF_1[2][5][0] = 0.0049159736184;
   fDecTF_1[2][5][1] = 0.890427790379;
   fDecTF_1[2][5][2] = 0.0219180349882;
   fDecTF_1[2][5][3] = -0.115932546332;
   fDecTF_1[2][5][4] = -0.0961059576998;
   fDecTF_1[2][5][5] = 3.87458424227;
   fDecTF_1[2][5][6] = 0.0624915801325;
   fDecTF_1[2][5][7] = -1.15814320229;
   fDecTF_1[2][5][8] = -2.58397770565;
   fDecTF_1[2][5][9] = 0.337198525603;
   fDecTF_1[2][6][0] = 0.0910847539647;
   fDecTF_1[2][6][1] = -0.0368463250188;
   fDecTF_1[2][6][2] = -1.19810535333;
   fDecTF_1[2][6][3] = 0.0494285175362;
   fDecTF_1[2][6][4] = -1.36178172236;
   fDecTF_1[2][6][5] = 0.0624915801325;
   fDecTF_1[2][6][6] = 3.03169087473;
   fDecTF_1[2][6][7] = -0.128526205487;
   fDecTF_1[2][6][8] = 0.0243482363922;
   fDecTF_1[2][6][9] = -0.0639339137341;
   fDecTF_1[2][7][0] = 0.00799326883305;
   fDecTF_1[2][7][1] = -0.475740098212;
   fDecTF_1[2][7][2] = 0.0262801076011;
   fDecTF_1[2][7][3] = 0.317423680749;
   fDecTF_1[2][7][4] = 0.0523220317084;
   fDecTF_1[2][7][5] = -1.15814320229;
   fDecTF_1[2][7][6] = -0.128526205487;
   fDecTF_1[2][7][7] = 3.51097407603;
   fDecTF_1[2][7][8] = 0.474854037905;
   fDecTF_1[2][7][9] = -1.78583103769;
   fDecTF_1[2][8][0] = -0.0223746258886;
   fDecTF_1[2][8][1] = -4.27502268488;
   fDecTF_1[2][8][2] = 0.0115818592991;
   fDecTF_1[2][8][3] = 2.30082961948;
   fDecTF_1[2][8][4] = -0.0653053800059;
   fDecTF_1[2][8][5] = -2.58397770565;
   fDecTF_1[2][8][6] = 0.0243482363922;
   fDecTF_1[2][8][7] = 0.474854037906;
   fDecTF_1[2][8][8] = 5.71786084331;
   fDecTF_1[2][8][9] = -2.64107936924;
   fDecTF_1[2][9][0] = 0.020484185022;
   fDecTF_1[2][9][1] = 2.61498830666;
   fDecTF_1[2][9][2] = -0.0912589546445;
   fDecTF_1[2][9][3] = -4.220022029;
   fDecTF_1[2][9][4] = 0.055778567692;
   fDecTF_1[2][9][5] = 0.337198525603;
   fDecTF_1[2][9][6] = -0.0639339137341;
   fDecTF_1[2][9][7] = -1.78583103769;
   fDecTF_1[2][9][8] = -2.64107936924;
   fDecTF_1[2][9][9] = 5.21807478868;
}

//_______________________________________________________________________
inline void ReadBDTD::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   }

   std::vector<double> tv;
   for (int i=0; i<10;i++) {
      double v = 0;
      for (int j=0; j<10; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<10;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadBDTD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadBDTD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
